### ISSUE TITLE
Failed to send file

### ISSUE THREAD

**Issue by susobaco** [kontalk/androidclient#1034]
### Expected behavior
May this message disappear

### Actual behavior
A message appears every few minutes saying: "Failed to send file"

### Steps to reproduce
1. I reconnect the client to the server.
2. The message appears and I recognize it.
3. After a few minutes, the message reappears

### Environment

Kontalk version: 4.0.3 F-droid

Android version: Android 4.4.0

Device model: Primux Omega 6

### Logs

W/MessageCenterService: no upload info received yet, delaying media message
W/MessageCenterService: no upload info received yet, delaying media message
W/MessageCenterService: error preprocessing media: content://com.android.contacts/contacts/as_vcard/****************-****-****-****-**************%2540cloud..openmailbox..org..vcf
W/MessageCenterService: java.io.FileNotFoundException: Unable to create stream
	at android.content.ContentResolver.openInputStream(ContentResolver.java:682)
	at org.kontalk.service.msgcenter.MessageCenterService.sendMessage(MessageCenterService.java:2338)
	at org.kontalk.service.msgcenter.MessageCenterService.sendMessages(MessageCenterService.java:1977)
	at org.kontalk.service.msgcenter.MessageCenterService.resendPendingMessages(MessageCenterService.java:1833)
	at org.kontalk.service.msgcenter.MessageCenterService.resendPendingMessages(MessageCenterService.java:1747)
	at org.kontalk.service.msgcenter.MessageCenterPacketListener$1.run(MessageCenterPacketListener.java:141)
	at android.os.Handler.handleCallback(Handler.java:815)
	at android.os.Handler.dispatchMessage(Handler.java:104)
	at android.os.Looper.loop(Looper.java:207)
	at android.app.ActivityThread.main(ActivityThread.java:5728)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679)

**Comment by daniele-athome** [comment]
What are you trying to share? It seems that Kontalk can't access the original content for some reason. Where does it come from?

**Comment by susobaco** [comment]
I do not know, it seems like it does not find a file to attach, it seems like a bug when sending and it keeps repeating. Is it not possible to eliminate this warning?

**Comment by daniele-athome** [comment]
Oh ok if you refer to the fact that Kontalk keeps trying, you should delete the message to make it stop.

**Comment by susobaco** [comment]
Impossible, I deleted all the conversations and the error message is still coming out.

**Comment by daniele-athome** [comment]
Ok that is weird. Does it happen if you also kill the application and start it again?

**Comment by susobaco** [comment]
Sorry, sorry, and 1000 sorrys, I was missing a conversation to clean, the last.... "Mr Murphy". I am sorry.
Anyway, in the future, it would be interesting to open the error message, it will take you directly to the message that gives the error, thus, you can avoid clearing the conversations until you find the message that gives the error.

**Comment by daniele-athome** [comment]
> Anyway, in the future, it would be interesting to open the error message, it will take you directly to the message that gives the error, thus, you can avoid clearing the conversations until you find the message that gives the error.

You're right, good idea. I opened #1035.
