### ISSUE TITLE
Request ignore battery optimization action is not handled on Samsung devices

### ISSUE THREAD

**Issue by daniele-athome** [kontalk/androidclient#1037]
Obviously people at Samsung doesn't think that respecting Android APIs is worth the effort...

```
android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.settings.REQUEST_IGNORE_BATTERY_OPTIMIZATIONS dat=package:org.kontalk }
       at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1878)
       at android.app.Instrumentation.execStartActivity(Instrumentation.java:1545)
       at android.app.Activity.startActivityForResult(Activity.java:4283)
       at android.support.v4.app.BaseFragmentActivityJB.startActivityForResult(BaseFragmentActivityJB.java:50)
       at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:79)
       at android.app.Activity.startActivityForResult(Activity.java:4230)
       at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:859)
       at android.app.Activity.startActivity(Activity.java:4567)
       at android.app.Activity.startActivity(Activity.java:4535)
       at org.kontalk.ui.MainActivity.requestDozeModeWhitelist(MainActivity.java:134)
       at org.kontalk.ui.MainActivity$3.onClick(MainActivity.java:106)
       at com.afollestad.materialdialogs.MaterialDialog.onClick(MaterialDialog.java:367)
```

**Comment by daniele-athome** [comment]
Falling back even more in be78119687940545d3613ae0d4280f4068125f6a.
