### ISSUE TITLE
Null reference when stopping right after starting audio play

### ISSUE THREAD

**Issue by daniele-athome** [kontalk/androidclient#1045]
That's some serious race condition here.

```
java.lang.NullPointerException: Attempt to invoke virtual method 'void com.nineoldandroids.animation.ObjectAnimator.cancel()' on a null object reference
       at org.kontalk.ui.AudioDialog.pauseAudio(AudioDialog.java:444)
       at org.kontalk.ui.AudioDialog.finish(AudioDialog.java:291)
       at org.kontalk.ui.AudioDialog.onStop(AudioDialog.java:280)
       at android.app.Dialog.dismissDialog(Dialog.java:553)
       at android.app.Dialog.dismiss(Dialog.java:529)
       at android.support.v7.app.AlertController$ButtonHandler.handleMessage(AlertController.java:165)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:158)
       at android.app.ActivityThread.main(ActivityThread.java:7224)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
```

**Comment by daniele-athome** [comment]
Unable to reproduce.
