### ISSUE TITLE
Possible issue with Proguard

### ISSUE THREAD

**Issue by daniele-athome** [kontalk/androidclient#1047]
Even if it was very well tested...

```
java.lang.NoClassDefFoundError: com.bumptech.glide.Glide
       at org.kontalk.util.GlideApp.with(GlideApp.java:78)
       at org.kontalk.ui.CodeValidation.onCreate(CodeValidation.java:250)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1047)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:1615)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:1667)
       at android.app.ActivityThread.access$1500(ActivityThread.java:117)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:935)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:130)
       at android.app.ActivityThread.main(ActivityThread.java:3687)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:507)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:625)
       at dalvik.system.NativeStart.main(NativeStart.java)
```

**Comment by daniele-athome** [comment]
Glide 4 incompatibility with Android 2. Downgraded to Glide 3.
