### ISSUE TITLE
Still null reference for selected items

### ISSUE THREAD

**Issue by daniele-athome** [kontalk/androidclient#1048]
Null SparseArray here. Maybe we should focus on the akalipetis implementation of ActionModeListFragment? What's the compatibility level of that API? Is there something available in appcompat?

```
java.lang.NullPointerException: Null reference used for synchronization (monitor-enter)
       at org.kontalk.util.SystemUtils.cloneSparseBooleanArray(SystemUtils.java:303)
       at org.kontalk.ui.AbstractComposeFragment.onActionItemClicked(AbstractComposeFragment.java:466)
       at com.akalipetis.fragment.ActionModeListFragment$InternalV11Listener.onActionItemClicked(ActionModeListFragment.java:153)
       at android.widget.AbsListView$MultiChoiceModeWrapper.onActionItemClicked(AbsListView.java:6440)
       at com.android.internal.policy.DecorView$ActionModeCallback2Wrapper.onActionItemClicked(DecorView.java:2276)
       at android.support.v7.view.SupportActionModeWrapper$CallbackWrapper.onActionItemClicked(SupportActionModeWrapper.java:173)
       at android.support.v7.app.AppCompatDelegateImplV9$ActionModeCallbackWrapperV9.onActionItemClicked(AppCompatDelegateImplV9.java:1801)
       at android.support.v7.view.StandaloneActionMode.onMenuItemSelected(StandaloneActionMode.java:140)
       at android.support.v7.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:822)
       at android.support.v7.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:156)
       at android.support.v7.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:969)
       at android.support.v7.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:959)
       at android.support.v7.widget.ActionMenuView.invokeItem(ActionMenuView.java:623)
       at android.support.v7.view.menu.ActionMenuItemView.onClick(ActionMenuItemView.java:154)
       at android.view.View.performClick(View.java:5612)
       at android.view.View$PerformClick.run(View.java:22288)
       at android.os.Handler.handleCallback(Handler.java:751)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6123)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757)
```

**Comment by daniele-athome** [comment]
Unable to reproduce.
