### ISSUE TITLE
Permission denied from direct share service

### ISSUE THREAD

**Issue by daniele-athome** [kontalk/androidclient#1050]
Reported via devteam email.

```
Caught a RuntimeException from the binder stub implementation.
  java.lang.SecurityException: Permission Denial: reading org.kontalk.provider.MessagesProvider uri content://org.kontalk.messages/threads?limit=5 from pid=0, uid=1000 requires the provider be exported, or grantUriPermission()
  at android.content.ContentProvider.enforceReadPermissionInner(ContentProvider.java:605)
  at android.content.ContentProvider$Transport.enforceReadPermission(ContentProvider.java:480)
  at android.content.ContentProvider$Transport.query(ContentProvider.java:211)
  at android.content.ContentResolver.query(ContentResolver.java:493)
  at android.content.ContentResolver.query(ContentResolver.java:435)
  at org.kontalk.provider.MessagesProviderUtils.getLatestThreads(MessagesProviderUtils.java:71)
  at org.kontalk.service.DirectShareTargetService.onGetChooserTargets(DirectShareTargetService.java:69)
  at android.service.chooser.ChooserTargetService$IChooserTargetServiceWrapper.getChooserTargets(ChooserTargetService.java:147)
```

**Comment by daniele-athome** [comment]
https://stackoverflow.com/a/38152022/1045199
