### ISSUE TITLE
Crash in location preview

### ISSUE THREAD

**Issue by 115ek** [kontalk/androidclient#1063]
### Expected behavior
Dialog for choosing app to open should appear.

### Actual behavior
Kontalk crashes. IllegalArgumentException: Log tag "PositionAbstractFragment" exceeds limit of 23 characters. It seems that something with your logging is broken.

### Steps to reproduce
1. no google services (especially Gmaps) installed
2. no other map services (like Osmand)
3. click on a shared location
4. click navigate button (or button in right upper corner --> screenshot)
5. Kontalk crashes

![screenshot](https://user-images.githubusercontent.com/11771774/30128719-f4e35850-9343-11e7-8f04-4c7aeeee6de7.png)

### Environment

Kontalk version: cb60ee3045f725c1fbcd7882ea178fda12a23cc9 (f-droid version)

Android version: 7.1.2 (Lineage 14.1)

Device model: Xperia Pro, Samsung S III Mini

### Logs

```
09-06 20:26:57.071 19552 19552 W System.err: 6 [main] INFO org.osmdroid.views.MapView - Using tile source: org.osmdroid.tileprovider.tilesource.XYTileSource@53d459b
09-06 20:26:57.086 19552 19552 W System.err: 21 [main] INFO org.osmdroid.tileprovider.modules.MapTileFileStorageProviderBase - sdcard state: mounted
09-06 20:26:57.104 19552 19552 W System.err: 39 [main] INFO org.osmdroid.tileprovider.modules.MapTileFileStorageProviderBase - sdcard state: mounted
09-06 20:26:57.121 19552 19552 W System.err: 56 [main] INFO org.osmdroid.tileprovider.modules.MapTileFileStorageProviderBase - sdcard state: mounted
09-06 20:26:57.542 19552 19552 W System.err: 477 [main] INFO org.osmdroid.tileprovider.MapTileProviderBase - rescale tile cache from 0 to 12
09-06 20:26:57.557 19552 19552 W System.err: 489 [main] INFO org.osmdroid.tileprovider.MapTileProviderBase - Finished rescale in 12ms
09-06 20:26:57.587 19552 19552 W System.err: 522 [main] INFO org.osmdroid.tileprovider.LRUMapTileCache - Tile cache increased from 9 to 15
09-06 20:26:57.849 19552 19565 W art     : Suspending all threads took: 9.857ms
09-06 20:26:57.959 19552 19565 I art     : Background sticky concurrent mark sweep GC freed 30801(1751KB) AllocSpace objects, 14(992KB) LOS objects, 0% free, 18MB/18MB, paused 20.965ms total 361.907ms
09-06 20:26:58.184 19552 19565 I art     : Background partial concurrent mark sweep GC freed 33272(1633KB) AllocSpace objects, 16(296KB) LOS objects, 40% free, 16MB/26MB, paused 8.728ms total 213.287ms
09-06 20:26:59.371 19552 19552 D AndroidRuntime: Shutting down VM
09-06 20:26:59.378 19552 19552 E AndroidRuntime: FATAL EXCEPTION: main
09-06 20:26:59.378 19552 19552 E AndroidRuntime: Process: org.kontalk, PID: 19552
09-06 20:26:59.378 19552 19552 E AndroidRuntime: java.lang.IllegalArgumentException: Log tag "PositionAbstractFragment" exceeds limit of 23 characters
09-06 20:26:59.378 19552 19552 E AndroidRuntime: 
09-06 20:26:59.378 19552 19552 E AndroidRuntime: 	at android.util.Log.isLoggable(Native Method)
09-06 20:26:59.378 19552 19552 E AndroidRuntime: 	at org.kontalk.Log.e(Log.java:321)
09-06 20:26:59.378 19552 19552 E AndroidRuntime: 	at org.kontalk.position.PositionAbstractFragment.onOptionsItemSelected(PositionAbstractFragment.java:228)
09-06 20:26:59.378 19552 19552 E AndroidRuntime: 	at android.support.v4.app.Fragment.performOptionsItemSelected(Fragment.java:2317)
09-06 20:26:59.378 19552 19552 E AndroidRuntime: 	at android.support.v4.app.FragmentManagerImpl.dispatchOptionsItemSelected(FragmentManager.java:3056)
09-06 20:26:59.378 19552 19552 E AndroidRuntime: 	at android.support.v4.app.FragmentController.dispatchOptionsItemSelected(FragmentController.java:353)
09-06 20:26:59.378 19552 19552 E AndroidRuntime: 	at android.support.v4.app.FragmentActivity.onMenuItemSelected(FragmentActivity.java:414)
09-06 20:26:59.378 19552 19552 E AndroidRuntime: 	at android.support.v7.app.AppCompatActivity.onMenuItemSelected(AppCompatActivity.java:195)
09-06 20:26:59.378 19552 19552 E AndroidRuntime: 	at android.support.v7.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:113)
09-06 20:26:59.378 19552 19552 E AndroidRuntime: 	at android.support.v7.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:113)
09-06 20:26:59.378 19552 19552 E AndroidRuntime: 	at android.support.v7.app.ToolbarActionBar$2.onMenuItemClick(ToolbarActionBar.java:69)
09-06 20:26:59.378 19552 19552 E AndroidRuntime: 	at android.support.v7.widget.Toolbar$1.onMenuItemClick(Toolbar.java:206)
09-06 20:26:59.378 19552 19552 E AndroidRuntime: 	at android.support.v7.widget.ActionMenuView$MenuBuilderCallback.onMenuItemSelected(ActionMenuView.java:776)
09-06 20:26:59.378 19552 19552 E AndroidRuntime: 	at android.support.v7.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:822)
09-06 20:26:59.378 19552 19552 E AndroidRuntime: 	at android.support.v7.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:156)
09-06 20:26:59.378 19552 19552 E AndroidRuntime: 	at android.support.v7.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:969)
09-06 20:26:59.378 19552 19552 E AndroidRuntime: 	at android.support.v7.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:959)
09-06 20:26:59.378 19552 19552 E AndroidRuntime: 	at android.support.v7.widget.ActionMenuView.invokeItem(ActionMenuView.java:623)
09-06 20:26:59.378 19552 19552 E AndroidRuntime: 	at android.support.v7.view.menu.ActionMenuItemView.onClick(ActionMenuItemView.java:154)
09-06 20:26:59.378 19552 19552 E AndroidRuntime: 	at android.view.View.performClick(View.java:5637)
09-06 20:26:59.378 19552 19552 E AndroidRuntime: 	at android.view.View$PerformClick.run(View.java:22433)
09-06 20:26:59.378 19552 19552 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:751)
09-06 20:26:59.378 19552 19552 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:95)
09-06 20:26:59.378 19552 19552 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:154)
09-06 20:26:59.378 19552 19552 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6186)
09-06 20:26:59.378 19552 19552 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
09-06 20:26:59.378 19552 19552 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
09-06 20:26:59.378 19552 19552 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
```

### Other

- Problem doesn't appear if debug logging is enabled. (just tried that to grab an additional log, but Kontalk didn't crashed anymore...).
- Problem doesn't appear with Gapps (incl. GMaps) installed.
- In addition it should be possible to open the geolocation link in a browser.

**Comment by daniele-athome** [comment]
Thanks for reporting. It seems that also Android API level > 24 has the log tag limit set to 23 characters, [despite what the documentation states](https://developer.android.com/reference/android/util/Log.html#isLoggable(java.lang.String,%20int)) (unless I misunderstood it, unless it's a Lineage specific issue). I guess always limiting the tag to 23 characters isn't a big deal anyway.
