### ISSUE TITLE
Race condition crash for null group object

### ISSUE THREAD

**Issue by daniele-athome** [kontalk/androidclient#1076]
Unbelievable.

```
java.lang.RuntimeException: Unable to start service org.kontalk.service.msgcenter.MessageCenterService@12d01dc with Intent { act=org.kontalk.action.MESSAGE cmp=org.kontalk/.service.msgcenter.MessageCenterService (has extras) }: java.lang.NullPointerException: Attempt to invoke virtual method 'void org.kontalk.client.KontalkGroupManager$KontalkGroup.groupInfo(org.jivesoftware.smack.packet.Stanza)' on a null object reference
       at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3048)
       at android.app.ActivityThread.-wrap17(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1455)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:5459)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)
Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'void org.kontalk.client.KontalkGroupManager$KontalkGroup.groupInfo(org.jivesoftware.smack.packet.Stanza)' on a null object reference
       at org.kontalk.service.msgcenter.group.KontalkGroupController.beforeEncryption(KontalkGroupController.java:98)
       at org.kontalk.service.msgcenter.group.KontalkGroupController.beforeEncryption(KontalkGroupController.java:43)
       at org.kontalk.service.msgcenter.MessageCenterService.sendMessage(MessageCenterService.java:2451)
       at org.kontalk.service.msgcenter.MessageCenterService.handleMessage(MessageCenterService.java:1144)
       at org.kontalk.service.msgcenter.MessageCenterService.handleIntent(MessageCenterService.java:920)
       at org.kontalk.service.msgcenter.MessageCenterService.onStartCommand(MessageCenterService.java:725)
       at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3031)
       at android.app.ActivityThread.-wrap17(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1455)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:5459)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)
```

**Comment by daniele-athome** [comment]
Fixed in kontalk/client-common-java@cfe45b07c5809ce6aa0c05774bbee6b11468d7fe
