### ISSUE TITLE
Crash when resuming chat for sending media

### ISSUE THREAD

**Issue by daniele-athome** [kontalk/androidclient#1085]
Another weird issue. Detected on a Samsung Galaxy S2 9.7 running Android 7.0 with Kontalk 4.0.4 (but the issue occurs in latest version too).

```
Unable to resume activity {org.kontalk/org.kontalk.ui.ConversationsActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void org.kontalk.ui.AbstractComposeFragment.setTextEntry(java.lang.CharSequence)' on a null object reference
       at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3841)
       at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3882)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3048)
       at android.app.ActivityThread.-wrap14(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1639)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6780)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1496)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1386)
Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'void org.kontalk.ui.AbstractComposeFragment.setTextEntry(java.lang.CharSequence)' on a null object reference
       at org.kontalk.ui.SendIntentReceiver.processSendIntent(SendIntentReceiver.java:74)
       at org.kontalk.ui.ConversationsActivity.processSendIntent(ConversationsActivity.java:161)
       at org.kontalk.ui.ConversationsActivity.onResumeFragments(ConversationsActivity.java:240)
       at android.support.v4.app.FragmentActivity.onPostResume(FragmentActivity.java:498)
       at android.support.v7.app.AppCompatActivity.onPostResume(AppCompatActivity.java:172)
       at android.app.Activity.performResume(Activity.java:7118)
       at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3818)
       at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3882)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3048)
       at android.app.ActivityThread.-wrap14(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1639)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6780)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1496)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1386)
```

**Comment by daniele-athome** [comment]
Unable to reproduce.

**Comment by daniele-athome** [comment]
Reopening after an Amazon Fire 8 tablet reported this again:

```
Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'void org.kontalk.ui.AbstractComposeFragment.setTextEntry(java.lang.CharSequence)' on a null object reference
       at org.kontalk.ui.SendIntentReceiver.processSendIntent + 74(SendIntentReceiver.java:74)
       at org.kontalk.ui.ConversationsActivity.processSendIntent + 161(ConversationsActivity.java:161)
       at org.kontalk.ui.ConversationsActivity.onResumeFragments + 241(ConversationsActivity.java:241)
       at android.support.v4.app.FragmentActivity.onPostResume + 527(FragmentActivity.java:527)
       at android.support.v7.app.AppCompatActivity.onPostResume + 172(AppCompatActivity.java:172)
       at android.app.Activity.performResume + 6844(Activity.java:6844)
       at android.app.ActivityThread.performResumeActivity + 3428(ActivityThread.java:3428)
       at android.app.ActivityThread.handleResumeActivity + 3502(ActivityThread.java:3502)
       at android.app.ActivityThread.handleLaunchActivity + 2754(ActivityThread.java:2754)
       at android.app.ActivityThread.-wrap12(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage + 1488(ActivityThread.java:1488)
       at android.os.Handler.dispatchMessage + 102(Handler.java:102)
       at android.os.Looper.loop + 154(Looper.java:154)
       at android.app.ActivityThread.main + 6188(ActivityThread.java:6188)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run + 911(ZygoteInit.java:911)
       at com.android.internal.os.ZygoteInit.main + 801(ZygoteInit.java:801)
```
