### ISSUE TITLE
Error exporting private key

### ISSUE THREAD

**Issue by frakbe** [kontalk/androidclient#1111]
### Expected behavior
Menu -> maintenance -> Export private key -> export private key on a zipped file

### Actual behavior
Error in export. The procedure creates an empty (0kb) file.

### Steps to reproduce
1. Go to maintenance
2. Select Export private key
3. Select a destination directory
4. The error appears

### Environment

Kontalk version: From F-Droid 4.1.1 (2.7.0)

Android version: LineageOS 14.1 Android 7.1.2

Device model: Xiaomi Redmi 3

### Logs
(enabling debug mode)
2017-12-04 14:11:37 E/Kontalk: error exporting keys
2017-12-04 14:11:37 E/Kontalk: org.spongycastle.openpgp.PGPException: checksum mismatch at 0 of 20
	at org.spongycastle.openpgp.PGPSecretKey.extractKeyData(PGPSecretKey.java:400)
	at org.spongycastle.openpgp.PGPSecretKey.copyWithNewPassword(PGPSecretKey.java:667)
	at org.spongycastle.openpgp.PGPSecretKeyRing.copyWithNewPassword(PGPSecretKeyRing.java:403)
	at org.kontalk.crypto.PGP.copySecretKeyRingWithNewPassword(PGP.java:679)
	at org.kontalk.crypto.PGP.copySecretKeyRingWithNewPassword(PGP.java:664)
	at org.kontalk.crypto.PersonalKeyExporter.save(PersonalKeyExporter.java:60)
	at org.kontalk.authenticator.Authenticator.exportDefaultPersonalKey(Authenticator.java:212)
	at org.kontalk.Kontalk.exportPersonalKey(Kontalk.java:274)
	at org.kontalk.ui.prefs.MaintenanceFragment.exportPersonalKey(MaintenanceFragment.java:439)
	at org.kontalk.ui.prefs.MaintenanceFragment.onActivityResult(MaintenanceFragment.java:467)
	at android.support.v4.app.FragmentActivity.onActivityResult(FragmentActivity.java:151)
	at android.app.Activity.dispatchActivityResult(Activity.java:6937)
	at android.app.ActivityThread.deliverResults(ActivityThread.java:4122)
	at android.app.ActivityThread.handleSendResult(ActivityThread.java:4169)
	at android.app.ActivityThread.-wrap20(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1552)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6186)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)

### Other

Thank you

**Comment by daniele-athome** [comment]
> Damn Bouncy Castle!!!

Thanks for reporting.

**Comment by daniele-athome** [comment]
Note to myself: investigate encoding issues in the passphrase - or it might be just a passphrase handling bug in the app...

**Comment by frakbe** [comment]
About your note: I've read on a previous bug about handling "complex" password, so I tried also with a simple, only character-based password. The problem remains.

**Comment by abadroot** [comment]
Same issue for me

Environment

Kontalk version: From Play Store 4.1.1

Android version: 7.0 NRD90M.G930FXXU1DQJ1

Device model: Samsung Galaxy S7 SM-G930F

Logs

2017-12-04 22:31:45 E/Kontalk: error exporting keys
2017-12-04 22:31:45 E/Kontalk: org.spongycastle.openpgp.PGPException: checksum mismatch at 0 of 20
	at org.spongycastle.openpgp.PGPSecretKey.extractKeyData(PGPSecretKey.java:400)
	at org.spongycastle.openpgp.PGPSecretKey.copyWithNewPassword(PGPSecretKey.java:667)
	at org.spongycastle.openpgp.PGPSecretKeyRing.copyWithNewPassword(PGPSecretKeyRing.java:403)
	at org.kontalk.crypto.PGP.copySecretKeyRingWithNewPassword(PGP.java:679)
	at org.kontalk.crypto.PGP.copySecretKeyRingWithNewPassword(PGP.java:664)
	at org.kontalk.crypto.PersonalKeyExporter.save(PersonalKeyExporter.java:60)
	at org.kontalk.authenticator.Authenticator.exportDefaultPersonalKey(Authenticator.java:212)
	at org.kontalk.Kontalk.exportPersonalKey(Kontalk.java:274)
	at org.kontalk.ui.prefs.MaintenanceFragment.exportPersonalKey(MaintenanceFragment.java:439)
	at org.kontalk.ui.prefs.MaintenanceFragment.onActivityResult(MaintenanceFragment.java:467)
	at android.support.v4.app.FragmentActivity.onActivityResult(FragmentActivity.java:151)
	at android.app.Activity.dispatchActivityResult(Activity.java:7226)
	at android.app.ActivityThread.deliverResults(ActivityThread.java:4477)
	at android.app.ActivityThread.handleSendResult(ActivityThread.java:4524)
	at android.app.ActivityThread.-wrap22(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1691)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6692)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1468)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1358)

**Comment by daniele-athome** [comment]
I'll release a hotfix based on the current master with a workaround. You'll also get [contextual reply](#594) which I was preparing for a next version along with another couple of new features :-)

**Comment by gnikwo** [comment]
same issue for me 

Kontalk version: From F-Droid, 4.1.2

Android version: Resurrection Remix Nougat android-7.1.2_r36

Device model: Huawei P10 lite 2017 - WAS-LX1A

2018-01-05 14:45:28 E/Kontalk: error exporting keys
2018-01-05 14:45:28 E/Kontalk: org.spongycastle.openpgp.PGPException: checksum mismatch at 0 of 20
	at org.spongycastle.openpgp.PGPSecretKey.extractKeyData(PGPSecretKey.java:400)
	at org.spongycastle.openpgp.PGPSecretKey.copyWithNewPassword(PGPSecretKey.java:667)
	at org.spongycastle.openpgp.PGPSecretKeyRing.copyWithNewPassword(PGPSecretKeyRing.java:403)
	at org.kontalk.crypto.PGP.copySecretKeyRingWithNewPassword(PGP.java:679)
	at org.kontalk.crypto.PGP.copySecretKeyRingWithNewPassword(PGP.java:664)
	at org.kontalk.crypto.PersonalKeyExporter.save(PersonalKeyExporter.java:60)
	at org.kontalk.authenticator.Authenticator.exportDefaultPersonalKey(Authenticator.java:212)
	at org.kontalk.Kontalk.exportPersonalKey(Kontalk.java:274)
	at org.kontalk.ui.prefs.MaintenanceFragment.exportPersonalKey(MaintenanceFragment.java:467)
	at org.kontalk.ui.prefs.MaintenanceFragment.onActivityResult(MaintenanceFragment.java:495)
	at android.support.v4.app.FragmentActivity.onActivityResult(FragmentActivity.java:151)
	at android.app.Activity.dispatchActivityResult(Activity.java:6937)
	at android.app.ActivityThread.deliverResults(ActivityThread.java:4137)
	at android.app.ActivityThread.handleSendResult(ActivityThread.java:4184)
	at android.app.ActivityThread.-wrap20(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1563)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6236)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:891)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:781)

**Comment by webratte** [comment]
Hi @gnikwo,
AFAIK it's fixed in: https://github.com/kontalk/androidclient/commit/30757ce3f8cc5bc7793da23c5ffb6b3ee676c8b0
and it only wait's for release ;-)
