### ISSUE TITLE
Cannot export keys from Kontalk Android

### ISSUE THREAD

**Issue by andreasspeck** [kontalk/androidclient#1139]
### Expected behavior
When going to Configuration->Maintenance->Export private key, entering the correct password and choosing a location the keys should exported to a zip file.

### Actual behavior
After choosing a location (to which Kontalk has write permissions, as this happens even if I choose the location where Kontalk saves downloaded images), the zip file gets created, but it is empty (of zero length). An error message appears "Cannot export private keys" (my Kontalk shows messages in Spanish, so the English one might not be correct).

### Steps to reproduce
As above.

### Environment

Kontalk version: (please also specify origin, e.g. F-Droid or Google Play)
4.1.2 from F-Droid

Android version: (please also specify custom ROM name if applicable)
LineageOS 14.1 

Device model: BQ Aquaris M5 "piccolo"

### Logs
2018-01-20 18:30:49 D/MessageCenterService: entering inactive state
2018-01-20 18:31:26 E/Kontalk: error exporting keys
2018-01-20 18:31:26 E/Kontalk: org.spongycastle.openpgp.PGPException: checksum mismatch at 0 of 20
	at org.spongycastle.openpgp.PGPSecretKey.extractKeyData(PGPSecretKey.java:400)
	at org.spongycastle.openpgp.PGPSecretKey.copyWithNewPassword(PGPSecretKey.java:667)
	at org.spongycastle.openpgp.PGPSecretKeyRing.copyWithNewPassword(PGPSecretKeyRing.java:403)
	at org.kontalk.crypto.PGP.copySecretKeyRingWithNewPassword(PGP.java:679)
	at org.kontalk.crypto.PGP.copySecretKeyRingWithNewPassword(PGP.java:664)
	at org.kontalk.crypto.PersonalKeyExporter.save(PersonalKeyExporter.java:60)
	at org.kontalk.authenticator.Authenticator.exportDefaultPersonalKey(Authenticator.java:212)
	at org.kontalk.Kontalk.exportPersonalKey(Kontalk.java:274)
	at org.kontalk.ui.prefs.MaintenanceFragment.exportPersonalKey(MaintenanceFragment.java:467)
	at org.kontalk.ui.prefs.MaintenanceFragment.onActivityResult(MaintenanceFragment.java:495)
	at android.support.v4.app.FragmentActivity.onActivityResult(FragmentActivity.java:151)
	at android.app.Activity.dispatchActivityResult(Activity.java:6937)
	at android.app.ActivityThread.deliverResults(ActivityThread.java:4122)
	at android.app.ActivityThread.handleSendResult(ActivityThread.java:4169)
	at android.app.ActivityThread.-wrap20(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1552)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6186)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)

**Comment by webratte** [comment]
This issue should be fixed in Version 4.1.3

If it's not available yet in F-droid you only have to wait. F-droid needs most a bit more time then Google Play.

**Comment by andreasspeck** [comment]
I can confirm this is now fixed. Thanks.
