### ISSUE TITLE
can't connect when in free wifi

### ISSUE THREAD

**Issue by 115ek** [kontalk/androidclient#1148]
### Expected behavior
Kontalk should connect to the server and be able to send and receive messages

### Actual behavior
Kontalk can't establish a connection

### Steps to reproduce
1. happens in a train where free wifi is provided
2. restarting message center doesn't help
3. after changing to a mobile data connection Kontalk connects immediately (network state changed!)

### Environment

Kontalk version: 4.1.3 no google

Android version: LineageOS 14.1 

Device model: Z1 compact

### Logs

```2018-01-22 06:35:26 D/MessageCenterService: Message Center starting - Intent { act=org.kontalk.action.HOLD cmp=org.kontalk/.service.msgcenter.MessageCenterService (has extras) }
2018-01-22 06:35:34 D/MessageCenterService: Message Center starting - Intent { act=org.kontalk.action.RELEASE cmp=org.kontalk/.service.msgcenter.MessageCenterService }
2018-01-22 06:35:34 D/MessageCenterService: destroying message center
2018-01-22 06:35:54 W/Kontalk: network state changed!
2018-01-22 06:35:54 D/MessageCenterService: testing message center connection
2018-01-22 06:35:54 D/MessageCenterService: Message Center starting - Intent { act=org.kontalk.action.TEST cmp=org.kontalk/.service.msgcenter.MessageCenterService }
2018-01-22 06:35:54 D/MessageCenterService: using server beta.kontalk.net
2018-01-22 06:35:54 V/MessageCenterService: connection created.
2018-01-22 06:35:54 E/MessageCenterService: connection error
2018-01-22 06:35:54 E/MessageCenterService: org.jivesoftware.smack.SmackException$ConnectionException: The following addresses failed: '_xmpp-client._tcp.beta.kontalk.net:5222' failed because: de.measite.minidns.hla.ResolutionUnsuccessfulException: Asking for _xmpp-client._tcp.beta.kontalk.net.	IN	SRV yielded an error response NX_DOMAIN, 'beta.kontalk.net:5222' failed because: de.measite.minidns.hla.ResolutionUnsuccessfulException: Asking for beta.kontalk.net.	IN	A yielded an error response NX_DOMAIN, 'beta.kontalk.net:5222' failed because: de.measite.minidns.hla.ResolutionUnsuccessfulException: Asking for beta.kontalk.net.	IN	AAAA yielded an error response NX_DOMAIN
	at org.kontalk.client.XMPPTCPConnection.connectUsingConfiguration(XMPPTCPConnection.java:619)
	at org.kontalk.client.XMPPTCPConnection.connectInternal(XMPPTCPConnection.java:902)
	at org.jivesoftware.smack.AbstractXMPPConnection.connect(AbstractXMPPConnection.java:380)
	at org.kontalk.service.XMPPConnectionHelper.connectOnce(XMPPConnectionHelper.java:202)
	at org.kontalk.service.XMPPConnectionHelper.connect(XMPPConnectionHelper.java:261)
	at org.kontalk.service.XMPPConnectionHelper.run(XMPPConnectionHelper.java:144)

2018-01-22 06:35:54 D/MessageCenterService: retrying in 3 seconds (retry=1)
2018-01-22 06:35:57 D/MessageCenterService: using server beta.kontalk.net
2018-01-22 06:35:58 E/MessageCenterService: connection error
2018-01-22 06:35:58 E/MessageCenterService: org.jivesoftware.smack.SmackException$ConnectionException: The following addresses failed: '_xmpp-client._tcp.beta.kontalk.net:5222' failed because: de.measite.minidns.hla.ResolutionUnsuccessfulException: Asking for _xmpp-client._tcp.beta.kontalk.net.	IN	SRV yielded an error response NX_DOMAIN, 'beta.kontalk.net:5222' failed because: de.measite.minidns.hla.ResolutionUnsuccessfulException: Asking for beta.kontalk.net.	IN	A yielded an error response NX_DOMAIN, 'beta.kontalk.net:5222' failed because: de.measite.minidns.hla.ResolutionUnsuccessfulException: Asking for beta.kontalk.net.	IN	AAAA yielded an error response NX_DOMAIN
	at org.kontalk.client.XMPPTCPConnection.connectUsingConfiguration(XMPPTCPConnection.java:619)
	at org.kontalk.client.XMPPTCPConnection.connectInternal(XMPPTCPConnection.java:902)
	at org.jivesoftware.smack.AbstractXMPPConnection.connect(AbstractXMPPConnection.java:380)
	at org.kontalk.service.XMPPConnectionHelper.connectOnce(XMPPConnectionHelper.java:202)
	at org.kontalk.service.XMPPConnectionHelper.connect(XMPPConnectionHelper.java:261)
	at org.kontalk.service.XMPPConnectionHelper.run(XMPPConnectionHelper.java:144)

2018-01-22 06:35:58 D/MessageCenterService: retrying in 9 seconds (retry=2)
2018-01-22 06:36:07 D/MessageCenterService: using server beta.kontalk.net
2018-01-22 06:36:07 E/MessageCenterService: connection error
2018-01-22 06:36:07 E/MessageCenterService: org.jivesoftware.smack.SmackException$ConnectionException: The following addresses failed: '_xmpp-client._tcp.beta.kontalk.net:5222' failed because: de.measite.minidns.hla.ResolutionUnsuccessfulException: Asking for _xmpp-client._tcp.beta.kontalk.net.	IN	SRV yielded an error response NX_DOMAIN, 'beta.kontalk.net:5222' failed because: de.measite.minidns.hla.ResolutionUnsuccessfulException: Asking for beta.kontalk.net.	IN	A yielded an error response NX_DOMAIN, 'beta.kontalk.net:5222' failed because: de.measite.minidns.hla.ResolutionUnsuccessfulException: Asking for beta.kontalk.net.	IN	AAAA yielded an error response NX_DOMAIN
	at org.kontalk.client.XMPPTCPConnection.connectUsingConfiguration(XMPPTCPConnection.java:619)
	at org.kontalk.client.XMPPTCPConnection.connectInternal(XMPPTCPConnection.java:902)
	at org.jivesoftware.smack.AbstractXMPPConnection.connect(AbstractXMPPConnection.java:380)
	at org.kontalk.service.XMPPConnectionHelper.connectOnce(XMPPConnectionHelper.java:202)
	at org.kontalk.service.XMPPConnectionHelper.connect(XMPPConnectionHelper.java:261)
	at org.kontalk.service.XMPPConnectionHelper.run(XMPPConnectionHelper.java:144)

2018-01-22 06:36:07 D/MessageCenterService: retrying in 19 seconds (retry=3)
2018-01-22 06:36:08 D/MessageCenterService: Message Center starting - Intent { act=org.kontalk.action.HOLD cmp=org.kontalk/.service.msgcenter.MessageCenterService (has extras) }
2018-01-22 06:36:10 D/MessageCenterService: Message Center starting - Intent { act=org.kontalk.action.RELEASE cmp=org.kontalk/.service.msgcenter.MessageCenterService }
2018-01-22 06:36:10 D/MessageCenterService: Message Center starting - Intent { act=org.kontalk.action.CONNECTED cmp=org.kontalk/.service.msgcenter.MessageCenterService }
2018-01-22 06:36:10 D/MessageCenterService: Message Center starting - Intent { act=org.kontalk.action.ROSTER_LOADED cmp=org.kontalk/.service.msgcenter.MessageCenterService }
2018-01-22 06:36:10 D/MessageCenterService: Message Center starting - Intent { act=org.kontalk.action.HOLD cmp=org.kontalk/.service.msgcenter.MessageCenterService (has extras) }
2018-01-22 06:36:14 D/MessageCenterService: Message Center starting - Intent { act=org.kontalk.action.MESSAGE cmp=org.kontalk/.service.msgcenter.MessageCenterService (has extras) }
2018-01-22 06:36:17 D/MessageCenterService: Message Center starting - Intent { act=org.kontalk.action.MESSAGE cmp=org.kontalk/.service.msgcenter.MessageCenterService (has extras) }
2018-01-22 06:36:20 D/MessageCenterService: Message Center starting - Intent { act=org.kontalk.action.RELEASE cmp=org.kontalk/.service.msgcenter.MessageCenterService }
2018-01-22 06:36:20 D/MessageCenterService: Message Center starting - Intent { act=org.kontalk.action.HOLD cmp=org.kontalk/.service.msgcenter.MessageCenterService (has extras) }
2018-01-22 06:36:23 D/MessageCenterService: Message Center starting - Intent { act=org.kontalk.action.RELEASE cmp=org.kontalk/.service.msgcenter.MessageCenterService }
2018-01-22 06:36:26 D/MessageCenterService: using server beta.kontalk.net
2018-01-22 06:36:27 E/MessageCenterService: connection error
2018-01-22 06:36:27 E/MessageCenterService: org.jivesoftware.smack.SmackException$ConnectionException: The following addresses failed: '_xmpp-client._tcp.beta.kontalk.net:5222' failed because: de.measite.minidns.hla.ResolutionUnsuccessfulException: Asking for _xmpp-client._tcp.beta.kontalk.net.	IN	SRV yielded an error response NX_DOMAIN, 'beta.kontalk.net:5222' failed because: de.measite.minidns.hla.ResolutionUnsuccessfulException: Asking for beta.kontalk.net.	IN	A yielded an error response NX_DOMAIN, 'beta.kontalk.net:5222' failed because: de.measite.minidns.hla.ResolutionUnsuccessfulException: Asking for beta.kontalk.net.	IN	AAAA yielded an error response NX_DOMAIN
	at org.kontalk.client.XMPPTCPConnection.connectUsingConfiguration(XMPPTCPConnection.java:619)
	at org.kontalk.client.XMPPTCPConnection.connectInternal(XMPPTCPConnection.java:902)
	at org.jivesoftware.smack.AbstractXMPPConnection.connect(AbstractXMPPConnection.java:380)
	at org.kontalk.service.XMPPConnectionHelper.connectOnce(XMPPConnectionHelper.java:202)
	at org.kontalk.service.XMPPConnectionHelper.connect(XMPPConnectionHelper.java:261)
	at org.kontalk.service.XMPPConnectionHelper.run(XMPPConnectionHelper.java:144)

2018-01-22 06:36:27 D/MessageCenterService: retrying in 28 seconds (retry=4)
2018-01-22 06:36:28 W/Kontalk: manual message center restart requested
2018-01-22 06:36:28 D/MessageCenterService: restarting message center
2018-01-22 06:36:28 D/MessageCenterService: Message Center starting - Intent { act=org.kontalk.action.RESTART cmp=org.kontalk/.service.msgcenter.MessageCenterService }
2018-01-22 06:36:28 E/MessageCenterService: - interrupted.
2018-01-22 06:36:28 D/MessageCenterService: using server beta.kontalk.net
2018-01-22 06:36:28 E/MessageCenterService: connection error
2018-01-22 06:36:28 E/MessageCenterService: org.jivesoftware.smack.SmackException$ConnectionException: The following addresses failed: '_xmpp-client._tcp.beta.kontalk.net:5222' failed because: de.measite.minidns.hla.ResolutionUnsuccessfulException: Asking for _xmpp-client._tcp.beta.kontalk.net.	IN	SRV yielded an error response NX_DOMAIN, 'beta.kontalk.net:5222' failed because: de.measite.minidns.hla.ResolutionUnsuccessfulException: Asking for beta.kontalk.net.	IN	A yielded an error response NX_DOMAIN, 'beta.kontalk.net:5222' failed because: de.measite.minidns.hla.ResolutionUnsuccessfulException: Asking for beta.kontalk.net.	IN	AAAA yielded an error response NX_DOMAIN
	at org.kontalk.client.XMPPTCPConnection.connectUsingConfiguration(XMPPTCPConnection.java:619)
	at org.kontalk.client.XMPPTCPConnection.connectInternal(XMPPTCPConnection.java:902)
	at org.jivesoftware.smack.AbstractXMPPConnection.connect(AbstractXMPPConnection.java:380)
	at org.kontalk.service.XMPPConnectionHelper.connectOnce(XMPPConnectionHelper.java:202)
	at org.kontalk.service.XMPPConnectionHelper.connect(XMPPConnectionHelper.java:261)
	at org.kontalk.service.XMPPConnectionHelper.run(XMPPConnectionHelper.java:144)

2018-01-22 06:36:28 D/MessageCenterService: retrying in 5 seconds (retry=1)
2018-01-22 06:36:30 D/MessageCenterService: Message Center starting - Intent { act=org.kontalk.action.HOLD cmp=org.kontalk/.service.msgcenter.MessageCenterService (has extras) }
2018-01-22 06:36:31 D/MessageCenterService: Message Center starting - Intent { act=org.kontalk.action.RELEASE cmp=org.kontalk/.service.msgcenter.MessageCenterService }
2018-01-22 06:36:31 D/MessageCenterService: Message Center starting - Intent { act=org.kontalk.action.CONNECTED cmp=org.kontalk/.service.msgcenter.MessageCenterService }
2018-01-22 06:36:31 D/MessageCenterService: Message Center starting - Intent { act=org.kontalk.action.ROSTER_LOADED cmp=org.kontalk/.service.msgcenter.MessageCenterService }
2018-01-22 06:36:31 D/MessageCenterService: Message Center starting - Intent { act=org.kontalk.action.HOLD cmp=org.kontalk/.service.msgcenter.MessageCenterService (has extras) }
2018-01-22 06:36:33 D/MessageCenterService: Message Center starting - Intent { act=org.kontalk.action.RELEASE cmp=org.kontalk/.service.msgcenter.MessageCenterService }
2018-01-22 06:36:34 D/MessageCenterService: using server beta.kontalk.net
2018-01-22 06:36:34 E/MessageCenterService: connection error
2018-01-22 06:36:34 E/MessageCenterService: org.jivesoftware.smack.SmackException$ConnectionException: The following addresses failed: '_xmpp-client._tcp.beta.kontalk.net:5222' failed because: de.measite.minidns.hla.ResolutionUnsuccessfulException: Asking for _xmpp-client._tcp.beta.kontalk.net.	IN	SRV yielded an error response NX_DOMAIN, 'beta.kontalk.net:5222' failed because: de.measite.minidns.hla.ResolutionUnsuccessfulException: Asking for beta.kontalk.net.	IN	A yielded an error response NX_DOMAIN, 'beta.kontalk.net:5222' failed because: de.measite.minidns.hla.ResolutionUnsuccessfulException: Asking for beta.kontalk.net.	IN	AAAA yielded an error response NX_DOMAIN
	at org.kontalk.client.XMPPTCPConnection.connectUsingConfiguration(XMPPTCPConnection.java:619)
	at org.kontalk.client.XMPPTCPConnection.connectInternal(XMPPTCPConnection.java:902)
	at org.jivesoftware.smack.AbstractXMPPConnection.connect(AbstractXMPPConnection.java:380)
	at org.kontalk.service.XMPPConnectionHelper.connectOnce(XMPPConnectionHelper.java:202)
	at org.kontalk.service.XMPPConnectionHelper.connect(XMPPConnectionHelper.java:261)
	at org.kontalk.service.XMPPConnectionHelper.run(XMPPConnectionHelper.java:144)

2018-01-22 06:36:34 D/MessageCenterService: retrying in 9 seconds (retry=2)
2018-01-22 06:36:34 D/MessageCenterService: Message Center starting - Intent { act=org.kontalk.action.HOLD cmp=org.kontalk/.service.msgcenter.MessageCenterService (has extras) }
2018-01-22 06:36:34 D/MessageCenterService: Message Center starting - Intent { act=org.kontalk.action.CONNECTED cmp=org.kontalk/.service.msgcenter.MessageCenterService }
2018-01-22 06:36:34 D/MessageCenterService: Message Center starting - Intent { act=org.kontalk.action.ROSTER_LOADED cmp=org.kontalk/.service.msgcenter.MessageCenterService }
2018-01-22 06:36:42 D/MessageCenterService: shutting down message center
2018-01-22 06:36:42 D/MessageCenterService: destroying message center
2018-01-22 06:36:42 E/MessageCenterService: - interrupted.
2018-01-22 06:36:42 W/Kontalk: network state changed!
2018-01-22 06:36:42 D/MessageCenterService: testing message center connection
2018-01-22 06:36:43 D/MessageCenterService: Message Center starting - Intent { act=org.kontalk.action.TEST cmp=org.kontalk/.service.msgcenter.MessageCenterService }
2018-01-22 06:36:43 D/MessageCenterService: using server beta.kontalk.net
2018-01-22 06:36:43 V/MessageCenterService: connection created.
2018-01-22 06:36:43 D/SMACK: SENT (2): <stream:stream xmlns='jabber:client' to='beta.kontalk.net' xmlns:stream='http://etherx.jabber.org/streams' version='1.0' xml:lang='en'>
```
### Other

Signal is working without issues.
May it be a problem with packet filtering? I know that deep packet inspection allows you to censor things...
But that's a bit paranoid, isn't it?

**Comment by daniele-athome** [comment]
The system is working so it's a problem related to the free network you're using. Maybe it's not so free eheh sorry. 
Also remember that you need outgoing access to TCP port 5222 to connect, but in this case it's more of a DNS resolution problem.
