### ISSUE TITLE
Problems upgrading database

### ISSUE THREAD

**Issue by daniele-athome** [kontalk/androidclient#1168]
```
android.database.sqlite.SQLiteException: Can't upgrade read-only database from version 12 to 16: messages.db
       at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:244)
       at android.database.sqlite.SQLiteOpenHelper.getReadableDatabase(SQLiteOpenHelper.java:187)
       at org.kontalk.provider.MessagesProvider.query(MessagesProvider.java:590)
       at android.content.ContentProvider.query(ContentProvider.java:1028)
       at android.content.ContentProvider$Transport.query(ContentProvider.java:243)
       at android.content.ContentResolver.query(ContentResolver.java:536)
       at android.content.ContentResolver.query(ContentResolver.java:478)
       at org.kontalk.ui.MessagingNotification.updateMessagesNotification(MessagingNotification.java:267)
       at org.kontalk.ui.MessagingNotification$1.run(MessagingNotification.java:207)
       at java.lang.Thread.run(Thread.java:762)
```

**Comment by daniele-athome** [comment]
Unable to reproduce in any way.
