### ISSUE TITLE
Assent race condition with null contexts

### ISSUE THREAD

**Issue by daniele-athome** [kontalk/androidclient#1176]
Here we go starting with null contexts with Assent.

```
java.lang.IllegalStateException: You must set an Activity or Fragment to Assent.
       at com.afollestad.assent.Assent.invalidateContext(Assent.java:84)
       at com.afollestad.assent.Assent.isPermissionGranted(Assent.java:127)
       at org.kontalk.ui.view.ComposerBar.startRecording(ComposerBar.java:522)
       at org.kontalk.ui.view.ComposerBar$7.onTouch(ComposerBar.java:304)
       at android.view.View.dispatchTouchEvent(View.java:10713)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2865)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2492)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2865)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2492)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2865)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2492)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2865)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2492)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2865)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2492)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2865)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2492)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2865)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2492)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2865)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2492)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2865)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2492)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2865)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2492)
       at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:559)
       at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1870)
       at android.app.Activity.dispatchTouchEvent(Activity.java:3236)
       at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:68)
       at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:68)
       at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:521)
       at android.view.View.dispatchPointerEvent(View.java:10946)
       at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:5110)
       at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4962)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4493)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4546)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4512)
       at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4645)
       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4520)
       at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4702)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4493)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4546)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4512)
       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4520)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4493)
       at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:7000)
       at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:6929)
       at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6890)
       at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:7110)
       at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
       at android.os.MessageQueue.nativePollOnce(MessageQueue.java)
       at android.os.MessageQueue.next(MessageQueue.java:323)
       at android.os.Looper.loop(Looper.java:136)
       at android.app.ActivityThread.main(ActivityThread.java:6682)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)
```

**Comment by daniele-athome** [comment]
Switched to EasyPermissions.
