### ISSUE TITLE
Error in action mode: checked item count is not 1

### ISSUE THREAD

**Issue by daniele-athome** [kontalk/androidclient#1192]
Of course this shouldn't be possible, but it happens.

```
java.lang.IllegalStateException: checked items count must be exactly 1
       at org.kontalk.ui.AbstractComposeFragment.getCheckedItem(AbstractComposeFragment.java:604)
       at org.kontalk.ui.AbstractComposeFragment.onActionItemClicked(AbstractComposeFragment.java:527)
       at android.widget.AbsListView$MultiChoiceModeWrapper.onActionItemClicked(AbsListView.java:6440)
       at com.android.internal.policy.DecorView$ActionModeCallback2Wrapper.onActionItemClicked(DecorView.java:2276)
       at android.support.v7.view.SupportActionModeWrapper$CallbackWrapper.onActionItemClicked(SupportActionModeWrapper.java:170)
       at android.support.v7.app.AppCompatDelegateImplV9$ActionModeCallbackWrapperV9.onActionItemClicked(AppCompatDelegateImplV9.java:1810)
       at android.support.v7.view.StandaloneActionMode.onMenuItemSelected(StandaloneActionMode.java:140)
       at android.support.v7.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:822)
       at android.support.v7.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:171)
       at android.support.v7.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:973)
       at android.support.v7.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:963)
       at android.support.v7.widget.ActionMenuView.invokeItem(ActionMenuView.java:624)
       at android.support.v7.view.menu.ActionMenuItemView.onClick(ActionMenuItemView.java:150)
       at android.view.View.performClick(View.java:5612)
       at android.view.View$PerformClick.run(View.java:22288)
       at android.os.Handler.handleCallback(Handler.java:751)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6123)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757)
       at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:107)
```

Happening on a few devices on Android 6 and 7. Possible causes:

* onItemCheckedStateChanged not being called
* onPrepareActionMode not being fired by ActionMode.invalidate()
* onDestroyActionMode being called prematurely

**Comment by daniele-athome** [comment]
Found it!
https://issuetracker.google.com/issues/37032031
