### ISSUE TITLE
Kontalk crashes if contacting from external xmpp client

### ISSUE THREAD

**Issue by Perflyst** [kontalk/androidclient#1242]
### Expected behavior
Kontalk should accept the invitation and shouldn't crash.

### Actual behavior
Kontalk is crashing after clicking "ACCEPT".

### Steps to reproduce
1. Create a normal xmpp account
2. Log in to Conversations
3. Optional: Enable OMEMO (i know not supported by kontalk)
4. Write a message to your Kontalk User ID
5. Open Kontalk and click on "ACCEPT".

### Environment

Kontalk version: 4.2.0 F-Droid
Android version: LineageOS 14.1 (Android 7.1.2)
Device model: Samsung G920F

### Logs
I paste them here because there are no private personal details

```
11-29 20:53:29.568  1534  1534 D AndroidRuntime: Shutting down VM
11-29 20:53:29.571  1534  1534 E AndroidRuntime: FATAL EXCEPTION: main
11-29 20:53:29.571  1534  1534 E AndroidRuntime: Process: org.kontalk, PID: 1534
11-29 20:53:29.571  1534  1534 E AndroidRuntime: java.lang.NullPointerException: fingerprint
11-29 20:53:29.571  1534  1534 E AndroidRuntime:        at org.kontalk.MessagesController.setTrustLevelAndRetryMessages(MessagesController.java:288)
11-29 20:53:29.571  1534  1534 E AndroidRuntime:        at org.kontalk.ui.ComposeMessageFragment.setPrivacy(ComposeMessageFragment.java:830)
11-29 20:53:29.571  1534  1534 E AndroidRuntime:        at org.kontalk.ui.ComposeMessageFragment$5.onClick(ComposeMessageFragment.java:773)
11-29 20:53:29.571  1534  1534 E AndroidRuntime:        at android.view.View.performClick(View.java:5637)
11-29 20:53:29.571  1534  1534 E AndroidRuntime:        at android.view.View$PerformClick.run(View.java:22433)
11-29 20:53:29.571  1534  1534 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:751)
11-29 20:53:29.571  1534  1534 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:95)
11-29 20:53:29.571  1534  1534 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:154)
11-29 20:53:29.571  1534  1534 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:6186)
11-29 20:53:29.571  1534  1534 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
11-29 20:53:29.571  1534  1534 E AndroidRuntime:        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
11-29 20:53:29.571  1534  1534 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
11-29 20:53:29.571  1534  1534 E AndroidRuntime:        at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:107)
11-29 20:53:29.572  4876  8264 W ActivityManager:   Force finishing activity org.kontalk/.ui.ComposeMessage
11-29 20:53:29.575  4876  8264 W ActivityManager:   Force finishing activity org.kontalk/.ui.ComposeMessage
11-29 20:53:29.575  4876  8264 W ActivityManager: Duplicate finish request for ActivityRecord{cd5d0de u0 org.kontalk/.ui.ComposeMessage t11968 f}
11-29 20:53:29.613  4876 23305 I OpenGLRenderer: Initialized EGL, version 1.4
11-29 20:53:29.613  4876 23305 D OpenGLRenderer: Swap behavior 1
11-29 20:53:29.617  4876 23305 D mali_winsys: EGLint new_window_surface(egl_winsys_display*, void*, EGLSurface, EGLConfig, egl_winsys_surface**, egl_color_buffer_format*, EGLBoolean) returns 0x3000,  [1624x847]-format:1
11-29 20:53:30.076  4876  4898 W ActivityManager: Activity pause timeout for ActivityRecord{cd5d0de u0 org.kontalk/.ui.ComposeMessage t11968 f}
11-29 20:53:30.214  4876  4895 W art     : Long monitor contention with owner ActivityManager (4898) at android.graphics.Bitmap com.android.server.wm.WindowManagerService.screenshotApplicationsInner(android.os.IBinder, int, int, int, boolean, float, android.graphics.Bitmap$Config, boolean)(WindowManagerService.java:6509) waiters=1 in int com.android.server.wm.WindowManagerService.relayoutWindow(com.android.server.wm.Session, android.view.IWindow, int, android.view.WindowManager$LayoutParams, int, int, int, int, android.graphics.Rect, android.graphics.Rect, android.graphics.Rect, android.graphics.Rect, android.graphics.Rect, android.graphics.Rect, android.graphics.Rect, android.content.res.Configuration, android.view.Surface) for 118ms
11-29 20:53:30.215  4876  4876 V NotificationService: pkg=android canInterrupt=false intercept=true
```

### Other
Note, there is xposed in the logs, please ignore it. I reproduced this with another device running Android 8 without xposed.

**Comment by daniele-athome** [comment]
Thanks for reporting!
