### ISSUE TITLE
Still some issues with debug log sending

### ISSUE THREAD

**Issue by daniele-athome** [kontalk/androidclient#1248]
Something still doesn't work with the file provider. Check it out.

```
java.lang.IllegalArgumentException: Failed to find configured root that contains /storage/0000-0000/Android/data/org.kontalk/cache/debug/kontalk-android.log
       at android.support.v4.content.FileProvider$SimplePathStrategy.getUriForFile(FileProvider.java:739)
       at android.support.v4.content.FileProvider.getUriForFile(FileProvider.java:418)
       at org.kontalk.util.MediaStorage.getWorldAccessibleUri(MediaStorage.java:158)
       at org.kontalk.util.MediaStorage.getWorldReadableUri(MediaStorage.java:134)
       at org.kontalk.ui.prefs.SendDebugLogPreference.sendDebugLog(SendDebugLogPreference.java:72)
       at org.kontalk.ui.prefs.SendDebugLogPreference.onClick(SendDebugLogPreference.java:62)
       at android.preference.Preference.performClick(Preference.java:1167)
       at android.preference.PreferenceScreen.onItemClick(PreferenceScreen.java:257)
       at android.widget.AdapterView.performItemClick(AdapterView.java:321)
       at android.widget.AbsListView.performItemClick(AbsListView.java:1217)
       at android.widget.AbsListView$PerformClick.run(AbsListView.java:3203)
       at android.widget.AbsListView$3.run(AbsListView.java:4151)
       at android.os.Handler.handleCallback(Handler.java:808)
       at android.os.Handler.dispatchMessage(Handler.java:101)
       at android.os.Looper.loop(Looper.java:166)
       at android.app.ActivityThread.main(ActivityThread.java:7523)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)
```

**Comment by daniele-athome** [comment]
Huawei not adhereing to Android contracts, see https://stackoverflow.com/a/41309223/1045199
Moving to internal cache, also for privacy reasons.
