### ISSUE TITLE
Conversation opened from contacts but contacts permission denied

### ISSUE THREAD

**Issue by daniele-athome** [kontalk/androidclient#1281]
Some users have found a way to start a conversation directly from contacts, but without allowing Kontalk to read contacts. This is probably going through "send message" action using the smsto schema. There isn't a safe way to fix this other than asking for permission first (if the user denied it, it would be pointless to ask again) or show a warning toast and abort.

```
java.lang.SecurityException: Permission Denial: opening provider com.android.providers.contacts.ContactsProvider2 from ProcessRecord{e0aced9 28996:org.kontalk/u0a85} (pid=28996, uid=10085) requires android.permission.READ_CONTACTS or android.permission.WRITE_CONTACTS
       at android.os.Parcel.readException + 1692(Parcel.java:1692)
       at android.os.Parcel.readException + 1645(Parcel.java:1645)
       at android.app.ActivityManagerProxy.getContentProvider + 4199(ActivityManagerProxy.java:4199)
       at android.app.ActivityThread.acquireProvider + 5534(ActivityThread.java:5534)
       at android.app.ContextImpl$ApplicationContentResolver.acquireUnstableProvider + 2239(ContextImpl.java:2239)
       at android.content.ContentResolver.acquireUnstableProvider + 1520(ContentResolver.java:1520)
       at android.content.ContentResolver.query + 518(ContentResolver.java:518)
       at android.content.ContentResolver.query + 475(ContentResolver.java:475)
       at org.kontalk.ui.ComposeMessageFragment.handleActionView + 325(ComposeMessageFragment.java:325)
       at org.kontalk.ui.AbstractComposeFragment.processArguments + 1737(AbstractComposeFragment.java:1737)
       at org.kontalk.ui.AbstractComposeFragment.onActivityCreated + 333(AbstractComposeFragment.java:333)
       at android.support.v4.app.Fragment.performActivityCreated + 2460(Fragment.java:2460)
       at android.support.v4.app.FragmentManagerImpl.moveToState + 1483(FragmentManagerImpl.java:1483)
       at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState + 1784(FragmentManagerImpl.java:1784)
       at android.support.v4.app.FragmentManagerImpl.moveToState + 1852(FragmentManagerImpl.java:1852)
       at android.support.v4.app.BackStackRecord.executeOps + 802(BackStackRecord.java:802)
       at android.support.v4.app.FragmentManagerImpl.executeOps + 2625(FragmentManagerImpl.java:2625)
       at android.support.v4.app.FragmentManagerImpl.executeOpsTogether + 2411(FragmentManagerImpl.java:2411)
       at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute + 2366(FragmentManagerImpl.java:2366)
       at android.support.v4.app.FragmentManagerImpl.execSingleAction + 2243(FragmentManagerImpl.java:2243)
       at android.support.v4.app.BackStackRecord.commitNowAllowingStateLoss + 654(BackStackRecord.java:654)
       at org.kontalk.ui.ComposeMessage.setComposeFragment + 156(ComposeMessage.java:156)
       at org.kontalk.ui.ComposeMessage.loadConversation + 176(ComposeMessage.java:176)
       at org.kontalk.ui.ComposeMessage.onNewIntent + 515(ComposeMessage.java:515)
       at android.app.Instrumentation.callActivityOnNewIntent + 1224(Instrumentation.java:1224)
       at android.app.Instrumentation.callActivityOnNewIntent + 1236(Instrumentation.java:1236)
       at android.app.ActivityThread.deliverNewIntents + 2827(ActivityThread.java:2827)
       at android.app.ActivityThread.performNewIntents + 2842(ActivityThread.java:2842)
       at android.app.ActivityThread.handleNewIntent + 2858(ActivityThread.java:2858)
       at android.app.ActivityThread.-wrap15(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage + 1575(ActivityThread.java:1575)
       at android.os.Handler.dispatchMessage + 102(Handler.java:102)
       at android.os.Looper.loop + 154(Looper.java:154)
       at android.app.ActivityThread.main + 6186(ActivityThread.java:6186)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run + 889(ZygoteInit.java:889)
       at com.android.internal.os.ZygoteInit.main + 779(ZygoteInit.java:779)
```

**Comment by daniele-athome** [comment]
Happens on tablet too:

```
Caused by java.lang.SecurityException: Permission Denial: opening provider com.android.providers.contacts.ContactsProvider2 from ProcessRecord{e424548 25171:org.kontalk/u0a245} (pid=25171, uid=10245) requires android.permission.READ_CONTACTS or android.permission.WRITE_CONTACTS
       at android.os.Parcel.readException(Parcel.java:2029)
       at android.os.Parcel.readException(Parcel.java:1975)
       at android.app.IActivityManager$Stub$Proxy.getContentProvider(IActivityManager.java:5228)
       at android.app.ActivityThread.acquireProvider(ActivityThread.java:6204)
       at android.app.ContextImpl$ApplicationContentResolver.acquireUnstableProvider(ContextImpl.java:2676)
       at android.content.ContentResolver.acquireUnstableProvider(ContentResolver.java:1786)
       at android.content.ContentResolver.query(ContentResolver.java:744)
       at android.content.ContentResolver.query(ContentResolver.java:710)
       at android.content.ContentResolver.query(ContentResolver.java:668)
       at org.kontalk.ui.ConversationsActivity.handleIntent(ConversationsActivity.java:129)
       at org.kontalk.ui.ConversationsActivity.onCreate(ConversationsActivity.java:107)
       at android.app.Activity.performCreate(Activity.java:7258)
       at android.app.Activity.performCreate(Activity.java:7249)
```
