### ISSUE TITLE
Unable to register device for the last 4 days

### ISSUE THREAD

**Issue by wibrt** [kontalk/androidclient#1290]
### Expected behavior

After installing Kontalk from f-droid,
putting in a nickname and the phonenr,
and receiving the pin code;
then putting this verification code in the form,
*and clicking on verify,*
i should be registered

### Actual behavior

*after clicking on verify*,
the process just keeps on turning (orange bar on the top),
shortly after i get called usually twice containing the spoken message 
with the same verification code,
the code is correct,
but the registration times out (after an hour or so)/fails? without an error message

### Other

i had used kontalk before, 
with the same device, but it got repaired (hardware),
so i had to reinstall all the software
so the same phone nr exists in the db probably.

### Environment

Kontalk version: F-droid

Android version: FP2 open os (android 7)

Device model: FP2

### Logs

If you have a system log related to the issue please send it via email at
devteam (at) kontalk.org. Please do not attach it or publish it anywhere because
it may contain sensitive information. If you have root access, you can use Catlog
(available on both Google Play and F-Droid) to produce it. Alternatively, if you
have the Android SDK installed on your computer, connect your device and execute:

```
adb logcat -d | grep `adb shell ps | grep org.kontalk | cut -c10-15` >kontalk-log.txt
```

I have done this, but unfortunately it is an empty file.

**Comment by daniele-athome** [comment]
Thanks for reporting. Would you mind sending your phone number to our devteam email? (devteam at kontalk.org) I'd like to make further analysis on the server. Thank you!

**Comment by daniele-athome** [comment]
Also, you can use the debug log feature inside Kontalk preferences (under maintenance):

* activate debug log
* retry registration
* use "send debug log"

No need to use adb this way. Thanks!

**Comment by daniele-athome** [comment]
@wibrt we got your number on the email and checking on the server. [A log would be even better](https://github.com/kontalk/androidclient/issues/1290#issuecomment-601603999) to fully analyze this. Thanks!

**Comment by wibrt** [comment]
ok, i'm running this right now,
the first two attempts  i had the wrong network, just ignore,
now it just keeps on running;
when it finishes i will sent the debug log

**Comment by wibrt** [comment]
Daniele Ricci schreef op vr 20-03-2020 om 16:31 [-0700]:
> @wibrt we got your number on the email and checking on the server. A
> log would be even better to fully analyze this. Thanks!

i have included the log,
at first glance it seems that google does not like my phone number?
(although it is a normal phone number, and i receive the sms and two
calls..)

**Comment by wibrt** [comment]
part of the log:
`I/NumberValidation: setting controls ENABLED
2020-03-21 13:45:34 W/SyncAdapter: doing sync with no server?
2020-03-21 13:45:34 E/SyncAdapter: unable to normalize number: #31# - skipping
2020-03-21 13:45:34 E/SyncAdapter: Error type: NOT_A_NUMBER. The string supplied did not seem to be a phone number.
	at com.google.i18n.phonenumbers.PhoneNumberUtil.parseHelper(PhoneNumberUtil.java:3175)
	at com.google.i18n.phonenumbers.PhoneNumberUtil.parse(PhoneNumberUtil.java:3055)
	at com.google.i18n.phonenumbers.PhoneNumberUtil.parse(PhoneNumberUtil.java:3045)
	at org.kontalk.service.registration.RegistrationService.fixNumber(RegistrationService.java:1577)
	at org.kontalk.service.registration.RegistrationService.fixNumber(RegistrationService.java:1557)
	at org.kontalk.provider.UsersProvider.resync(UsersProvider.java:653)
	at org.kontalk.provider.UsersProvider.update(UsersProvider.java:498)
	at android.content.ContentProvider$Transport.update(ContentProvider.java:358)
	at android.content.ContentResolver.update(ContentResolver.java:1412)
	at org.kontalk.provider.UsersProvider.resync(UsersProvider.java:1121)
	at org.kontalk.ui.CodeValidation$UsersResyncTask.doInBackground(CodeValidation.java:438)
	at org.kontalk.ui.CodeValidation$UsersResyncTask.doInBackground(CodeValidation.java:434)
	at android.os.AsyncTask$2.call(AsyncTask.java:305)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
	at java.lang.Thread.run(Thread.java:761)

2020-03-21 13:45:34 W/SyncAdapter: doing sync with no server?
2020-03-21 13:45:34 W/SyncAdapter: doing sync with no server?
2020-03-21 13:45:34 W/SyncAdapter: doing sync with no server?`

**Comment by daniele-athome** [comment]
That's not your number. That is Kontalk scanning your contacts, but we'll get to that.
I need the full log of what is happening during registration. Please do not publish it here as it might contain private information. Use our devteam email.

P.S. if you replied directly to the GitHub notifications the attachments are stripped out before the reply is published to GitHub.

**Comment by wibrt** [comment]
can i sent that personally, the log, i don't want it to published here publicly, 
as it contains my phone nr (i have sent mails before to devteam)

**Comment by daniele-athome** [comment]
Are you sure? I can't see any email in our devteam inbox (I checked in spam too). If you use the "Send debug log" setting in Kontalk it will prepare an email with the recipient already set.

**Comment by wibrt** [comment]
the log has been sent
