### ISSUE TITLE
HTC contacts issue

### ISSUE THREAD

**Issue by daniele-athome** [kontalk/androidclient#227]
Ref. #111
I'm getting sick of this.

```
09-21 17:13:32.925      741-751/? E/DatabaseUtils Writing exception to parcel
    java.lang.NullPointerException
            at com.android.providers.contacts.HtcContactsProvider2$PhoneDataRowHandler.insert(HtcContactsProvider2.java:10624)
            at com.android.providers.contacts.ContactsProvider2.insertData(ContactsProvider2.java:3647)
            at com.android.providers.contacts.ContactsProvider2.insertInTransaction(ContactsProvider2.java:3101)
            at com.android.providers.contacts.CContactsProvider2.insertInTransaction(CContactsProvider2.java:216)
            at com.android.providers.contacts.HtcContactsProvider2.insertInTransaction(HtcContactsProvider2.java:3406)
            at com.android.providers.contacts.AbstractContactsProvider.insert(AbstractContactsProvider.java:113)
            at com.android.providers.contacts.ContactsProvider2.insert(ContactsProvider2.java:2565)
            at com.android.providers.contacts.CContactsProvider2.insert(CContactsProvider2.java:118)
            at com.android.providers.contacts.HtcContactsProvider2.insert(HtcContactsProvider2.java:3432)
            at android.content.ContentProviderOperation.apply(ContentProviderOperation.java:218)
            at com.android.providers.contacts.AbstractContactsProvider.applyBatch(AbstractContactsProvider.java:214)
            at com.android.providers.contacts.ContactsProvider2.applyBatch(ContactsProvider2.java:2708)
            at com.android.providers.contacts.CContactsProvider2.applyBatch(CContactsProvider2.java:160)
            at com.android.providers.contacts.HtcContactsProvider2.applyBatch(HtcContactsProvider2.java:3455)
            at android.content.ContentProvider$Transport.applyBatch(ContentProvider.java:243)
            at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:211)
            at android.os.Binder.execTransact(Binder.java:367)
            at dalvik.system.NativeStart.run(Native Method)
09-21 17:13:32.925  10293-11081/? E/SyncAdapter contact write error
    java.lang.NullPointerException
            at android.os.Parcel.readException(Parcel.java:1440)
            at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:188)
            at android.database.DatabaseUtils.readExceptionWithOperationApplicationExceptionFromParcel(DatabaseUtils.java:163)
            at android.content.ContentProviderProxy.applyBatch(ContentProviderNative.java:523)
            at android.content.ContentProviderClient.applyBatch(ContentProviderClient.java:225)
            at org.kontalk.sync.Syncer.performSync(Syncer.java:422)
            at org.kontalk.sync.SyncAdapter.onPerformSync(SyncAdapter.java:93)
            at android.content.AbstractThreadedSyncAdapter$SyncThread.run(AbstractThreadedSyncAdapter.java:254)
```

**Comment by RoelRoel** [comment]
How did you fix this?

**Comment by daniele-athome** [comment]
It was a HTC issue. Please see https://github.com/kontalk/androidclient/issues/111#issuecomment-37270993 and commit 45c416b16a6c834bd80d9b5a35b8dfe344da6762.
