### ISSUE TITLE
MediaPlayer instance is null

### ISSUE THREAD

**Issue by daniele-athome** [kontalk/androidclient#236]
When leaving the activity while playing an audio message, returning to the activity does not recreate the MediaPlayer instance, thus leading to a NPE.

```
java.lang.NullPointerException
	at org.kontalk.ui.ComposeMessageFragment.playAudio(ComposeMessageFragment.java:2601)
	at org.kontalk.ui.ComposeMessageFragment.buttonClick(ComposeMessageFragment.java:2541)
	at org.kontalk.ui.AudioContentView.onClick(AudioContentView.java:128)
```

**Comment by daniele-athome** [comment]
This should be fixed with a16b950.
