### ISSUE TITLE
Handle CPIM parse error as security fault

### ISSUE THREAD

**Issue by daniele-athome** [kontalk/androidclient#295]
For messages sent from Pidgin (happens once in a while).

```
decryption failed
java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.length()' on a null object reference
    at org.jxmpp.util.XmppDateTime.convertXep82TimezoneToRfc822(XmppDateTime.java:229)
    at org.jxmpp.util.XmppDateTime$DateFormatType.parse(XmppDateTime.java:106)
    at org.kontalk.util.CPIMMessage.parse(CPIMMessage.java:171)
    at org.kontalk.crypto.PGPCoder.decryptText(PGPCoder.java:355)
    at org.kontalk.util.MessageUtils.decryptMessage(MessageUtils.java:577)
    at org.kontalk.util.MessageUtils.decryptMessage(MessageUtils.java:554)
```

**Comment by daniele-athome** [comment]
Fixed in Pidgin plugin (kontalk/client-adapters@f7dac883bc99ffcd251706f06bda3cf1e374ca13). But the CPIM parser needs optimizations. Consider these parsing errors as warning and light up the security fault warning icon (the big red warning icon :-).
