### ISSUE TITLE
Crash on opening unknown contact

### ISSUE THREAD

**Issue by daniele-athome** [kontalk/androidclient#385]
Trying to carry out this intent (resuming compose activity):

```
I/ActivityManager(962): START u0 {act=android.intent.action.VIEW dat=content://com.android.contacts/data/4679 flg=0x10100000 cmp=org.kontalk/.ui.ComposeMessage} from uid 10006 on display 0
```

resulted in this crash:

```
java.lang.RuntimeException: Unable to start activity ComponentInfo{org.kontalk/org.kontalk.ui.ComposeMessage}: java.lang.NullPointerException: key == null
     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2314)
     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2388)
     at android.app.ActivityThread.access$800(ActivityThread.java:148)
     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1292)
     at android.os.Handler.dispatchMessage(Handler.java:102)
     at android.os.Looper.loop(Looper.java:135)
     at android.app.ActivityThread.main(ActivityThread.java:5312)
     at java.lang.reflect.Method.invoke(Native Method)
     at java.lang.reflect.Method.invoke(Method.java:372)
     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:901)
     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:696)
Caused by: java.lang.NullPointerException: key == null
     at android.support.v4.util.LruCache.get(LruCache.java:79)
     at org.kontalk.data.Contact$ContactCache.get(Contact.java:117)
     at org.kontalk.data.Contact.findByUserId(Contact.java:319)
     at org.kontalk.data.Conversation.loadContact(Conversation.java:140)
     at org.kontalk.data.Conversation.setRecipient(Conversation.java:174)
     at org.kontalk.ui.ComposeMessageFragment.processArguments(ComposeMessageFragment.java:1528)
     at org.kontalk.ui.ComposeMessageFragment.onActivityCreated(ComposeMessageFragment.java:388)
     at android.support.v4.app.Fragment.performActivityCreated(Fragment.java:1794)
     at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:967)
     at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1126)
     at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1108)
     at android.support.v4.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:1917)
     at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:544)
     at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1243)
     at android.app.Activity.performStart(Activity.java:5969)
     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2277)
     ... 10 more
```

**Comment by daniele-athome** [comment]
Unable to reproduce. Closing for now.
