### ISSUE TITLE
Unknown crash probably from 2.x upgrade gone south

### ISSUE THREAD

**Issue by daniele-athome** [kontalk/androidclient#410]
Reported from Google Play on version 3.0-rc3.

```
java.lang.IllegalArgumentException: server is null
at org.kontalk.util.XMPPUtils.createLocalJID(XMPPUtils.java:96)
at org.kontalk.authenticator.Authenticator.isSelfJID(Authenticator.java:130)
at org.kontalk.ui.ComposeMessageFragment.updateUI(ComposeMessageFragment.java:2374)
at org.kontalk.ui.ComposeMessageFragment.onCreateOptionsMenu(ComposeMessageFragment.java:670)
at android.support.v4.app.Fragment.performCreateOptionsMenu(Fragment.java:1868)
at android.support.v4.app.FragmentManagerImpl.dispatchCreateOptionsMenu(FragmentManager.java:1989)
at android.support.v4.app.FragmentActivity.onCreatePanelMenu(FragmentActivity.java:276)
at android.support.v7.app.ActionBarActivity.superOnCreatePanelMenu(ActionBarActivity.java:233)
at android.support.v7.app.ActionBarActivityDelegateICS.onCreatePanelMenu(ActionBarActivityDelegateICS.java:146)
at android.support.v7.app.ActionBarActivity.onCreatePanelMenu(ActionBarActivity.java:200)
at android.support.v7.app.ActionBarActivityDelegateICS$WindowCallbackWrapper.onCreatePanelMenu(ActionBarActivityDelegateICS.java:293)
at com.android.internal.policy.impl.PhoneWindow.preparePanel(PhoneWindow.java:575)
at com.android.internal.policy.impl.PhoneWindow.doInvalidatePanelMenu(PhoneWindow.java:944)
at com.android.internal.policy.impl.PhoneWindow$1.run(PhoneWindow.java:285)
at android.os.Handler.handleCallback(Handler.java:739)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:155)
at android.app.ActivityThread.main(ActivityThread.java:5696)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1028)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:823)
```

**Comment by daniele-athome** [comment]
Unable to reproduce. Probably triggered by malformed manual server address set in a 2.x version.
