### ISSUE TITLE
java.lang.ArrayIndexOutOfBoundsException: result:3 at android.graphics.Text.setPaint

### ISSUE THREAD

**Issue by daniele-athome** [kontalk/androidclient#45]
_From [daniele.athome@gmail.com](https://code.google.com/u/daniele.athome@gmail.com/) on April 29, 2013 11:40:53_

User message: app closes when sending messages with emoji.
Still a "conflict" problem with internal Emoji handling by operating system. Damn Android fragmentation!!!

```
java.lang.ArrayIndexOutOfBoundsException: result:3
at android.graphics.Text.setPaint(Native Method)
at android.graphics.Text.setPaint(Text.java:211)
at android.text.Layout.each(Layout.java:350)
at android.text.Layout.decorateText(Layout.java:312)
at android.text.Layout.reflow(Layout.java:410)
at android.text.Layout.reflow(Layout.java:380)
at android.text.DynamicLayout.reflow(DynamicLayout.java:292)
at android.text.DynamicLayout$ChangeWatcher.reflow(DynamicLayout.java:180)
at android.text.DynamicLayout$ChangeWatcher.onSpanAdded(DynamicLayout.java:200)
at android.text.SpannableStringBuilder.sendSpanAdded(SpannableStringBuilder.java:915)
at android.text.SpannableStringBuilder.setSpan(SpannableStringBuilder.java:620)
at android.text.SpannableStringBuilder.setSpan(SpannableStringBuilder.java:523)
at android.view.inputmethod.BaseInputConnection.setComposingRegion(BaseInputConnection.java:441)
at com.android.internal.view.IInputConnectionWrapper.executeMessage(IInputConnectionWrapper.java:327)
at com.android.internal.view.IInputConnectionWrapper$MyHandler.handleMessage(IInputConnectionWrapper.java:75)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:130)
at android.app.ActivityThread.main(ActivityThread.java:3701)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:507)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:866)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:624)
at dalvik.system.NativeStart.main(Native Method)
```

_Original issue: http://code.google.com/p/kontalk/issues/detail?id=74_

**Comment by daniele-athome** [comment]
Giving up on this.

**Comment by hasanaga** [comment]
Another one...

`java.lang.ArrayIndexOutOfBoundsException: length=116; index=252
at android.text.MeasuredText.addStyleRun(MeasuredText.java:168)
at android.text.MeasuredText.addStyleRun(MeasuredText.java:204)
at android.text.StaticLayout.generate(StaticLayout.java:281)
at android.text.DynamicLayout.reflow(DynamicLayout.java:284)
at android.text.DynamicLayout.access$000(DynamicLayout.java:35)
at android.text.DynamicLayout$ChangeWatcher.reflow(DynamicLayout.java:621)
at android.text.DynamicLayout$ChangeWatcher.onTextChanged(DynamicLayout.java:631)
at android.text.SpannableStringBuilder.sendTextChanged(SpannableStringBuilder.java:962)
at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:496)
at android.text.SpannableStringBuilder.append(SpannableStringBuilder.java:253)
at android.text.SpannableStringBuilder.append(SpannableStringBuilder.java:30)
at android.widget.TextView.append(TextView.java:3131)`
