### ISSUE TITLE
Unique constraint exception during sync

### ISSUE THREAD

**Issue by daniele-athome** [kontalk/androidclient#454]
Happening in unknown conditions.

```
D/SyncAdapter(6418): sync took 56.18700 seconds
FATAL EXCEPTION: SyncAdapterThread-1
android.database.sqlite.SQLiteConstraintException: column number is not unique (code 19)
     at android.database.sqlite.SQLiteConnection.nativeExecuteForChangedRowCount(Native Method)
     at android.database.sqlite.SQLiteConnection.executeForChangedRowCount(SQLiteConnection.java:734)
     at android.database.sqlite.SQLiteSession.executeForChangedRowCount(SQLiteSession.java:754)
     at android.database.sqlite.SQLiteStatement.executeUpdateDelete(SQLiteStatement.java:64)
     at android.database.sqlite.SQLiteDatabase.updateWithOnConflict(SQLiteDatabase.java:1574)
     at android.database.sqlite.SQLiteDatabase.update(SQLiteDatabase.java:1520)
     at org.kontalk.provider.UsersProvider.updateUser(UsersProvider.java:349)
     at org.kontalk.provider.UsersProvider.update(UsersProvider.java:335)
     at android.content.ContentProvider$Transport.update(ContentProvider.java:287)
     at android.content.ContentProviderClient.update(ContentProviderClient.java:251)
     at org.kontalk.sync.Syncer.performSync(Syncer.java:549)
     at org.kontalk.sync.SyncAdapter.onPerformSync(SyncAdapter.java:111)
     at android.content.AbstractThreadedSyncAdapter$SyncThread.run(AbstractThreadedSyncAdapter.java:259)
```

**Comment by daniele-athome** [comment]
Got it! ACTION_CONNECTED in the receiver was triggered twice, making it send another roster match request.
