### ISSUE TITLE
Pictures can't be uploaded 

### ISSUE THREAD

**Issue by Fab2100** [kontalk/androidclient#462]
It is not possible for me to upload / send a picture from the gallery to a recipient. 
Everytime I try it the picture is shown in the conversations list with a small clock in the right lower end of the bubble. 
After some sec a notification appears with an error message, that the file could not be uploaded. 

This happens on mobile data and wifi too. 

Kontalk 3.0; Cyanogenos 12; Android 5.0.0

**Comment by daniele-athome** [comment]
Thanks for reporting. I had similar reports but had no way to debug it. Could you send me a full system log to the devteam email address after trying to reproduce the issue?

**Comment by Fab2100** [comment]
Done

**Comment by daniele-athome** [comment]
```
upload error
java.io.IOException: upload error
      at org.kontalk.upload.KontalkBoxUploadConnection.innerException(KontalkBoxUploadConnection.java:176)
      at org.kontalk.upload.KontalkBoxUploadConnection.upload(KontalkBoxUploadConnection.java:156)
      at org.kontalk.service.UploadService.onHandleIntent(UploadService.java:199)
      at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:65)
      at android.os.Handler.dispatchMessage(Handler.java:102)
      at android.os.Looper.loop(Looper.java:135)
      at android.os.HandlerThread.run(HandlerThread.java:61)
Caused by: javax.net.ssl.SSLPeerUnverifiedException: No peer certificate
      at com.android.org.conscrypt.SSLNullSession.getPeerCertificates(SSLNullSession.java:104)
      at org.apache.http.conn.ssl.AbstractVerifier.verify(AbstractVerifier.java:93)
      at org.apache.http.conn.ssl.SSLSocketFactory.createSocket(SSLSocketFactory.java:388)
      at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:165)
      at org.apache.http.impl.conn.AbstractPoolEntry.open(AbstractPoolEntry.java:164)
      at org.apache.http.impl.conn.AbstractPooledConnAdapter.open(AbstractPooledConnAdapter.java:119)
      at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:360)
      at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:555)
      at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:487)
      at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:465)
      at org.kontalk.upload.KontalkBoxUploadConnection.execute(KontalkBoxUploadConnection.java:258)
      at org.kontalk.upload.KontalkBoxUploadConnection.upload(KontalkBoxUploadConnection.java:149)
      ... 5 more
```

**Comment by daniele-athome** [comment]
Issue was solved. Please try again and if it doesn't work, regenerate your key from Kontalk settings.
