### ISSUE TITLE
Out of memory when resizing image

### ISSUE THREAD

**Issue by daniele-athome** [kontalk/androidclient#476]
This is going to be hard to fix, if at all possible. Reported on a HTC Desire C running Android 4.0.x.

```
java.lang.OutOfMemoryError: (Heap Size=32803KB, Allocated=28238KB)
at android.graphics.Bitmap.nativeCreateScaledBitmap(Native Method)
at android.graphics.Bitmap.createScaledBitmap(Bitmap.java:744)
at org.kontalk.util.MediaStorage.resizeImage(MediaStorage.java:388)
at org.kontalk.util.MediaStorage.resizeImage(MediaStorage.java:312)
at org.kontalk.service.UploadService.onHandleIntent(UploadService.java:173)
at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:65)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:156)
at android.os.HandlerThread.run(HandlerThread.java:60)
```

**Comment by daniele-athome** [comment]
Another one.

```
java.lang.OutOfMemoryError: bitmap size exceeds VM budget
at android.graphics.Bitmap.nativeCreate(Native Method)
at android.graphics.Bitmap.createBitmap(Bitmap.java:477)
at android.graphics.Bitmap.createBitmap(Bitmap.java:444)
at android.graphics.Bitmap.createScaledBitmap(Bitmap.java:349)
at org.kontalk.util.MediaStorage.resizeImage(MediaStorage.java:388)
at org.kontalk.util.MediaStorage.resizeImage(MediaStorage.java:312)
at org.kontalk.service.UploadService.onHandleIntent(UploadService.java:173)
at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:59)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:130)
at android.os.HandlerThread.run(HandlerThread.java:60)
```

**Comment by ameenross** [comment]
Is this because those devices are memory constrained? HTC Desire C has 512 MB or RAM and the Huawei has 256.

**Comment by daniele-athome** [comment]
@ameenross yes, but I remember we've handled that by resampling the image on loading. I'll see what I can do to further optimize it.

**Comment by daniele-athome** [comment]
I did something to further optimize it, but it must be tested on the real device. Closing for now.
