### ISSUE TITLE
ANR when loading avatar for notification

### ISSUE THREAD

**Issue by daniele-athome** [kontalk/androidclient#477]
Another impossible fix. I probably had better to load avatars in the background somehow even in onCreate and fire the notification afterwards.

```
(mutexes: tll=0 tsl=0 tscl=0 ghl=0)
"main" prio=5 tid=1 NATIVE
| group="main" sCount=1 dsCount=0 obj=0x40ab6490 self=0x1b8ad20
| sysTid=1853 nice=0 sched=0/0 cgrp=default handle=1074877736
| schedstat=( 956787114 1248748773 724 ) utm=83 stm=12 core=0
at android.os.BinderProxy.transact(Native Method)
at android.content.ContentProviderProxy.query(ContentProviderNative.java:404)
at android.content.ContentResolver.query(ContentResolver.java:315)
at android.provider.ContactsContract$Contacts.openContactPhotoInputStream(ContactsContract.java:2019)
at android.provider.ContactsContract$Contacts.openContactPhotoInputStream(ContactsContract.java:2050)
at org.kontalk.data.Contact.loadAvatarData(Contact.java:404)
at org.kontalk.data.Contact.getAvatar(Contact.java:253)
at org.kontalk.ui.MessagingNotification.updateMessagesNotification(MessagingNotification.java:432)
at org.kontalk.Kontalk.onCreate(Kontalk.java:150)
at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:981)
at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4494)
at android.app.ActivityThread.access$1300(ActivityThread.java:139)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1306)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:156)
at android.app.ActivityThread.main(ActivityThread.java:4987)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:511)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:784)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:551)
at dalvik.system.NativeStart.main(Native Method)
```

**Comment by daniele-athome** [comment]
Not fixing this for the moment. It happens only on very low end devices. Let's see if we receive more reports.
