### ISSUE TITLE
Registration fails (kontalk.halifax.rwth-aachen.de connection refused)

### ISSUE THREAD

**Issue by TheLastProject** [kontalk/androidclient#501]
Reporting for a friend. He says it could just be on his side but I figured I'd report it anyway, because I get "connection refused" upon doing `telnet kontalk.halifax.rwth-aachen.de 5222`.

Logcat:
```
07-12 11:49:04.049 I/PackageManager(300): /data/app/org.kontalk-1.apk changed; collecting certs
07-12 11:51:14.509 I/ActivityManager(300): Starting: Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=org.kontalk/.ui.ConversationList } from pid 717
07-12 11:51:14.599 I/ActivityManager(300): Start proc org.kontalk for activity org.kontalk/.ui.ConversationList: pid=727 uid=10010 gids={3003, 1015}
07-12 11:51:15.389 I/ActivityThread(727): Pub org.kontalk.messages: org.kontalk.provider.MessagesProvider
07-12 11:51:15.399 I/dalvikvm(727): Could not find method android.database.sqlite.SQLiteDatabase.beginTransactionNonExclusive, referenced from method org.kontalk.provider.MessagesProvider.beginTransaction
07-12 11:51:15.439 I/ActivityThread(727): Pub org.kontalk.users: org.kontalk.provider.UsersProvider
07-12 11:51:15.439 I/dalvikvm(727): Could not find method android.database.sqlite.SQLiteDatabase.beginTransactionNonExclusive, referenced from method org.kontalk.provider.UsersProvider.beginTransaction
07-12 11:51:16.949 I/dalvikvm(727): Could not find method android.view.Display.getSize, referenced from method org.kontalk.util.Preferences.cacheConversationBackground
07-12 11:51:16.949 D/dalvikvm(727): VFY: dead code 0x001c-001f in Lorg/kontalk/util/Preferences;.cacheConversationBackground (Landroid/content/Context;Landroid/net/Uri;)Ljava/io/File;
07-12 11:51:17.289 I/ActivityManager(300): Starting: Intent { cmp=org.kontalk/.ui.NumberValidation (has extras) } from pid 727
07-12 11:51:17.319 W/ActivityManager(300): Unable to start service Intent { act=org.kontalk.action.RELEASE cmp=org.kontalk/.service.msgcenter.MessageCenterService }: not found
07-12 11:51:19.879 W/ActivityManager(300): Activity pause timeout for HistoryRecord{40594800 org.kontalk/.ui.NumberValidation}
07-12 11:51:29.269 I/ActivityManager(300): Starting: Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=org.kontalk/.ui.ConversationList } from pid 717
07-12 11:51:29.469 I/ActivityManager(300): Displayed org.kontalk/.ui.NumberValidation: +12s153ms
07-12 11:51:38.679 V/KeyPair (727): key pair generated: org.kontalk.crypto.PersonalKey@40c4d5b0
07-12 11:51:38.699 V/NumberValidator(727): key generation completed org.kontalk.crypto.PersonalKey@40c4d5b0
07-12 11:51:38.699 D/MessageCenterService(727): using server beta.kontalk.net
07-12 11:51:41.719 D/MessageCenterService(727): using server beta.kontalk.net
07-12 11:51:42.659 I/ActivityManager(300): Starting: Intent { cmp=org.kontalk/.ui.CodeValidation (has extras) } from pid 727
07-12 11:51:43.029 I/ActivityManager(300): Displayed org.kontalk/.ui.CodeValidation: +317ms
07-12 11:51:58.989 D/MessageCenterService(727): using server beta.kontalk.net
07-12 11:53:40.209 I/ActivityManager(300): Starting: Intent { act=android.settings.APPLICATION_DETAILS_SETTINGS dat=package:org.kontalk cmp=com.android.settings/.applications.InstalledAppDetails } from pid 383
07-12 11:53:43.509 I/InstalledAppDetails(383): Clearing user data for package : org.kontalk
07-12 11:53:43.519 I/ActivityManager(300): Force stopping package org.kontalk uid=10010
07-12 11:53:43.619 I/InstalledAppDetails(383): Cleared user data for package : org.kontalk
07-12 11:56:19.479 I/ActivityManager(300): Starting: Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=org.kontalk/.ui.ConversationList } from pid 717
07-12 11:56:19.489 I/ActivityManager(300): Start proc org.kontalk for activity org.kontalk/.ui.ConversationList: pid=846 uid=10010 gids={3003, 1015}
07-12 11:56:19.909 I/ActivityThread(846): Pub org.kontalk.messages: org.kontalk.provider.MessagesProvider
07-12 11:56:19.909 I/dalvikvm(846): Could not find method android.database.sqlite.SQLiteDatabase.beginTransactionNonExclusive, referenced from method org.kontalk.provider.MessagesProvider.beginTransaction
07-12 11:56:19.939 I/ActivityThread(846): Pub org.kontalk.users: org.kontalk.provider.UsersProvider
07-12 11:56:19.939 I/dalvikvm(846): Could not find method android.database.sqlite.SQLiteDatabase.beginTransactionNonExclusive, referenced from method org.kontalk.provider.UsersProvider.beginTransaction
07-12 11:56:21.599 I/dalvikvm(846): Could not find method android.view.Display.getSize, referenced from method org.kontalk.util.Preferences.cacheConversationBackground
07-12 11:56:21.599 D/dalvikvm(846): VFY: dead code 0x001c-001f in Lorg/kontalk/util/Preferences;.cacheConversationBackground (Landroid/content/Context;Landroid/net/Uri;)Ljava/io/File;
07-12 11:56:21.969 I/ActivityManager(300): Starting: Intent { cmp=org.kontalk/.ui.NumberValidation (has extras) } from pid 846
07-12 11:56:21.979 W/ActivityManager(300): Unable to start service Intent { act=org.kontalk.action.RELEASE cmp=org.kontalk/.service.msgcenter.MessageCenterService }: not found
07-12 11:56:26.119 I/ActivityManager(300): Displayed org.kontalk/.ui.NumberValidation: +4s133ms (total +6s629ms)
07-12 11:56:45.579 V/KeyPair (846): key pair generated: org.kontalk.crypto.PersonalKey@40c6bab0
07-12 11:56:45.579 V/NumberValidator(846): key generation completed org.kontalk.crypto.PersonalKey@40c6bab0
07-12 11:56:45.579 D/MessageCenterService(846): using server kontalk.halifax.rwth-aachen.de|kontalk.halifax.rwth-aachen.de:5222
07-12 11:56:47.029 W/NumberValidator(846): org.jivesoftware.smack.SmackException$ConnectionException: The following addresses failed: 'kontalk.halifax.rwth-aachen.de:5222' failed because java.net.ConnectException: kontalk.halifax.rwth-aachen.de/137.226.111.112:5222 - Connection refused
07-12 11:56:47.029 W/NumberValidator(846): 	at org.kontalk.service.XMPPConnectionHelper.connectOnce(XMPPConnectionHelper.java:192)
07-12 11:56:47.029 W/NumberValidator(846): 	at org.kontalk.service.XMPPConnectionHelper.connectOnce(XMPPConnectionHelper.java:141)
07-12 11:56:47.029 W/NumberValidator(846): 	at org.kontalk.client.NumberValidator.initConnection(NumberValidator.java:478)
07-12 11:56:47.029 W/NumberValidator(846): 	at org.kontalk.client.NumberValidator.run(NumberValidator.java:201)
07-12 11:56:47.029 D/MessageCenterService(846): using server beta.kontalk.net
07-12 11:56:52.440 D/MessageCenterService(846): using server beta.kontalk.net
07-12 11:56:54.389 I/ActivityManager(300): Starting: Intent { cmp=org.kontalk/.ui.CodeValidation (has extras) } from pid 846
07-12 11:56:54.759 I/ActivityManager(300): Displayed org.kontalk/.ui.CodeValidation: +326ms
07-12 11:57:00.449 I/ActivityManager(300): Starting: Intent { cmp=org.kontalk/.ui.CodeValidation (has extras) } from pid 846
07-12 11:57:00.789 I/ActivityManager(300): Displayed org.kontalk/.ui.CodeValidation: +281ms
07-12 11:57:15.359 D/MessageCenterService(846): using server beta.kontalk.net
07-12 12:01:40.679 I/ActivityManager(300): Starting: Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=org.kontalk/.ui.ConversationList } from pid 717
07-12 12:01:40.919 I/ActivityManager(300): Starting: Intent { cmp=org.kontalk/.ui.NumberValidation (has extras) } from pid 846
07-12 12:01:40.929 W/ActivityManager(300): Unable to start service Intent { act=org.kontalk.action.RELEASE cmp=org.kontalk/.service.msgcenter.MessageCenterService }: not found
07-12 12:01:41.269 I/ActivityManager(300): Displayed org.kontalk/.ui.NumberValidation: +339ms (total +571ms)
07-12 12:01:41.889 I/ActivityManager(300): Starting: Intent { cmp=org.kontalk/.ui.BootstrapPreferences } from pid 846
07-12 12:01:41.939 I/dalvikvm(846): Could not find method org.kontalk.ui.BootstrapPreferences.getActionBar, referenced from method org.kontalk.ui.BootstrapPreferences.setupActivity
07-12 12:01:41.939 W/dalvikvm(846): VFY: unable to resolve virtual method 15553: Lorg/kontalk/ui/BootstrapPreferences;.getActionBar ()Landroid/app/ActionBar;
07-12 12:01:41.939 D/dalvikvm(846): VFY: dead code 0x000a-0010 in Lorg/kontalk/ui/BootstrapPreferences;.setupActivity ()V
07-12 12:01:41.999 I/dalvikvm(846): Could not find method org.kontalk.ui.PreferencesActivity.getActionBar, referenced from method org.kontalk.ui.PreferencesActivity.setupActivity
07-12 12:01:41.999 W/dalvikvm(846): VFY: unable to resolve virtual method 16360: Lorg/kontalk/ui/PreferencesActivity;.getActionBar ()Landroid/app/ActionBar;
07-12 12:01:41.999 D/dalvikvm(846): VFY: dead code 0x000a-0010 in Lorg/kontalk/ui/PreferencesActivity;.setupActivity ()V
07-12 12:01:42.329 I/ActivityManager(300): Displayed org.kontalk/.ui.BootstrapPreferences: +417ms
07-12 12:01:45.049 V/KeyPair (846): key pair generated: org.kontalk.crypto.PersonalKey@40ad68d8
07-12 12:02:28.979 D/MessageCenterService(846): using server kontalk.halifax.rwth-aachen.de|kontalk.halifax.rwth-aachen.de:5222
07-12 12:02:29.189 W/NumberValidator(846): org.jivesoftware.smack.SmackException$ConnectionException: The following addresses failed: 'kontalk.halifax.rwth-aachen.de:5222' failed because java.net.ConnectException: kontalk.halifax.rwth-aachen.de/137.226.111.112:5222 - Connection refused
07-12 12:02:29.189 W/NumberValidator(846): 	at org.kontalk.service.XMPPConnectionHelper.connectOnce(XMPPConnectionHelper.java:192)
07-12 12:02:29.189 W/NumberValidator(846): 	at org.kontalk.service.XMPPConnectionHelper.connectOnce(XMPPConnectionHelper.java:141)
07-12 12:02:29.189 W/NumberValidator(846): 	at org.kontalk.client.NumberValidator.initConnection(NumberValidator.java:478)
07-12 12:02:29.189 W/NumberValidator(846): 	at org.kontalk.client.NumberValidator.run(NumberValidator.java:201)
07-12 12:02:29.189 D/MessageCenterService(846): using server beta.kontalk.net
07-12 12:02:31.629 D/MessageCenterService(846): using server kontalk.halifax.rwth-aachen.de|kontalk.halifax.rwth-aachen.de:5222
07-12 12:02:31.859 W/NumberValidator(846): org.jivesoftware.smack.SmackException$ConnectionException: The following addresses failed: 'kontalk.halifax.rwth-aachen.de:5222' failed because java.net.ConnectException: kontalk.halifax.rwth-aachen.de/137.226.111.112:5222 - Connection refused
07-12 12:02:31.859 W/NumberValidator(846): 	at org.kontalk.service.XMPPConnectionHelper.connectOnce(XMPPConnectionHelper.java:192)
07-12 12:02:31.859 W/NumberValidator(846): 	at org.kontalk.service.XMPPConnectionHelper.connectOnce(XMPPConnectionHelper.java:141)
07-12 12:02:31.859 W/NumberValidator(846): 	at org.kontalk.client.NumberValidator.initConnection(NumberValidator.java:478)
07-12 12:02:31.859 W/NumberValidator(846): 	at org.kontalk.client.NumberValidator.run(NumberValidator.java:201)
07-12 12:02:31.859 D/MessageCenterService(846): using server beta.kontalk.net
07-12 12:02:32.989 I/ActivityManager(300): Starting: Intent { cmp=org.kontalk/.ui.CodeValidation (has extras) } from pid 846
07-12 12:02:33.379 I/ActivityManager(300): Displayed org.kontalk/.ui.CodeValidation: +300ms
07-12 12:02:55.129 D/MessageCenterService(846): using server beta.kontalk.net
07-12 12:12:47.559 I/ActivityManager(300): Starting: Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=org.kontalk/.ui.ConversationList } from pid 717
07-12 12:12:47.829 I/ActivityManager(300): Starting: Intent { cmp=org.kontalk/.ui.NumberValidation (has extras) } from pid 846
07-12 12:12:47.839 W/ActivityManager(300): Unable to start service Intent { act=org.kontalk.action.RELEASE cmp=org.kontalk/.service.msgcenter.MessageCenterService }: not found
07-12 12:12:48.119 I/ActivityManager(300): Displayed org.kontalk/.ui.NumberValidation: +278ms (total +523ms)
07-12 12:12:54.309 V/KeyPair (846): key pair generated: org.kontalk.crypto.PersonalKey@40e62158
07-12 12:12:55.469 D/MessageCenterService(846): using server kontalk.halifax.rwth-aachen.de|kontalk.halifax.rwth-aachen.de:5222
07-12 12:12:56.059 W/NumberValidator(846): org.jivesoftware.smack.SmackException$ConnectionException: The following addresses failed: 'kontalk.halifax.rwth-aachen.de:5222' failed because java.net.ConnectException: kontalk.halifax.rwth-aachen.de/137.226.111.112:5222 - Connection refused
07-12 12:12:56.059 W/NumberValidator(846): 	at org.kontalk.service.XMPPConnectionHelper.connectOnce(XMPPConnectionHelper.java:192)
07-12 12:12:56.059 W/NumberValidator(846): 	at org.kontalk.service.XMPPConnectionHelper.connectOnce(XMPPConnectionHelper.java:141)
07-12 12:12:56.059 W/NumberValidator(846): 	at org.kontalk.client.NumberValidator.initConnection(NumberValidator.java:478)
07-12 12:12:56.059 W/NumberValidator(846): 	at org.kontalk.client.NumberValidator.run(NumberValidator.java:201)
07-12 12:12:56.059 D/MessageCenterService(846): using server beta.kontalk.net
07-12 12:12:58.279 D/MessageCenterService(846): using server kontalk.halifax.rwth-aachen.de|kontalk.halifax.rwth-aachen.de:5222
07-12 12:12:58.389 W/NumberValidator(846): org.jivesoftware.smack.SmackException$ConnectionException: The following addresses failed: 'kontalk.halifax.rwth-aachen.de:5222' failed because java.net.ConnectException: kontalk.halifax.rwth-aachen.de/137.226.111.112:5222 - Connection refused
07-12 12:12:58.389 W/NumberValidator(846): 	at org.kontalk.service.XMPPConnectionHelper.connectOnce(XMPPConnectionHelper.java:192)
07-12 12:12:58.389 W/NumberValidator(846): 	at org.kontalk.service.XMPPConnectionHelper.connectOnce(XMPPConnectionHelper.java:141)
07-12 12:12:58.389 W/NumberValidator(846): 	at org.kontalk.client.NumberValidator.initConnection(NumberValidator.java:478)
07-12 12:12:58.389 W/NumberValidator(846): 	at org.kontalk.client.NumberValidator.run(NumberValidator.java:201)
07-12 12:12:58.389 D/MessageCenterService(846): using server beta.kontalk.net
07-12 12:12:59.399 I/ActivityManager(300): Starting: Intent { cmp=org.kontalk/.ui.CodeValidation (has extras) } from pid 846
07-12 12:12:59.729 I/ActivityManager(300): Displayed org.kontalk/.ui.CodeValidation: +281ms
07-12 12:13:18.289 D/MessageCenterService(846): using server beta.kontalk.net
```

**Comment by TheLastProject** [comment]
The friend could finish registration after manually setting the server to beta.kontalk.net in settings.

**Comment by daniele-athome** [comment]
The app tries all servers in the server list until it finds one that it can connect to.
It seems it tries to connect to beta:

> 07-12 12:02:29.189 D/MessageCenterService(846): using server beta.kontalk.net

But somehow skips it without errors... is your friend updating from a previous version? And I guess he/she's using the latest version.

**Comment by TheLastProject** [comment]
He installed the app to his SD card (I assume force-moved it there), at which point he had to re-register after unmounting his SD card. Before doing so, he did a fresh install (this time to the internal storage). 3.0.1 is the only version he ever ran.

**Comment by daniele-athome** [comment]
Can you make him install this debug version and try to register again?
http://astra.casaricci.it/public/Kontalk-3.0.1-googleplay-debug.apk

He should uninstall the old version first to be sure everything is clean. I'll need a logcat after a registration attempt.

**Comment by TheLastProject** [comment]
He is an F-Droid user, not sure if he even has Google Play, so I assume a debug build for the basic version would be better, but I'll ask him if he's up to trying that.

**Comment by daniele-athome** [comment]
@TheLastProject I can produce that if he wants, but if Google Play is not installed on his device, the Google Play part of the app won't activate at all.

**Comment by TheLastProject** [comment]
```
07-13 11:11:40.730 I/InstallAppProgress(1523): Finished installing org.kontalk
07-13 11:12:08.950 I/ActivityManager(300): Starting: Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=org.kontalk/.ui.ConversationList } from pid 548
07-13 11:12:08.989 I/ActivityManager(300): Start proc org.kontalk for activity org.kontalk/.ui.ConversationList: pid=1791 uid=10016 gids={3003, 1015}
07-13 11:12:09.429 I/ActivityThread(1791): Pub org.kontalk.messages: org.kontalk.provider.MessagesProvider
07-13 11:12:09.429 I/dalvikvm(1791): Could not find method android.database.sqlite.SQLiteDatabase.beginTransactionNonExclusive, referenced from method org.kontalk.provider.MessagesProvider.beginTransaction
07-13 11:12:09.469 I/ActivityThread(1791): Pub org.kontalk.users: org.kontalk.provider.UsersProvider
07-13 11:12:09.469 I/dalvikvm(1791): Could not find method android.database.sqlite.SQLiteDatabase.beginTransactionNonExclusive, referenced from method org.kontalk.provider.UsersProvider.beginTransaction
07-13 11:12:10.949 I/dalvikvm(1791): Could not find method android.view.Display.getSize, referenced from method org.kontalk.util.Preferences.cacheConversationBackground
07-13 11:12:10.949 D/dalvikvm(1791): VFY: dead code 0x001c-001f in Lorg/kontalk/util/Preferences;.cacheConversationBackground (Landroid/content/Context;Landroid/net/Uri;)Ljava/io/File;
07-13 11:12:12.069 I/ActivityManager(300): Starting: Intent { cmp=org.kontalk/.ui.NumberValidation (has extras) } from pid 1791
07-13 11:12:12.089 W/ActivityManager(300): Unable to start service Intent { act=org.kontalk.action.RELEASE cmp=org.kontalk/.service.msgcenter.MessageCenterService }: not found
07-13 11:12:16.339 I/ActivityManager(300): Displayed org.kontalk/.ui.NumberValidation: +4s249ms (total +7s353ms)
07-13 11:12:23.829 V/KeyPair (1791): key pair generated: org.kontalk.crypto.PersonalKey@40864770
07-13 11:12:23.829 V/NumberValidator(1791): key generation completed org.kontalk.crypto.PersonalKey@40864770
07-13 11:12:23.829 D/MessageCenterService(1791): using server beta.kontalk.net
07-13 11:12:25.239 D/SMACK   (1791): SENT (0): <stream:stream xmlns='jabber:client' to='beta.kontalk.net' xmlns:stream='http://etherx.jabber.org/streams' version='1.0' xml:lang='en'>
07-13 11:12:25.289 D/SMACK   (1791): RECV (0): <?xml version='1.0'?><stream:stream xmlns='jabber:client' xmlns:stream='http://etherx.jabber.org/streams' from='beta.kontalk.net' id='5bc498f4-05cc-4c2b-804a-50edf26377a2' version='1.0' xml:lang='en'>
07-13 11:12:25.339 D/SMACK   (1791): RECV (0): <stream:features><sm xmlns="urn:xmpp:sm:3"/><roster xmlns="http://kontalk.org/extensions/roster"/><ver xmlns="urn:xmpp:features:rosterver"/><register xmlns="http://jabber.org/features/iq-register"/><starttls xmlns="urn:ietf:params:xml:ns:xmpp-tls"/><mechanisms xmlns="urn:ietf:params:xml:ns:xmpp-sasl"><mechanism>KONTALK-TOKEN</mechanism><mechanism>PLAIN</mechanism></mechanisms><compression xmlns="http://jabber.org/features/compress"><method>zlib</method></compression><csi xmlns="urn:xmpp:csi:0"/></stream:features>
07-13 11:12:25.929 D/SMACK   (1791): SENT (0): <stream:stream xmlns='jabber:client' to='beta.kontalk.net' xmlns:stream='http://etherx.jabber.org/streams' version='1.0' xml:lang='en'>
07-13 11:12:26.259 D/SMACK   (1791): RECV (0): <?xml version='1.0'?><stream:stream xmlns='jabber:client' xmlns:stream='http://etherx.jabber.org/streams' from='beta.kontalk.net' id='5bc498f4-05cc-4c2b-804a-50edf26377a2' version='1.0' xml:lang='en'>
07-13 11:12:26.259 D/SMACK   (1791): RECV (0): stream:features><sm xmlns="urn:xmpp:sm:3"/><roster xmlns="http://kontalk.org/extensions/roster"/><ver xmlns="urn:xmpp:features:rosterver"/><register xmlns="http://jabber.org/features/iq-register"/><mechanisms xmlns="urn:ietf:params:xml:ns:xmpp-sasl"><mechanism>KONTALK-TOKEN</mechanism><mechanism>PLAIN</mechanism></mechanisms><compression xmlns="http://jabber.org/features/compress"><method>zlib</method></compression><csi xmlns="urn:xmpp:csi:0"/></stream:features>
07-13 11:12:26.309 D/SMACK   (1791): SENT (0): <iq to='beta.kontalk.net' id='4ozy5-1' type='set'><query xmlns='jabber:iq:register'><x xmlns='jabber:x:data' type='submit'><field var='FORM_TYPE' type='hidden'><value>jabber:iq:register</value></field><field label='Phone number' var='phone' type='text-single'><value>****PHONE****</value></field></x></query></iq>
07-13 11:12:26.359 D/SMACK   (1791): RECV (0): iq type="error" xmlns="jabber:client" id="4ozy5-1" from="beta.kontalk.net"><query xmlns="jabber:iq:register"><x type="submit" xmlns="jabber:x:data"><field type="hidden" var="FORM_TYPE"><value>jabber:iq:register</value></field><field type="text-single" var="phone" label="Phone number"><value>****PHONE****</value></field></x></query><error code="409" type="modify"><conflict xmlns="urn:ietf:params:xml:ns:xmpp-stanzas"/><text xml:lang="en" xmlns="urn:ietf:params:xml:ns:xmpp-stanzas">Another user is registered with the same id.</text></error></iq>
07-13 11:12:28.039 D/MessageCenterService(1791): using server beta.kontalk.net
07-13 11:12:28.309 D/SMACK   (1791): SENT (1): <stream:stream xmlns='jabber:client' to='beta.kontalk.net' xmlns:stream='http://etherx.jabber.org/streams' version='1.0' xml:lang='en'>
07-13 11:12:28.359 D/SMACK   (1791): RECV (1): <?xml version='1.0'?><stream:stream xmlns='jabber:client' xmlns:stream='http://etherx.jabber.org/streams' from='beta.kontalk.net' id='3e4e2592-0e66-46d8-958e-fa517a49a9b5' version='1.0' xml:lang='en'>
07-13 11:12:28.409 D/SMACK   (1791): RECV (1): <stream:features><sm xmlns="urn:xmpp:sm:3"/><roster xmlns="http://kontalk.org/extensions/roster"/><ver xmlns="urn:xmpp:features:rosterver"/><register xmlns="http://jabber.org/features/iq-register"/><starttls xmlns="urn:ietf:params:xml:ns:xmpp-tls"/><mechanisms xmlns="urn:ietf:params:xml:ns:xmpp-sasl"><mechanism>KONTALK-TOKEN</mechanism><mechanism>PLAIN</mechanism></mechanisms><compression xmlns="http://jabber.org/features/compress"><method>zlib</method></compression><csi xmlns="urn:xmpp:csi:0"/></stream:features>
07-13 11:12:29.039 D/SMACK   (1791): SENT (1): <stream:stream xmlns='jabber:client' to='beta.kontalk.net' xmlns:stream='http://etherx.jabber.org/streams' version='1.0' xml:lang='en'>
07-13 11:12:29.299 D/SMACK   (1791): RECV (1): <?xml version='1.0'?><stream:stream xmlns='jabber:client' xmlns:stream='http://etherx.jabber.org/streams' from='beta.kontalk.net' id='3e4e2592-0e66-46d8-958e-fa517a49a9b5' version='1.0' xml:lang='en'>
07-13 11:12:29.299 D/SMACK   (1791): RECV (1): stream:features><sm xmlns="urn:xmpp:sm:3"/><roster xmlns="http://kontalk.org/extensions/roster"/><ver xmlns="urn:xmpp:features:rosterver"/><register xmlns="http://jabber.org/features/iq-register"/><mechanisms xmlns="urn:ietf:params:xml:ns:xmpp-sasl"><mechanism>KONTALK-TOKEN</mechanism><mechanism>PLAIN</mechanism></mechanisms><compression xmlns="http://jabber.org/features/compress"><method>zlib</method></compression><csi xmlns="urn:xmpp:csi:0"/></stream:features>
07-13 11:12:29.349 D/SMACK   (1791): SENT (1): <iq to='beta.kontalk.net' id='4ozy5-5' type='set'><query xmlns='jabber:iq:register'><x xmlns='jabber:x:data' type='submit'><field var='FORM_TYPE' type='hidden'><value>jabber:iq:register</value></field><field label='Phone number' var='phone' type='text-single'><value>****PHONE****</value></field><field label='Phone number' var='force' type='boolean'><value>true</value></field></x></query></iq>
07-13 11:12:29.679 D/SMACK   (1791): RECV (1): iq type="result" xmlns="jabber:client" id="4ozy5-5" from="beta.kontalk.net"><query xmlns="jabber:iq:register"><instructions>A SMS containing a verification code will be sent to the phone number you provided.</instructions><x type="form" xmlns="jabber:x:data"><field type="hidden" var="FORM_TYPE"><value>jabber:iq:register</value></field><field type="text-single" label="SMS sender" var="from"><value>19512282041</value></field></x></query></iq>
07-13 11:12:29.769 I/ActivityManager(300): Starting: Intent { cmp=org.kontalk/.ui.CodeValidation (has extras) } from pid 1791
07-13 11:12:30.119 I/ActivityManager(300): Displayed org.kontalk/.ui.CodeValidation: +298ms
07-13 11:12:45.429 D/MessageCenterService(1791): using server beta.kontalk.net
07-13 11:12:47.039 D/SMACK   (1791): SENT (2): <stream:stream xmlns='jabber:client' to='beta.kontalk.net' xmlns:stream='http://etherx.jabber.org/streams' version='1.0' xml:lang='en'>
07-13 11:12:47.099 D/SMACK   (1791): RECV (2): <?xml version='1.0'?><stream:stream xmlns='jabber:client' xmlns:stream='http://etherx.jabber.org/streams' from='beta.kontalk.net' id='52241ebc-688a-424a-b615-d4b9fbeabb73' version='1.0' xml:lang='en'>
07-13 11:12:47.149 D/SMACK   (1791): RECV (2): <stream:features><sm xmlns="urn:xmpp:sm:3"/><roster xmlns="http://kontalk.org/extensions/roster"/><ver xmlns="urn:xmpp:features:rosterver"/><register xmlns="http://jabber.org/features/iq-register"/><starttls xmlns="urn:ietf:params:xml:ns:xmpp-tls"/><mechanisms xmlns="urn:ietf:params:xml:ns:xmpp-sasl"><mechanism>KONTALK-TOKEN</mechanism><mechanism>PLAIN</mechanism></mechanisms><compression xmlns="http://jabber.org/features/compress"><method>zlib</method></compression><csi xmlns="urn:xmpp:csi:0"/></stream:features>
07-13 11:12:47.519 D/SMACK   (1791): SENT (2): <stream:stream xmlns='jabber:client' to='beta.kontalk.net' xmlns:stream='http://etherx.jabber.org/streams' version='1.0' xml:lang='en'>
07-13 11:12:47.699 D/SMACK   (1791): RECV (2): <?xml version='1.0'?><stream:stream xmlns='jabber:client' xmlns:stream='http://etherx.jabber.org/streams' from='beta.kontalk.net' id='52241ebc-688a-424a-b615-d4b9fbeabb73' version='1.0' xml:lang='en'>
07-13 11:12:47.699 D/SMACK   (1791): RECV (2): stream:features><sm xmlns="urn:xmpp:sm:3"/><roster xmlns="http://kontalk.org/extensions/roster"/><ver xmlns="urn:xmpp:features:rosterver"/><register xmlns="http://jabber.org/features/iq-register"/><mechanisms xmlns="urn:ietf:params:xml:ns:xmpp-sasl"><mechanism>EXTERNAL</mechanism><mechanism>KONTALK-TOKEN</mechanism><mechanism>PLAIN</mechanism></mechanisms><compression xmlns="http://jabber.org/features/compress"><method>zlib</method></compression><csi xmlns="urn:xmpp:csi:0"/></stream:features>
07-13 11:12:47.739 D/SMACK   (1791): SENT (2): <iq to='beta.kontalk.net' id='4ozy5-8' type='set'><query xmlns='jabber:iq:register'><x xmlns='jabber:x:data' type='submit'><field var='FORM_TYPE' type='hidden'><value>http://kontalk.org/protocol/register#code</value></field><field label='Validation code' var='code' type='text-single'><value>965429</value></field></x></query></iq>
```

**Comment by daniele-athome** [comment]
Seems to arrive until code verification. What happens next?

**Comment by TheLastProject** [comment]
Apparently, absolutely nothing. No logs, no Internet activity, nothing. The logs literally end at the point.

**Comment by daniele-athome** [comment]
It's an unexpected error on the server:

```
2015-07-13 09:10:03.779 [kontalk:jabber:iq:register Queue Worker 0]  WorkerThread.run()  SEVERE: tigase.server.xmppsession.SessionManager$ProcessorWorkerThread,(kontalk:jabber:iq:register Queue Worker 0) Exception during packet processing: from=c2s@beta.kontalk.net/178.62.44.19_5999_82.241.196.155_44294, to=sess-man@beta.kontalk.net, DATA=<iq type="set" id="4ozy5-8" xmlns="jabber:client" to="beta.kontalk.net"><query xmlns="jabber:iq:register"><x type="submit" xmlns="jabber:x:data"><field type="hidden" var="FORM_TYPE"><value>http://kontalk.org/protocol/register#code</value></field><field type="text-single" var="code" label="Validation code"><value>965429</value></field></x></query></iq>, SIZE=353, XMLNS=jabber:client, PRIORITY=NORMAL, PERMISSION=NONE, TYPE=set
com.freiheit.gnupg.GnuPGException: 53: Chiave pubblica non utilizzabile
        at com.freiheit.gnupg.GnuPGContext.gpgmeOpImport(Native Method)
        at com.freiheit.gnupg.GnuPGContext.importKey(GnuPGContext.java:700)
        at org.kontalk.xmppserver.KontalkKeyring.importKeyInternal(KontalkKeyring.java:342)
        at org.kontalk.xmppserver.KontalkKeyring.importKey(KontalkKeyring.java:335)
        at org.kontalk.xmppserver.KontalkKeyring.signKey(KontalkKeyring.java:303)
        at org.kontalk.xmppserver.KontalkIqRegister.signPublicKey(KontalkIqRegister.java:518)
        at org.kontalk.xmppserver.KontalkIqRegister.process(KontalkIqRegister.java:247)
        at tigase.server.xmppsession.SessionManager$ProcessorWorkerThread.process(SessionManager.java:2455)
        at tigase.util.WorkerThread.run(WorkerThread.java:128)
```

Android version and device model?

**Comment by TheLastProject** [comment]
Samsung GT-5830 (Galaxy Ace) and Android 2.3.7

**Comment by daniele-athome** [comment]
I had some problems in the past with Android 2.3 with SSL client certificate authentication... it is going to be a problem, however I don't have a SSL/TLS implementation to use instead of the default Java one (does it even exist? Bouncy Castle uses custom APIs, I would need to adapt Smack to that).

**Comment by TheLastProject** [comment]
He registered successfully before when manually entering the beta.kontalk.net server, this time his registration apparently failed because he entered a wrong code. He got called, entered the right code and it worked. He didn't change server in settings this time.

**Comment by daniele-athome** [comment]
Mmm... it didn't seem like that. I had that server error which indicated failure in SSL client certificate exchange... glad it's fixed though. But we'll never know the reason of the error that happened in the first place :-(

**Comment by daniele-athome** [comment]
Thanks for the support @TheLastProject by the way. You should however let him install again from F-Droid since apk signature is different (it won't be able to upgrade from F-Droid if he uses my package).

**Comment by jcsantosx** [comment]
Can't register either.
I receive the calls, input the last 4 digits, but always 'invalid code, can't register'

Have the firewall open on port 5222, but can't connect by telnet using the default server, changed to beta.kontalk.net now can connect, but 'the code is wrong'

I tried also to input with space(' '), the full number, extra last digits(cause they not have always the same length) and have no more stupid ideas.

Android 5.1.1
Any advice? Thanks
