### ISSUE TITLE
Crash on marking user as registered

### ISSUE THREAD

**Issue by daniele-athome** [kontalk/androidclient#512]
Unknown context. Reported on Google Play from an Xperia Tipo running Android 4.0.x.

```
android.database.sqlite.SQLiteConstraintException: error code 19: constraint failed
at android.database.sqlite.SQLiteStatement.native_execute(Native Method)
at android.database.sqlite.SQLiteStatement.executeUpdateDelete(SQLiteStatement.java:92)
at android.database.sqlite.SQLiteDatabase.updateWithOnConflict(SQLiteDatabase.java:1851)
at android.database.sqlite.SQLiteDatabase.update(SQLiteDatabase.java:1802)
at org.kontalk.provider.UsersProvider.updateUser(UsersProvider.java:349)
at org.kontalk.provider.UsersProvider.update(UsersProvider.java:335)
at android.content.ContentProvider$Transport.update(ContentProvider.java:219)
at android.content.ContentResolver.update(ContentResolver.java:856)
at org.kontalk.provider.UsersProvider.markRegistered(UsersProvider.java:720)
at org.kontalk.service.msgcenter.MessageCenterService$8.run(MessageCenterService.java:1986)
at java.lang.Thread.run(Thread.java:856)
```

**Comment by daniele-athome** [comment]
Unable to reproduce. This should be impossible anyway. Closing for now.
