### ISSUE TITLE
Cursor reloading race condition

### ISSUE THREAD

**Issue by daniele-athome** [kontalk/androidclient#523]
Reported by @M4v3r1cK87 while deleting a photo waiting to be sent. It probably happens because data was being modified right before delete happened. We need to make sure to cancel the previous reloading someway (how do we stop Android relayout?)

```
FATAL EXCEPTION: main
Process: org.kontalk, PID: 24459
java.lang.IllegalStateException: Couldn't read row 1842, col 0 from CursorWindow.  Make sure the Cursor is initialized correctly before accessing data from it.
    at android.database.CursorWindow.nativeGetLong(Native Method)
    at android.database.CursorWindow.getLong(CursorWindow.java:511)
    at android.database.AbstractWindowedCursor.getLong(AbstractWindowedCursor.java:75)
    at android.database.AbstractCursor.moveToPosition(AbstractCursor.java:220)
    at android.database.CursorWrapper.moveToPosition(CursorWrapper.java:162)
    at android.widget.CursorAdapter.getItemId(CursorAdapter.java:223)
    at android.widget.AbsListView$RecycleBin.retrieveFromScrap(AbsListView.java:6778)
    at android.widget.AbsListView$RecycleBin.getScrapView(AbsListView.java:6517)
    at android.widget.AbsListView.obtainView(AbsListView.java:2346)
    at android.widget.ListView.makeAndAddView(ListView.java:1864)
    at android.widget.ListView.fillUp(ListView.java:732)
    at android.widget.ListView.layoutChildren(ListView.java:1654)
    at android.widget.AbsListView.onLayout(AbsListView.java:2151)
    at android.view.View.layout(View.java:15689)
    at android.view.ViewGroup.layout(ViewGroup.java:5040)
    at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1703)
    at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1557)
    at android.widget.LinearLayout.onLayout(LinearLayout.java:1466)
    at android.view.View.layout(View.java:15689)
    at android.view.ViewGroup.layout(ViewGroup.java:5040)
    at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
    at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
    at android.view.View.layout(View.java:15689)
    at android.view.ViewGroup.layout(ViewGroup.java:5040)
    at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
    at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
    at android.view.View.layout(View.java:15689)
    at android.view.ViewGroup.layout(ViewGroup.java:5040)
    at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
    at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
    at android.view.View.layout(View.java:15689)
    at android.view.ViewGroup.layout(ViewGroup.java:5040)
    at com.android.internal.widget.ActionBarOverlayLayout.onLayout(ActionBarOverlayLayout.java:494)
    at android.view.View.layout(View.java:15689)
    at android.view.ViewGroup.layout(ViewGroup.java:5040)
    at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
    at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
    at android.view.View.layout(View.java:15689)
    at android.view.ViewGroup.layout(ViewGroup.java:5040)
    at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2116)
    at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1873)
    at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1084)
    at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5990)
    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:767)
    at android.view.Choreographer.doCallbacks(Choreographer.java:580)
    at android.view.Choreographer.doFrame(Choreographer.java:550)
    at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:753)
    at android.os.Handler.handleCallback(Handler.java:739)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at android.os.Looper.loop(Looper.java:135)
    at android.app.ActivityThread.main(ActivityThread.java:5343)
    at java.lang.reflect.Method.invoke(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:372)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:905)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:700)
```

**Comment by daniele-athome** [comment]
This is nasty. And **very** hard to reproduce. Closing it for now until I'll have some other basis for further analysis.
