### ISSUE TITLE
SMS  authentification

### ISSUE THREAD

**Issue by realdmitchell** [kontalk/androidclient#546]
typed my mobile number but I get no SMS. Please help!

**Comment by TheLastProject** [comment]
@realdmitchell Are you using Kontalk 3.0.4 or 3.1-beta2?

I kinda have a similar issue, logs looking like this (stuck on requesting registration forever):
```
D/NumberValidation( 2802): phone number checked, sending validation request
D/MessageCenterService( 2802): using server kontalk.halifax.rwth-aachen.de|kontalk.halifax.rwth-aachen.de:5222
W/NumberValidator( 2802): connection error - trying next server in list
W/NumberValidator( 2802): org.jivesoftware.smack.SmackException$ConnectionException: The following addresses failed: 'kontalk.halifax.rwth-aachen.de:5222' failed because java.net.ConnectException: failed to connect to kontalk.halifax.rwth-aachen.de/137.226.111.112 (port 5222) after 30000ms: isConnected failed: ECONNREFUSED (Connection refused)
W/NumberValidator( 2802):       at org.jivesoftware.smack.tcp.XMPPTCPConnection.connectUsingConfiguration(XMPPTCPConnection.java:596)
W/NumberValidator( 2802):       at org.jivesoftware.smack.tcp.XMPPTCPConnection.connectInternal(XMPPTCPConnection.java:830)
W/NumberValidator( 2802):       at org.jivesoftware.smack.AbstractXMPPConnection.connect(AbstractXMPPConnection.java:365)
W/NumberValidator( 2802):       at org.kontalk.service.XMPPConnectionHelper.connectOnce(XMPPConnectionHelper.java:195)
W/NumberValidator( 2802):       at org.kontalk.service.XMPPConnectionHelper.connectOnce(XMPPConnectionHelper.java:144)
W/NumberValidator( 2802):       at org.kontalk.client.NumberValidator.initConnection(NumberValidator.java:501)
W/NumberValidator( 2802):       at org.kontalk.client.NumberValidator.run(NumberValidator.java:224)
W/NumberValidator( 2802):       at java.lang.Thread.run(Thread.java:818)
D/MessageCenterService( 2802): using server beta.kontalk.net
W/AbstractXMPPConnection( 2802): Connection closed with error
W/AbstractXMPPConnection( 2802): javax.net.ssl.SSLException: Read error: ssl=0xa46b8e00: I/O error during system call, Connection timed out
W/AbstractXMPPConnection( 2802):        at com.android.org.conscrypt.NativeCrypto.SSL_read(Native Method)
W/AbstractXMPPConnection( 2802):        at com.android.org.conscrypt.OpenSSLSocketImpl$SSLInputStream.read(OpenSSLSocketImpl.java:699)
W/AbstractXMPPConnection( 2802):        at java.io.InputStreamReader.read(InputStreamReader.java:231)
W/AbstractXMPPConnection( 2802):        at java.io.BufferedReader.read(BufferedReader.java:325)
W/AbstractXMPPConnection( 2802):        at org.kxml2.io.KXmlParser.fillBuffer(KXmlParser.java:1515)
W/AbstractXMPPConnection( 2802):        at org.kxml2.io.KXmlParser.peekType(KXmlParser.java:992)
W/AbstractXMPPConnection( 2802):        at org.kxml2.io.KXmlParser.next(KXmlParser.java:349)
W/AbstractXMPPConnection( 2802):        at org.kxml2.io.KXmlParser.next(KXmlParser.java:313)
W/AbstractXMPPConnection( 2802):        at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader.parsePackets(XMPPTCPConnection.java:1155)
W/AbstractXMPPConnection( 2802):        at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader.access$200(XMPPTCPConnection.java:935)
W/AbstractXMPPConnection( 2802):        at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader$1.run(XMPPTCPConnection.java:950)
W/AbstractXMPPConnection( 2802):        at java.lang.Thread.run(Thread.java:818)
```

Or like this (registration failed, try again later error):
```
D/NumberValidation( 8501): phone number checked, sending validation request
D/MessageCenterService( 8501): using server network@beta.kontalk.net|kontalk.halifax.rwth-aachen.de:5222
W/NumberValidator( 8501): connection error - trying next server in list
W/NumberValidator( 8501): org.jivesoftware.smack.SmackException$ConnectionException: The following addresses failed: 'kontalk.halifax.rwth-aachen.de:5222' failed because java.net.ConnectException: failed to connect to kontalk.halifax.rwth-aachen.de/137.226.111.112 (port 5222) after 30000ms: isConnected failed: ECONNREFUSED (Connection refused)
W/NumberValidator( 8501):       at org.jivesoftware.smack.tcp.XMPPTCPConnection.connectUsingConfiguration(XMPPTCPConnection.java:596)
W/NumberValidator( 8501):       at org.jivesoftware.smack.tcp.XMPPTCPConnection.connectInternal(XMPPTCPConnection.java:830)
W/NumberValidator( 8501):       at org.jivesoftware.smack.AbstractXMPPConnection.connect(AbstractXMPPConnection.java:365)
W/NumberValidator( 8501):       at org.kontalk.service.XMPPConnectionHelper.connectOnce(XMPPConnectionHelper.java:195)
W/NumberValidator( 8501):       at org.kontalk.service.XMPPConnectionHelper.connectOnce(XMPPConnectionHelper.java:144)
W/NumberValidator( 8501):       at org.kontalk.client.NumberValidator.initConnection(NumberValidator.java:501)
W/NumberValidator( 8501):       at org.kontalk.client.NumberValidator.run(NumberValidator.java:224)
W/NumberValidator( 8501):       at java.lang.Thread.run(Thread.java:818)
D/MessageCenterService( 8501): using server network@beta.kontalk.net|beta.kontalk.net:5222
W/art     ( 8501): Long monitor contention event with owner method=int java.lang.System.identityHashCode!(java.lang.Object) from System.java:4294967294 waiters=0 for 14.957s
W/AbstractXMPPConnection( 8501): Connection closed with error
W/AbstractXMPPConnection( 8501): org.jivesoftware.smack.XMPPException$StreamErrorException: host-unknown You can read more about the meaning of this stream error at http://xmpp.org/rfcs/rfc6120.html#streams-error-conditions
W/AbstractXMPPConnection( 8501): <stream:error><host-unknown xmlns='urn:ietf:params:xml:ns:xmpp-streams'/></stream:error>
W/AbstractXMPPConnection( 8501):        at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader.parsePackets(XMPPTCPConnection.java:994)
W/AbstractXMPPConnection( 8501):        at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader.access$200(XMPPTCPConnection.java:935)
W/AbstractXMPPConnection( 8501):        at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader$1.run(XMPPTCPConnection.java:950)
W/AbstractXMPPConnection( 8501):        at java.lang.Thread.run(Thread.java:818)
E/NumberValidation( 8501): validation error.
E/NumberValidation( 8501): org.jivesoftware.smack.SmackException$NoResponseException: No response received within reply timeout. Timeout was 15000ms (~15s). Used filter: No filter used or filter was 'null'.
E/NumberValidation( 8501):      at org.jivesoftware.smack.SynchronizationPoint.checkForResponse(SynchronizationPoint.java:253)
E/NumberValidation( 8501):      at org.jivesoftware.smack.SynchronizationPoint.checkIfSuccessOrWait(SynchronizationPoint.java:146)
E/NumberValidation( 8501):      at org.jivesoftware.smack.SynchronizationPoint.checkIfSuccessOrWaitOrThrow(SynchronizationPoint.java:125)
E/NumberValidation( 8501):      at org.jivesoftware.smack.tcp.XMPPTCPConnection.connectInternal(XMPPTCPConnection.java:837)
E/NumberValidation( 8501):      at org.jivesoftware.smack.AbstractXMPPConnection.connect(AbstractXMPPConnection.java:365)
E/NumberValidation( 8501):      at org.kontalk.service.XMPPConnectionHelper.connectOnce(XMPPConnectionHelper.java:195)
E/NumberValidation( 8501):      at org.kontalk.service.XMPPConnectionHelper.connectOnce(XMPPConnectionHelper.java:144)
E/NumberValidation( 8501):      at org.kontalk.client.NumberValidator.initConnection(NumberValidator.java:501)
E/NumberValidation( 8501):      at org.kontalk.client.NumberValidator.run(NumberValidator.java:224)
E/NumberValidation( 8501):      at org.kontalk.client.NumberValidator.run(NumberValidator.java:233)
E/NumberValidation( 8501):      at java.lang.Thread.run(Thread.java:818)
W/NumberValidator( 8501): shutting down
W/NumberValidator( 8501): exiting
```

**Comment by duff-y** [comment]
Same here, I deleted my account and wanted to set up a new one with a different name. Now I am stuck with retrieving the verification sms.

**Comment by daniele-athome** [comment]
I'm looking over this, be back in a moment.

**Comment by daniele-athome** [comment]
Ok it's fixed folks. Can you try again? Sorry for the inconvenience.

**Comment by duff-y** [comment]
I tried it again, it looks promising, but I cannot answer the incoming call, which I am supposed to, right?

**Comment by daniele-athome** [comment]
@duff-y it depends on the instructions on the screen. New missed call based registration was among the new features :-)

**Comment by daniele-athome** [comment]
I understand it might not have been translated correctly (or not at all, it depends on which language), but the point of missed call registration is that you have to input the last 5 digits of the number that will call you.

**Comment by duff-y** [comment]
Holy sh**, am I dumb (: Thanks a lot, I appreciate your help. It worked for me!

**Comment by webratte** [comment]
@daniele-athome In the startscreen (bevore regisrated) there is the text:

"Please enter your name, select your country code and input your mobile phone number. A SMS with a verification code will be sent to you. Your phone number will be used once and then discarded."

In the next step you start with "missed call".
This may confuse users because they expect a SMS..

**Comment by daniele-athome** [comment]
You're right, my mistake. I'll fix it right away.
