### ISSUE TITLE
Crash on requesting persistable uri

### ISSUE THREAD

**Issue by daniele-athome** [kontalk/androidclient#582]
Reported on Google Play. Android 5.0.

```
java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=65538, result=-1, data=Intent { act=android.intent.action.VIEW dat=file:///storage/emulated/0/DCIM/Camera/IMG_20151013_152813.jpg }} to activity {org.kontalk/org.kontalk.ui.ComposeMessage}: java.lang.SecurityException: No persistable permission grants found for UID 10106 and Uri 0 @ file:///storage/emulated/0/DCIM/Camera/IMG_20151013_152813.jpg
	at android.app.ActivityThread.deliverResults(ActivityThread.java:3743)
	at android.app.ActivityThread.handleSendResult(ActivityThread.java:3786)
	at android.app.ActivityThread.access$1300(ActivityThread.java:167)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1468)
	at android.os.Handler.dispatchMessage(Handler.java:111)
	at android.os.Looper.loop(Looper.java:194)
	at android.app.ActivityThread.main(ActivityThread.java:5546)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:964)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:759)
Caused by: java.lang.SecurityException: No persistable permission grants found for UID 10106 and Uri 0 @ file:///storage/emulated/0/DCIM/Camera/IMG_20151013_152813.jpg
	at android.os.Parcel.readException(Parcel.java:1540)
	at android.os.Parcel.readException(Parcel.java:1493)
	at android.app.ActivityManagerProxy.takePersistableUriPermission(ActivityManagerNative.java:4042)
	at android.content.ContentResolver.takePersistableUriPermission(ContentResolver.java:1707)
	at org.kontalk.util.MediaStorage.requestPersistablePermissions(MediaStorage.java:431)
	at org.kontalk.ui.ComposeMessageFragment.onActivityResult(ComposeMessageFragment.java:1303)
	at android.support.v4.app.FragmentActivity.onActivityResult(FragmentActivity.java:153)
	at org.kontalk.ui.ComposeMessage.onActivityResult(ComposeMessage.java:297)
	at android.app.Activity.dispatchActivityResult(Activity.java:6179)
	at android.app.ActivityThread.deliverResults(ActivityThread.java:3739)
	... 10 more
```

**Comment by daniele-athome** [comment]
Probably fix (introducing multiple images):
http://stackoverflow.com/questions/25414352/how-to-persist-permission-in-android-api-19-kitkat
