### ISSUE TITLE
BC 1.53.0.0 causes parcel exception

### ISSUE THREAD

**Issue by daniele-athome** [kontalk/androidclient#584]
```
W / Kontalk  (20485): error creating from parcel
W / Kontalk  (20485): java.lang.IllegalArgumentException: illegal object in getInstance: org.spongycastle.asn1.DLSequence
W / Kontalk  (20485):   at org.spongycastle.asn1.ASN1ObjectIdentifier.getInstance(ASN1ObjectIdentifier.java:53)
W / Kontalk  (20485):   at org.spongycastle.openpgp.operator.jcajce.JcaPGPKeyConverter.getPGPPublicKey(JcaPGPKeyConverter.java:197)
W / Kontalk  (20485):   at org.spongycastle.openpgp.operator.jcajce.JcaPGPKeyConverter.getPGPPublicKey(JcaPGPKeyConverter.java:245)
W / Kontalk  (20485):   at org.kontalk.crypto.PGP.fromParcel(PGP.java:242)
W / Kontalk  (20485):   at org.kontalk.crypto.PersonalKey.<init>(PersonalKey.java:90)
W / Kontalk  (20485):   at org.kontalk.crypto.PersonalKey.<init>(PersonalKey.java:67)
W / Kontalk  (20485):   at org.kontalk.crypto.PersonalKey$1.createFromParcel(PersonalKey.java:463)
W / Kontalk  (20485):   at org.kontalk.crypto.PersonalKey$1.createFromParcel(PersonalKey.java:460)
W / Kontalk  (20485):   at android.os.Parcel.readParcelable(Parcel.java:1992)
W / Kontalk  (20485):   at android.os.Parcel.readValue(Parcel.java:1854)
W / Kontalk  (20485):   at android.os.Parcel.readMapInternal(Parcel.java:2094)
W / Kontalk  (20485):   at android.os.Bundle.unparcel(Bundle.java:223)
W / Kontalk  (20485):   at android.os.Bundle.getParcelable(Bundle.java:1158)
W / Kontalk  (20485):   at android.content.Intent.getParcelableExtra(Intent.java:3951)
W / Kontalk  (20485):   at org.kontalk.ui.AccountAuthenticatorActionBarActivity.onCreate(AccountAuthenticatorActionBarActivity.java:60)
W / Kontalk  (20485):   at org.kontalk.ui.CodeValidation.onCreate(CodeValidation.java:77)
W / Kontalk  (20485):   at android.app.Activity.performCreate(Activity.java:4465)
W / Kontalk  (20485):   at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1049)
W / Kontalk  (20485):   at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:1920)
W / Kontalk  (20485):   at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:1981)
W / Kontalk  (20485):   at android.app.ActivityThread.access$600(ActivityThread.java:123)
W / Kontalk  (20485):   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1147)
W / Kontalk  (20485):   at android.os.Handler.dispatchMessage(Handler.java:99)
W / Kontalk  (20485):   at android.os.Looper.loop(Looper.java:137)
W / Kontalk  (20485):   at android.app.ActivityThread.main(ActivityThread.java:4424)
W / Kontalk  (20485):   at java.lang.reflect.Method.invokeNative(Native Method)
W / Kontalk  (20485):   at java.lang.reflect.Method.invoke(Method.java:511)
W / Kontalk  (20485):   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:784)
W / Kontalk  (20485):   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:551)
W / Kontalk  (20485):   at dalvik.system.NativeStart.main(Native Method)
```

**Comment by daniele-athome** [comment]
Try again with 1.54.0.0 (although I don't think it will make any difference).
