### ISSUE TITLE
Failed to connect to local tigase server (connection refused)

### ISSUE THREAD

**Issue by siuyinjanice** [kontalk/androidclient#613]
Hi support,

I set up a local tigase xmpp server following the wiki https://github.com/kontalk/tigase-extension/wiki/How-to-setup-a-local-server.  It has domain siuyinjanice.ddns.net and the DNS has set SRV records (xmpp-client and xmpp-server).  But when I try to connect it from kontalk android client it connected failed with connection refused error.  Below are log from the client:

12-30 12:13:46.397 E/MessageCenterService(  879): connection error

12-30 12:13:46.397 E/MessageCenterService(  879): org.jivesoftware.smack.SmackException$ConnectionException: The following addresses failed: 'siuyinjanice.ddns.net:5222 prio:10:w:0' failed because java.net.ConnectException: failed to connect to siuyinjanice.ddns.net/210.6.73.9 (port 5222) after 30000ms: isConnected failed: ECONNREFUSED (Connection refused), 'siuyinjanice.ddns.net:5222' failed because java.net.ConnectException: failed to connect to siuyinjanice.ddns.net/210.6.73.9 (port 5222) after 30000ms: isConnected failed: ECONNREFUSED (Connection refused)

12-30 12:13:46.397 E/MessageCenterService(  879): 	at org.jivesoftware.smack.tcp.XMPPTCPConnection.connectUsingConfiguration(XMPPTCPConnection.java:605)

12-30 12:13:46.397 E/MessageCenterService(  879): 	at org.jivesoftware.smack.tcp.XMPPTCPConnection.connectInternal(XMPPTCPConnection.java:839)

12-30 12:13:46.397 E/MessageCenterService(  879): 	at org.jivesoftware.smack.AbstractXMPPConnection.connect(AbstractXMPPConnection.java:365)

12-30 12:13:46.397 E/MessageCenterService(  879): 	at org.kontalk.service.XMPPConnectionHelper.connectOnce(XMPPConnectionHelper.java:195)

12-30 12:13:46.397 E/MessageCenterService(  879): 	at org.kontalk.service.XMPPConnectionHelper.connect(XMPPConnectionHelper.java:254)

12-30 12:13:46.397 E/MessageCenterService(  879): 	at org.kontalk.service.XMPPConnectionHelper.run(XMPPConnectionHelper.java:137)

Could you advise how can I fix this?  Thanks.

**Comment by siuyinjanice** [comment]
This is found that the problem is due to Genymotion's settings.  The problem is now solved.
