### ISSUE TITLE
java.lang.UnsatisfiedLinkError: no gnupg-for-java in java.library.path

### ISSUE THREAD

**Issue by siuyinjanice** [kontalk/androidclient#614]
Hi support,

I hosted a local tigase xmpp server and send request from a Kontalk client.  Connection can be established but there follows by the following error:

2016-01-02 14:22:04.464 [urn:ietf:params:xml:ns:xmpp-sasl Queue Worker 0]  ThreadExceptionHandler.uncaughtException()  SEVERE: Uncaught thread: 

"urn:ietf:params:xml:ns:xmpp-sasl Queue Worker 0" exception
java.lang.UnsatisfiedLinkError: no gnupg-for-java in java.library.path
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1886)
	at java.lang.Runtime.loadLibrary0(Runtime.java:849)
	at java.lang.System.loadLibrary(System.java:1088)
	at com.freiheit.gnupg.GnuPGContext.<clinit>(GnuPGContext.java:42)
	at org.kontalk.xmppserver.KontalkKeyring.<init>(KontalkKeyring.java:69)
	at org.kontalk.xmppserver.KontalkKeyring.getInstance(KontalkKeyring.java:405)
	at org.kontalk.xmppserver.auth.KontalkCertificateCallbackHandler.getKeyring(KontalkCertificateCallbackHandler.java:210)
	at org.kontalk.xmppserver.auth.KontalkCertificateCallbackHandler.verifyPublicKey(KontalkCertificateCallbackHandler.java:155)
	at org.kontalk.xmppserver.auth.KontalkCertificateCallbackHandler.verifyCertificate(KontalkCertificateCallbackHandler.java:137)
	at org.kontalk.xmppserver.auth.KontalkCertificateCallbackHandler.handle(KontalkCertificateCallbackHandler.java:95)
	at tigase.auth.mechanisms.AbstractSasl.handleCallbacks(AbstractSasl.java:56)
	at tigase.auth.mechanisms.SaslEXTERNAL.evaluateResponse(SaslEXTERNAL.java:42)
	at tigase.xmpp.impl.SaslAuth.process(SaslAuth.java:277)
	at tigase.server.xmppsession.SessionManager$ProcessorWorkerThread.process(SessionManager.java:2455)
	at tigase.util.WorkerThread.run(WorkerThread.java:128)

FYI, I did add the java.library.path in tigase.conf as follows:

JAVA_OPTIONS="${GC} ${EX} ${ENC} ${DRV} ${JMX_REMOTE_IP} -server -Xms100M -Xmx200M -XX:PermSize=32m -XX:MaxPermSize=256m -XX:MaxDirectMemorySize=128m -Djava.library.path=~/.m2/repository/org/gnupg/gnupg-for-java/0.2-pre-SNAPSHOT"

Grateful if you can advise how to fix this problem.  Thanks.

**Comment by siuyinjanice** [comment]
The problem is solved when the .so file is renamed to gnupg-for-java.so.

**Comment by daniele-athome** [comment]
It should already have that name. What name did it have on your computer?

**Comment by siuyinjanice** [comment]
gnupg-for-java-0.2-pre-SNAPSHOT.so

**Comment by siuyinjanice** [comment]
It is found that the problem is still not solved actually, even renaming the .so file to gnupg-for-java.so.

Please advise how to solve this problem.  Thanks.

**Comment by daniele-athome** [comment]
Can you log into IRC please? Freenode, #kontalk channel. I want to follow the whole installation procedure and I'm not sure about some things you did.

**Comment by daniele-athome** [comment]
By the way, I've fixed the server setup howto and moved it to the tigase-kontalk repository here: https://github.com/kontalk/tigase-kontalk/blob/master/docs/local-server-howto.md
You can refer to it to check if you missed something in your setup. I will be on IRC for the next hour or so, then I will be back tonight.

**Comment by siuyinjanice** [comment]
I am new to IRC and see nothing when go into the kontalk chat room.  Could you tell how can i log into it?

**Comment by daniele-athome** [comment]
You probably intered the wrong network. Use this interface: https://webchat.freenode.net/

**Comment by siuyinjanice** [comment]
logged into the kontalk channel, can you see my message?

**Comment by siuyinjanice** [comment]
I tried to connect to the server again but still the same error, 
fyi, there's no error when starting the server

**Comment by siuyinjanice** [comment]
good news!! after i removed the -Djava.library.path=~/.m2/repository/org/gnupg/gnupg-for-java/0.2-pre-SNAPSHOT in tigase.conf (i just found that there already -Djava.library.path=jars).  There's no more such error now.  But another error XmppSaslException occured when processing the Sasl request.  Let me put this back to #615 and close this issue.

Thanks Daniele for your time and support.
