### ISSUE TITLE
Unable to export personal key

### ISSUE THREAD

**Issue by ezeenova** [kontalk/androidclient#678]
When trying to export my personal key in order to move it to a different device, I get the error message "Unable to export personal key". The resulting kontalk-keys.zip is faulty (when I try to unzip it on my computer with unzip it says "End-of-central-directory signature not found.").

Relevant system log excerpt:

```
E/dalvikvm(12130): >>>>> org.kontalk [ userId:0 | appId:10028 ]
E/Kontalk (12130): error exporting keys
E/Kontalk (12130): java.lang.NullPointerException: value == null
E/Kontalk (12130): 	at java.util.Hashtable.put(Hashtable.java:362)
E/Kontalk (12130): 	at java.util.Hashtable.putAll(Hashtable.java:425)
E/Kontalk (12130): 	at org.kontalk.crypto.PersonalKeyExporter.save(PersonalKeyExporter.java:118)
E/Kontalk (12130): 	at org.kontalk.authenticator.Authenticator.exportDefaultPersonalKey(Authenticator.java:195)
E/Kontalk (12130): 	at org.kontalk.Kontalk.exportPersonalKey(Kontalk.java:234)
E/Kontalk (12130): 	at org.kontalk.ui.PreferencesFragment.exportPersonalKey(PreferencesFragment.java:597)
E/Kontalk (12130): 	at org.kontalk.ui.PreferencesFragment.onActivityResult(PreferencesFragment.java:513)
E/Kontalk (12130): 	at android.support.v4.app.FragmentActivity.onActivityResult(FragmentActivity.java:176)
E/Kontalk (12130): 	at android.app.Activity.dispatchActivityResult(Activity.java:5650)
E/Kontalk (12130): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:3676)
E/Kontalk (12130): 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:3723)
E/Kontalk (12130): 	at android.app.ActivityThread.access$1400(ActivityThread.java:174)
E/Kontalk (12130): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1355)
E/Kontalk (12130): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/Kontalk (12130): 	at android.os.Looper.loop(Looper.java:146)
E/Kontalk (12130): 	at android.app.ActivityThread.main(ActivityThread.java:5593)
E/Kontalk (12130): 	at java.lang.reflect.Method.invokeNative(Native Method)
E/Kontalk (12130): 	at java.lang.reflect.Method.invoke(Method.java:515)
E/Kontalk (12130): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283)
E/Kontalk (12130): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
E/Kontalk (12130): 	at dalvik.system.NativeStart.main(Native Method)
```

**Comment by daniele-athome** [comment]
Thanks for reporting.
