### ISSUE TITLE
Crash on launch from somewhere

### ISSUE THREAD

**Issue by daniele-athome** [kontalk/androidclient#688]
When receiving an ACTION_VIEW intent. Android 5.0, Galaxy Note 3.

```
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.net.Uri.getScheme()' on a null object reference
	at android.content.ContentResolver.acquireUnstableProvider(ContentResolver.java:1447)
	at android.content.ContentResolver.query(ContentResolver.java:468)
	at android.content.ContentResolver.query(ContentResolver.java:428)
	at org.kontalk.ui.ConversationsActivity.handleIntent(ConversationsActivity.java:247)
	at org.kontalk.ui.ConversationsActivity.onCreate(ConversationsActivity.java:108)
```

**Comment by daniele-athome** [comment]
Unable to reproduce. Moving to next milestone.
