### ISSUE TITLE
Crash on contacts list resume

### ISSUE THREAD

**Issue by daniele-athome** [kontalk/androidclient#696]
Android 4.1.2, Micromax A111.

```
java.lang.RuntimeException: Unable to resume activity {org.kontalk/org.kontalk.ui.ContactsListActivity}: java.lang.NullPointerException
       at android.app.ActivityThread.performResumeActivity(ActivityThread.java:2583)
       at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:2611)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2097)
       at android.app.ActivityThread.access$600(ActivityThread.java:133)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1203)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:137)
       at android.app.ActivityThread.main(ActivityThread.java:4794)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:511)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:556)
       at dalvik.system.NativeStart.main(NativeStart.java)
Caused by java.lang.NullPointerException
       at android.widget.AlphabetIndexer.getSectionForPosition(AlphabetIndexer.java:256)
       at lb.library.cursor.BasePinnedHeaderCursorListViewAdapter.getSectionForPosition(BasePinnedHeaderCursorListViewAdapter.java:79)
       at android.widget.FastScroller.getThumbPositionForListPosition(FastScroller.java:648)
       at android.widget.FastScroller.onScroll(FastScroller.java:458)
       at android.widget.AbsListView.invokeOnItemScrollListener(AbsListView.java:1327)
       at android.widget.ListView.layoutChildren(ListView.java:1707)
       at android.widget.AbsListView.onLayout(AbsListView.java:2111)
       at lb.library.PinnedHeaderListView.onLayout(PinnedHeaderListView.java:111)
       at android.widget.AdapterView.updateEmptyStatus(AdapterView.java:756)
       at android.widget.AdapterView.checkFocus(AdapterView.java:720)
       at android.widget.AdapterView$AdapterDataSetObserver.onChanged(AdapterView.java:819)
       at android.widget.AbsListView$AdapterDataSetObserver.onChanged(AbsListView.java:6056)
       at android.database.DataSetObservable.notifyChanged(DataSetObservable.java:37)
       at android.widget.BaseAdapter.notifyDataSetChanged(BaseAdapter.java:50)
       at android.widget.CursorAdapter.swapCursor(CursorAdapter.java:341)
       at android.widget.CursorAdapter.changeCursor(CursorAdapter.java:309)
       at lb.library.cursor.SearchablePinnedHeaderCursorListViewAdapter.changeCursor(SearchablePinnedHeaderCursorListViewAdapter.java:25)
       at org.kontalk.ui.adapter.ContactsListAdapter.changeCursor(ContactsListAdapter.java:115)
       at org.kontalk.ui.ContactsListFragment.startQuery(ContactsListFragment.java:267)
       at org.kontalk.ui.ContactsListActivity.onResume(ContactsListActivity.java:81)
       at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1184)
       at android.app.Activity.performResume(Activity.java:5082)
       at android.app.ActivityThread.performResumeActivity(ActivityThread.java:2573)
       at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:2611)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2097)
       at android.app.ActivityThread.access$600(ActivityThread.java:133)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1203)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:137)
       at android.app.ActivityThread.main(ActivityThread.java:4794)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:511)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:556)
       at dalvik.system.NativeStart.main(NativeStart.java)
```

**Comment by daniele-athome** [comment]
Probably related:

```
java.lang.IndexOutOfBoundsException: Invalid index 30, size is 0
       at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)
       at java.util.ArrayList.get(ArrayList.java:308)
       at android.widget.HeaderViewListAdapter.isEnabled(HeaderViewListAdapter.java:164)
       at android.widget.AbsListView.onInitializeAccessibilityNodeInfoForItem(AbsListView.java:2525)
       at android.widget.ListView.onInitializeAccessibilityNodeInfoForItem(ListView.java:3949)
       at android.widget.AbsListView$ListItemAccessibilityDelegate.onInitializeAccessibilityNodeInfo(AbsListView.java:2452)
       at android.view.View.onInitializeAccessibilityNodeInfo(View.java:6088)
       at android.view.View.createAccessibilityNodeInfoInternal(View.java:6049)
       at android.view.View$AccessibilityDelegate.createAccessibilityNodeInfo(View.java:22455)
       at android.view.View.createAccessibilityNodeInfo(View.java:6032)
       at android.view.AccessibilityInteractionController$AccessibilityNodePrefetcher.prefetchDescendantsOfRealNode(AccessibilityInteractionController.java:1020)
       at android.view.AccessibilityInteractionController$AccessibilityNodePrefetcher.prefetchDescendantsOfRealNode(AccessibilityInteractionController.java:1043)
       at android.view.AccessibilityInteractionController$AccessibilityNodePrefetcher.prefetchAccessibilityNodeInfos(AccessibilityInteractionController.java:844)
       at android.view.AccessibilityInteractionController.findAccessibilityNodeInfoByAccessibilityIdUiThread(AccessibilityInteractionController.java:156)
       at android.view.AccessibilityInteractionController.access$400(AccessibilityInteractionController.java:54)
       at android.view.AccessibilityInteractionController$PrivateHandler.handleMessage(AccessibilityInteractionController.java:1191)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:5527)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:730)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:620)
```

Android 6.0 on a LG G3 (D855).

**Comment by daniele-athome** [comment]
Unable to reproduce, even with exotic characters in display names (tested all sort of things on emulator). Closing for now.

**Comment by daniele-athome** [comment]
A few more reported crashes...
