### ISSUE TITLE
Crash when dismissing progress dialog after activity has paused

### ISSUE THREAD

**Issue by daniele-athome** [kontalk/androidclient#698]
Caused by badly handled screen orientation change.

```
java.lang.IllegalArgumentException: View not attached to window manager
       at android.view.WindowManagerImpl.findViewLocked(WindowManagerImpl.java:730)
       at android.view.WindowManagerImpl.removeView(WindowManagerImpl.java:413)
       at android.view.WindowManagerImpl$CompatModeWrapper.removeView(WindowManagerImpl.java:164)
       at android.app.Dialog.dismissDialog(Dialog.java:342)
       at android.app.Dialog.dismiss(Dialog.java:325)
       at com.afollestad.materialdialogs.MaterialDialog.dismiss(MaterialDialog.java:1811)
       at org.kontalk.ui.PreferencesFragment$12$2.updated(PreferencesFragment.java:420)
       at org.kontalk.service.ServerListUpdater.onReceive(ServerListUpdater.java:164)
       at android.support.v4.content.LocalBroadcastManager.executePendingBroadcasts(LocalBroadcastManager.java:297)
       at android.support.v4.content.LocalBroadcastManager.access$000(LocalBroadcastManager.java:46)
       at android.support.v4.content.LocalBroadcastManager$1.handleMessage(LocalBroadcastManager.java:116)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:174)
       at android.app.ActivityThread.main(ActivityThread.java:4952)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:511)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1027)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:794)
       at dalvik.system.NativeStart.main(NativeStart.java)
```

**Comment by daniele-athome** [comment]
Resurfaced.

```
java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.Context android.content.Context.getApplicationContext()' on a null object reference
       at org.kontalk.ui.PreferencesFragment$12$1.updated(PreferencesFragment.java:420)
       at org.kontalk.service.ServerListUpdater.onReceive(ServerListUpdater.java:164)
       at android.support.v4.content.LocalBroadcastManager.executePendingBroadcasts(LocalBroadcastManager.java:297)
       at android.support.v4.content.LocalBroadcastManager.access$000(LocalBroadcastManager.java:46)
       at android.support.v4.content.LocalBroadcastManager$1.handleMessage(LocalBroadcastManager.java:116)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:224)
       at android.app.ActivityThread.main(ActivityThread.java:5526)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```
