### ISSUE TITLE
Out of memory issues

### ISSUE THREAD

**Issue by daniele-athome** [kontalk/androidclient#703]
Happening regularly in emulated Gingerbread (2.3.7) for Bitmap allocations.
Recently reported on Crashlytics on a Odyssey Plus (?) running Android 4.3:

```
java.lang.OutOfMemoryError
       at org.kxml2.io.KXmlParser.<init>(KXmlParser.java:142)
       at java.lang.Class.newInstanceImpl(Class.java)
       at java.lang.Class.newInstance(Class.java:1130)
       at org.xmlpull.v1.XmlPullParserFactory.newInstance(XmlPullParserFactory.java:310)
       at org.xmlpull.v1.XmlPullParserFactory.newInstance(XmlPullParserFactory.java:247)
       at org.jivesoftware.smack.util.PacketParserUtils.newXmppParser(PacketParserUtils.java:174)
       at org.jivesoftware.smack.util.PacketParserUtils.newXmppParser(PacketParserUtils.java:203)
       at org.kontalk.client.XMPPTCPConnection.openStream(XMPPTCPConnection.java:945)
       at org.kontalk.client.XMPPTCPConnection$PacketWriter.writePackets(XMPPTCPConnection.java:1317)
       at org.kontalk.client.XMPPTCPConnection$PacketWriter.access$3200(XMPPTCPConnection.java:1198)
       at org.kontalk.client.XMPPTCPConnection$PacketWriter$1.run(XMPPTCPConnection.java:1236)
       at java.lang.Thread.run(Thread.java:841)
```

Some memory analysis would be nice.

---

I noticed how almost all crashes happen on ldpi devices. Support library has no ldpi resources, so the system is forced to scale down mdpi files. Could this be a major cause for this OOM errors?

**Comment by daniele-athome** [comment]
Alé!!

```
java.lang.OutOfMemoryError
       at java.lang.String.<init>(String.java:255)
       at libcore.io.IoUtils$FileReader.toString(IoUtils.java:272)
       at libcore.io.IoUtils.readFileAsString(IoUtils.java:114)
       at com.android.org.conscrypt.CertPinManager.readPinFile(CertPinManager.java:111)
       at com.android.org.conscrypt.CertPinManager.rebuild(CertPinManager.java:85)
       at com.android.org.conscrypt.CertPinManager.<init>(CertPinManager.java:49)
       at com.android.org.conscrypt.TrustManagerImpl.<init>(TrustManagerImpl.java:143)
       at com.android.org.conscrypt.TrustManagerImpl.<init>(TrustManagerImpl.java:103)
       at com.android.org.conscrypt.TrustManagerFactoryImpl.engineGetTrustManagers(TrustManagerFactoryImpl.java:80)
       at javax.net.ssl.TrustManagerFactory.getTrustManagers(TrustManagerFactory.java:219)
       at org.kontalk.client.KontalkConnection.setupSSL(KontalkConnection.java:174)
       at org.kontalk.client.KontalkConnection.buildConfiguration(KontalkConnection.java:113)
       at org.kontalk.client.KontalkConnection.<init>(KontalkConnection.java:71)
       at org.kontalk.service.XMPPConnectionHelper.connectOnce(XMPPConnectionHelper.java:180)
       at org.kontalk.service.XMPPConnectionHelper.connect(XMPPConnectionHelper.java:254)
       at org.kontalk.service.XMPPConnectionHelper.run(XMPPConnectionHelper.java:137)
```

**Comment by daniele-athome** [comment]
Yeah!

```
java.lang.OutOfMemoryError
       at android.graphics.BitmapFactory.nativeDecodeStream(BitmapFactory.java)
       at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:623)
       at org.kontalk.util.MediaStorage.resizeImage(MediaStorage.java:499)
       at org.kontalk.util.MediaStorage.resizeImage(MediaStorage.java:449)
       at org.kontalk.ui.ComposeMessageFragment.sendBinaryMessage(ComposeMessageFragment.java:731)
       at org.kontalk.ui.ComposeMessageFragment.onActivityResult(ComposeMessageFragment.java:1494)
       at android.support.v4.app.FragmentActivity.onActivityResult(FragmentActivity.java:176)
       at org.kontalk.ui.ComposeMessage.onActivityResult(ComposeMessage.java:299)
       at android.app.Activity.dispatchActivityResult(Activity.java:5515)
       at android.app.ActivityThread.deliverResults(ActivityThread.java:3429)
       at android.app.ActivityThread.handleSendResult(ActivityThread.java:3476)
       at android.app.ActivityThread.access$1200(ActivityThread.java:157)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1337)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:176)
       at android.app.ActivityThread.main(ActivityThread.java:5317)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:511)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1102)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:869)
       at dalvik.system.NativeStart.main(NativeStart.java)
```

**Comment by daniele-athome** [comment]
I'm doing the best I can to reduce memory usage, but until I can have one of the devices that can reproduce the issue, I'm stuck with static memory analysis and risk going into the micro-optimizations loop.
