### ISSUE TITLE
Very unlikely race condition

### ISSUE THREAD

**Issue by daniele-athome** [kontalk/androidclient#704]
This is really bad luck: the inactive message is delivered right when the service is shutting down.

```
java.lang.NullPointerException
       at org.kontalk.service.msgcenter.MessageCenterService.sendPacket(MessageCenterService.java:664)
       at org.kontalk.service.msgcenter.MessageCenterService.sendPacket(MessageCenterService.java:655)
       at org.kontalk.service.msgcenter.MessageCenterService.sendPresence(MessageCenterService.java:1437)
       at org.kontalk.service.msgcenter.MessageCenterService.inactive(MessageCenterService.java:1407)
       at org.kontalk.service.msgcenter.MessageCenterService.access$200(MessageCenterService.java:148)
       at org.kontalk.service.msgcenter.MessageCenterService$IdleConnectionHandler.handleMessage(MessageCenterService.java:440)
       at org.kontalk.service.msgcenter.MessageCenterService$IdleConnectionHandler.handleMessage(MessageCenterService.java:420)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:176)
       at android.os.HandlerThread.run(HandlerThread.java:60)
```

We need a proper synchronization mechanism besides synchronized blocks/methods.

**Comment by daniele-athome** [comment]
Should be fixed in 6a57d0fdb6c4dda5925453b5187657042074ec7e.
