### ISSUE TITLE
SHA1PRNG algorithm not available??

### ISSUE THREAD

**Issue by daniele-athome** [kontalk/androidclient#706]
Unbelievable. Android 4.1.2, HTC Desire X.

```
java.lang.RuntimeException: Unable to create application org.kontalk.Kontalk: java.lang.SecurityException: SHA1PRNG not available
       at android.app.ActivityThread.handleBindApplication(ActivityThread.java)
       at android.app.ActivityThread.access$1300(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java)
       at android.os.Handler.dispatchMessage(Handler.java)
       at android.os.Looper.loop(Looper.java)
       at android.app.ActivityThread.main(ActivityThread.java)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java)
       at dalvik.system.NativeStart.main(NativeStart.java)
Caused by java.lang.SecurityException: SHA1PRNG not available
       at org.kontalk.crypto.PRNGFixes.installLinuxPRNGSecureRandom(PRNGFixes.java:166)
       at org.kontalk.crypto.PRNGFixes.apply(PRNGFixes.java:89)
       at org.kontalk.Kontalk.onCreate(Kontalk.java:115)
       at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java)
       at android.app.ActivityThread.handleBindApplication(ActivityThread.java)
       at android.app.ActivityThread.access$1300(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java)
       at android.os.Handler.dispatchMessage(Handler.java)
       at android.os.Looper.loop(Looper.java)
       at android.app.ActivityThread.main(ActivityThread.java)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java)
       at dalvik.system.NativeStart.main(NativeStart.java)
Caused by java.security.NoSuchAlgorithmException: SecureRandom SHA1PRNG implementation not found
       at org.apache.harmony.security.fortress.Engine.notFound(Engine.java)
       at org.apache.harmony.security.fortress.Engine.getInstance(Engine.java)
       at java.security.SecureRandom.getInstance(SecureRandom.java)
       at org.kontalk.crypto.PRNGFixes.installLinuxPRNGSecureRandom(PRNGFixes.java:164)
       at org.kontalk.crypto.PRNGFixes.apply(PRNGFixes.java:89)
       at org.kontalk.Kontalk.onCreate(Kontalk.java:115)
       at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java)
       at android.app.ActivityThread.handleBindApplication(ActivityThread.java)
       at android.app.ActivityThread.access$1300(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java)
       at android.os.Handler.dispatchMessage(Handler.java)
       at android.os.Looper.loop(Looper.java)
       at android.app.ActivityThread.main(ActivityThread.java)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java)
       at dalvik.system.NativeStart.main(NativeStart.java)
```

**Comment by daniele-athome** [comment]
Another issue has resurfaced:

```
java.lang.SecurityException: SecureRandom.getInstance("SHA1PRNG") backed by wrong Provider: class org.apache.harmony.security.provider.crypto.CryptoProvider
       at org.kontalk.crypto.PRNGFixes.installLinuxPRNGSecureRandom(PRNGFixes.java:170)
       at org.kontalk.crypto.PRNGFixes.apply(PRNGFixes.java:89)
       at org.kontalk.Kontalk.onCreate(Kontalk.java:115)
       at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:999)
       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4244)
       at android.app.ActivityThread.access$1300(ActivityThread.java:137)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1270)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:137)
       at android.app.ActivityThread.main(ActivityThread.java:4838)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:511)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:875)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:642)
       at dalvik.system.NativeStart.main(NativeStart.java)
```
