### ISSUE TITLE
Unable to share pictures from Google Photos

### ISSUE THREAD

**Issue by daniele-athome** [kontalk/androidclient#707]
Something changed in how intents should be processed and of course no warning from Google.

```
looking up mime type for uri content://com.google.android.apps.photos.contentprovider/-1/1/file%3A%2F%2F%2Fstorage%2Femulated%2F0%2FPictures%2FKontalk%2FIMG_20160501_162247425.png/ORIGINAL/NONE/1843605577
using detected mime type image/jpeg
sending binary content: content://com.google.android.apps.photos.contentprovider/-1/1/file%3A%2F%2F%2Fstorage%2Femulated%2F0%2FPictures%2FKontalk%2FIMG_20160501_162247425.png/ORIGINAL/NONE/1843605577
unable to store media
java.io.FileNotFoundException: File not found: null
	at android.database.DatabaseUtils.readExceptionWithFileNotFoundExceptionFromParcel(DatabaseUtils.java:144)
	at android.content.ContentProviderProxy.openTypedAssetFile(ContentProviderNative.java:692)
	at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:1103)
	at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:942)
	at android.content.ContentResolver.openInputStream(ContentResolver.java:662)
	at org.kontalk.util.MediaStorage.cacheThumbnail(MediaStorage.java:146)
	at org.kontalk.util.MediaStorage.cacheThumbnail(MediaStorage.java:140)
	at org.kontalk.util.MediaStorage.cacheThumbnail(MediaStorage.java:133)
	at org.kontalk.ui.ComposeMessageFragment.sendBinaryMessage(ComposeMessageFragment.java:726)
	at org.kontalk.ui.ComposeMessage.sendMedia(ComposeMessage.java:358)
	at org.kontalk.ui.ComposeMessage.processSendIntent(ComposeMessage.java:406)
	at org.kontalk.ui.ComposeMessage.onActivityResult(ComposeMessage.java:284)
	at android.app.Activity.dispatchActivityResult(Activity.java:6442)
	at android.app.ActivityThread.deliverResults(ActivityThread.java:3716)
	at android.app.ActivityThread.handleSendResult(ActivityThread.java:3763)
	at android.app.ActivityThread.-wrap16(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1403)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:5443)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)
```

**Comment by daniele-athome** [comment]
Very dirty workaround: https://github.com/nostra13/Android-Universal-Image-Loader/pull/1074 (yeaahh!!!)

**Comment by daniele-athome** [comment]
Not occuring anymore, probably fixed by Google updates.
