### ISSUE TITLE
Invalid signature on get resource from classpath

### ISSUE THREAD

**Issue by daniele-athome** [kontalk/androidclient#716]
It might been have caused by the Google Play security provider (I can't find a way to explain it though, it's closed source so who knows what the hell they are doing). Investigate.

```
java.lang.ExceptionInInitializerError
       at org.jivesoftware.smack.SmackConfiguration.getVersion(SmackConfiguration.java:96)
       at org.jivesoftware.smack.provider.ProviderManager.<clinit>(ProviderManager.java:121)
       at org.kontalk.client.SmackInitializer.initialize(SmackInitializer.java:51)
       at org.kontalk.service.msgcenter.MessageCenterService.configure(MessageCenterService.java:678)
       at org.kontalk.service.msgcenter.MessageCenterService.onCreate(MessageCenterService.java:602)
       at android.app.ActivityThread.handleCreateService(ActivityThread.java:2775)
       at android.app.ActivityThread.access$1800(ActivityThread.java:145)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1406)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:135)
       at android.app.ActivityThread.main(ActivityThread.java:5319)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1016)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:811)
Caused by java.lang.IllegalStateException: java.lang.SecurityException: Incorrect signature
       at org.jivesoftware.smack.SmackInitialization.<clinit>(SmackInitialization.java:112)
       at org.jivesoftware.smack.SmackConfiguration.getVersion(SmackConfiguration.java:96)
       at org.jivesoftware.smack.provider.ProviderManager.<clinit>(ProviderManager.java:121)
       at org.kontalk.client.SmackInitializer.initialize(SmackInitializer.java:51)
       at org.kontalk.service.msgcenter.MessageCenterService.configure(MessageCenterService.java:678)
       at org.kontalk.service.msgcenter.MessageCenterService.onCreate(MessageCenterService.java:602)
       at android.app.ActivityThread.handleCreateService(ActivityThread.java:2775)
       at android.app.ActivityThread.access$1800(ActivityThread.java:145)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1406)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:135)
       at android.app.ActivityThread.main(ActivityThread.java:5319)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1016)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:811)
Caused by java.lang.SecurityException: Incorrect signature
       at org.apache.harmony.security.utils.JarUtils.verifySignature(JarUtils.java:223)
       at java.util.jar.JarVerifier.verifyCertificate(JarVerifier.java:294)
       at java.util.jar.JarVerifier.readCertificates(JarVerifier.java:268)
       at java.util.jar.JarFile.getInputStream(JarFile.java:380)
       at libcore.net.url.JarURLConnectionImpl.getInputStream(JarURLConnectionImpl.java:222)
       at java.net.URL.openStream(URL.java:470)
       at java.lang.ClassLoader.getResourceAsStream(ClassLoader.java:444)
       at org.jivesoftware.smack.util.FileUtils.getStreamForUrl(FileUtils.java:54)
       at org.jivesoftware.smack.SmackInitialization.<clinit>(SmackInitialization.java:109)
       at org.jivesoftware.smack.SmackConfiguration.getVersion(SmackConfiguration.java:96)
       at org.jivesoftware.smack.provider.ProviderManager.<clinit>(ProviderManager.java:121)
       at org.kontalk.client.SmackInitializer.initialize(SmackInitializer.java:51)
       at org.kontalk.service.msgcenter.MessageCenterService.configure(MessageCenterService.java:678)
       at org.kontalk.service.msgcenter.MessageCenterService.onCreate(MessageCenterService.java:602)
       at android.app.ActivityThread.handleCreateService(ActivityThread.java:2775)
       at android.app.ActivityThread.access$1800(ActivityThread.java:145)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1406)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:135)
       at android.app.ActivityThread.main(ActivityThread.java:5319)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1016)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:811)
```

**Comment by daniele-athome** [comment]
https://code.google.com/p/android/issues/detail?id=68562
