### ISSUE TITLE
Blocking while offline throws IllegalStateException

### ISSUE THREAD

**Issue by abika** [kontalk/androidclient#723]
Don't want to be annoying but in a special cases blocking a contact results in an app crash:
To reproduce:
* go offline
* open a chat and block the user
* go back to conversation list and go online again
* wait some seconds... bamm!
```
java.lang.IllegalStateException: Fragment ComposeMessageFragment{a5744348} not attached to Activity
    at android.support.v4.app.Fragment.getResources(Fragment.java:636)
    at android.support.v4.app.Fragment.getText(Fragment.java:648)
    at org.kontalk.ui.ComposeMessageFragment.updateUI(ComposeMessageFragment.java:2732)
    at org.kontalk.ui.ComposeMessageFragment.access$2200(ComposeMessageFragment.java:150)
    at org.kontalk.ui.ComposeMessageFragment$22.onReceive(ComposeMessageFragment.java:1903)
    at android.support.v4.content.LocalBroadcastManager.executePendingBroadcasts(LocalBroadcastManager.java:297)
    at android.support.v4.content.LocalBroadcastManager.access$000(LocalBroadcastManager.java:46)
    at android.support.v4.content.LocalBroadcastManager$1.handleMessage(LocalBroadcastManager.java:116)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:136)
    at android.app.ActivityThread.main(ActivityThread.java:5001)
    at java.lang.reflect.Method.invokeNative(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:515)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
    at dalvik.system.NativeStart.main(Native Method)
```

(and if this is caught the next NPE is thrown by `Toast.makeText()`)

I get the problem: the broadcast receiver gets the intent after the ui view was already changed, i.e. the fragment isn't added to the activity anymore.
But what is the best solution? Quickfix is
```
        if (mPrivacyListener != null) {
            mLocalBroadcastManager.unregisterReceiver(mPrivacyListener);
            mPrivacyListener = null;
        }
```
in `onPause()`. But when going online and immediately going back to the conversation the view is not updated.

**Comment by daniele-athome** [comment]
Never annoying if you report a bug :-) thanks! I'll look into it.

**Comment by daniele-athome** [comment]
Since it's not a blocker issue and I'd like to refactor this part, I want to merge group chat first and fix it there.
