### ISSUE TITLE
Search view is null

### ISSUE THREAD

**Issue by daniele-athome** [kontalk/androidclient#735]
This shouldn't happen. Android 4.1.2 on a JYT JY G3.

```
java.lang.NullPointerException
       at org.kontalk.ui.ConversationsActivity.onCreateOptionsMenu(ConversationsActivity.java:318)
       at android.app.Activity.onCreatePanelMenu(Activity.java:2488)
       at android.support.v4.app.FragmentActivity.onCreatePanelMenu(FragmentActivity.java:341)
       at android.support.v7.view.WindowCallbackWrapper.onCreatePanelMenu(WindowCallbackWrapper.java:85)
       at android.support.v7.app.AppCompatDelegateImplBase$AppCompatWindowCallbackBase.onCreatePanelMenu(AppCompatDelegateImplBase.java:258)
       at android.support.v7.view.WindowCallbackWrapper.onCreatePanelMenu(WindowCallbackWrapper.java:85)
       at android.support.v7.app.ToolbarActionBar.populateOptionsMenu(ToolbarActionBar.java:454)
       at android.support.v7.app.ToolbarActionBar$1.run(ToolbarActionBar.java:61)
       at android.os.Handler.handleCallback(Handler.java:615)
       at android.os.Handler.dispatchMessage(Handler.java:92)
       at android.os.Looper.loop(Looper.java:153)
       at android.app.ActivityThread.main(ActivityThread.java:4987)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:511)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:821)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:584)
       at dalvik.system.NativeStart.main(NativeStart.java)
```

**Comment by daniele-athome** [comment]
Unable to reproduce and no relevant info anywhere. Closing for now.
