### ISSUE TITLE
Handle missing document app

### ISSUE THREAD

**Issue by daniele-athome** [kontalk/androidclient#740]
```
android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.CREATE_DOCUMENT cat=[android.intent.category.OPENABLE] typ=application/zip (has extras) }
       at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1665)
       at android.app.Instrumentation.execStartActivity(Instrumentation.java:1457)
       at android.app.Activity.startActivityForResult(Activity.java:3474)
       at android.support.v4.app.ActivityCompatJB.startActivityForResult(ActivityCompatJB.java:30)
       at android.support.v4.app.ActivityCompat.startActivityForResult(ActivityCompat.java:162)
       at android.support.v4.app.FragmentActivity.startActivityFromFragment(FragmentActivity.java:922)
       at android.support.v4.app.FragmentActivity$HostCallbacks.onStartActivityFromFragment(FragmentActivity.java:1010)
       at android.support.v4.app.Fragment.startActivityForResult(Fragment.java:940)
       at android.support.v4.app.Fragment.startActivityForResult(Fragment.java:929)
       at org.kontalk.util.MediaStorage.createFile(MediaStorage.java:606)
       at org.kontalk.ui.prefs.MaintenanceFragment$4$1.onPassphraseChanged(MaintenanceFragment.java:155)
       at org.kontalk.ui.prefs.MaintenanceFragment$4$2.onValidPassphrase(MaintenanceFragment.java:180)
       at org.kontalk.ui.prefs.MaintenanceFragment$6.onInput(MaintenanceFragment.java:268)
       at com.afollestad.materialdialogs.MaterialDialog.onClick(MaterialDialog.java:342)
       at android.view.View.performClick(View.java:4445)
       at android.view.View$PerformClick.run(View.java:18446)
       at android.os.Handler.handleCallback(Handler.java:733)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:136)
       at android.app.ActivityThread.main(ActivityThread.java:5147)
       at java.lang.reflect.Method.invokeNative(NativeMethod)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:795)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:611)
```

**Comment by daniele-athome** [comment]
Fixed in #780.
