### ISSUE TITLE
NullPointerException at org.kontalk.ui.view.ComposerBar.doSetSendEnabled(ComposerBar.java:374)

### ISSUE THREAD

**Issue by relan** [kontalk/androidclient#746]
NPE happens every time when ConversationsActivity is started (I'm on the latest master, basic flavor). Android 4.2.1 MIPS emulator:

```
E/AndroidRuntime( 1200): java.lang.RuntimeException: Unable to start activity ComponentInfo{org.kontalk.debug/org.kontalk.ui.ComposeMessage}: java.lang.NullPointerException
E/AndroidRuntime( 1200): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2180)
E/AndroidRuntime( 1200): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2230)
E/AndroidRuntime( 1200): 	at android.app.ActivityThread.access$600(ActivityThread.java:141)
E/AndroidRuntime( 1200): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1234)
E/AndroidRuntime( 1200): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime( 1200): 	at android.os.Looper.loop(Looper.java:137)
E/AndroidRuntime( 1200): 	at android.app.ActivityThread.main(ActivityThread.java:5039)
E/AndroidRuntime( 1200): 	at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime( 1200): 	at java.lang.reflect.Method.invoke(Method.java:511)
E/AndroidRuntime( 1200): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
E/AndroidRuntime( 1200): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560)
E/AndroidRuntime( 1200): 	at dalvik.system.NativeStart.main(Native Method)
E/AndroidRuntime( 1200): Caused by: java.lang.NullPointerException
E/AndroidRuntime( 1200): 	at org.kontalk.ui.view.ComposerBar.doSetSendEnabled(ComposerBar.java:374)
E/AndroidRuntime( 1200): 	at org.kontalk.ui.view.ComposerBar.onFinishInflate(ComposerBar.java:358)
E/AndroidRuntime( 1200): 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:754)
E/AndroidRuntime( 1200): 	at android.view.LayoutInflater.parseInclude(LayoutInflater.java:830)
E/AndroidRuntime( 1200): 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:736)
E/AndroidRuntime( 1200): 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:749)
E/AndroidRuntime( 1200): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:489)
E/AndroidRuntime( 1200): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:396)
E/AndroidRuntime( 1200): 	at org.kontalk.ui.AbstractComposeFragment.onCreateView(AbstractComposeFragment.java:308)
E/AndroidRuntime( 1200): 	at android.support.v4.app.Fragment.performCreateView(Fragment.java:1974)
E/AndroidRuntime( 1200): 	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1067)
E/AndroidRuntime( 1200): 	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1252)
E/AndroidRuntime( 1200): 	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1234)
E/AndroidRuntime( 1200): 	at android.support.v4.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:2046)
E/AndroidRuntime( 1200): 	at android.support.v4.app.FragmentController.dispatchActivityCreated(FragmentController.java:174)
E/AndroidRuntime( 1200): 	at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:597)
E/AndroidRuntime( 1200): 	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1164)
E/AndroidRuntime( 1200): 	at android.app.Activity.performStart(Activity.java:5114)
E/AndroidRuntime( 1200): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2153)
E/AndroidRuntime( 1200): 	... 11 more
W/ActivityManager(  262):   Force finishing activity org.kontalk.debug/org.kontalk.ui.ComposeMessage
W/ActivityManager(  262):   Force finishing activity org.kontalk.debug/org.kontalk.ui.ConversationsActivity
```

This is a regression introduced by this commit:

```
commit bc88c34f8cba76b2a8b371a3cf79d894ab08e2d0
Author: Daniele Ricci <daniele.athome@gmail.com>
Date:   Sun May 22 21:53:45 2016 +0200

    Disable send on solo groups
    
    Signed-off-by: Daniele Ricci <daniele.athome@gmail.com>
```

**Comment by daniele-athome** [comment]
I forgot to check against null for mAudioButton (which is null when audio is not supported on the device). Thanks for reporting!
