### ISSUE TITLE
Handle wrong roster response from rogue server

### ISSUE THREAD

**Issue by daniele-athome** [kontalk/androidclient#759]
Oooook....

```
java.lang.AssertionError: impossible
       at java.lang.Enum$1.create(Enum.java:45)
       at java.lang.Enum$1.create(Enum.java:35)
       at libcore.util.BasicLruCache.get(BasicLruCache.java:54)
       at java.lang.Enum.getSharedConstants(Enum.java:211)
       at java.lang.Enum.valueOf(Enum.java:191)
       at org.jivesoftware.smack.roster.packet.RosterPacket$ItemType.valueOf(RosterPacket.java:315)
       at org.kontalk.service.msgcenter.SQLiteRosterStore.fromCursor(SQLiteRosterStore.java:155)
       at org.kontalk.service.msgcenter.SQLiteRosterStore.getEntries(SQLiteRosterStore.java:130)
       at org.jivesoftware.smack.roster.Roster$RosterResultListener.processPacket(Roster.java:1368)
       at org.jivesoftware.smack.AbstractXMPPConnection$5.processPacket(AbstractXMPPConnection.java:1428)
       at org.jivesoftware.smack.AbstractXMPPConnection$3.run(AbstractXMPPConnection.java:1105)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:818)
Caused by java.lang.NoSuchMethodException: values []
       at java.lang.Class.getDeclaredMethod(Class.java:635)
       at java.lang.Enum$1.create(Enum.java:41)
       at java.lang.Enum$1.create(Enum.java:35)
       at libcore.util.BasicLruCache.get(BasicLruCache.java:54)
       at java.lang.Enum.getSharedConstants(Enum.java:211)
       at java.lang.Enum.valueOf(Enum.java:191)
       at org.jivesoftware.smack.roster.packet.RosterPacket$ItemType.valueOf(RosterPacket.java:315)
       at org.kontalk.service.msgcenter.SQLiteRosterStore.fromCursor(SQLiteRosterStore.java:155)
       at org.kontalk.service.msgcenter.SQLiteRosterStore.getEntries(SQLiteRosterStore.java:130)
       at org.jivesoftware.smack.roster.Roster$RosterResultListener.processPacket(Roster.java:1368)
       at org.jivesoftware.smack.AbstractXMPPConnection$5.processPacket(AbstractXMPPConnection.java:1428)
       at org.jivesoftware.smack.AbstractXMPPConnection$3.run(AbstractXMPPConnection.java:1105)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:818)
```

**Comment by daniele-athome** [comment]
Related to Proguard. Already including Proguard rules for enums so it cannot really be reproduced.
