### ISSUE TITLE
Paused JID causing exception?

### ISSUE THREAD

**Issue by daniele-athome** [kontalk/androidclient#761]
Might this be caused by `sPaused` being an empty string? Do some tests.

```
android.database.sqlite.SQLiteException: not an error
       at android.database.sqlite.SQLiteQuery.nativeFillWindow(SQLiteQuery.java)
       at android.database.sqlite.SQLiteQuery.fillWindow(SQLiteQuery.java:86)
       at android.database.sqlite.SQLiteCursor.fillWindow(SQLiteCursor.java:169)
       at android.database.sqlite.SQLiteCursor.getCount(SQLiteCursor.java:161)
       at android.content.ContentResolver.query(ContentResolver.java:346)
       at org.kontalk.ui.MessagingNotification.updateMessagesNotification(MessagingNotification.java:208)
       at org.kontalk.Kontalk.onCreate(Kontalk.java:168)
       at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:969)
       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4136)
       at android.app.ActivityThread.access$1300(ActivityThread.java:135)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1286)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:137)
       at android.app.ActivityThread.main(ActivityThread.java:4645)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:511)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:809)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:576)
       at dalvik.system.NativeStart.main(NativeStart.java)
```

**Comment by daniele-athome** [comment]
Unable to reproduce in any way. Also, research produced no result, so closing for now (it was reported just one time on Crashlytics anyway).
