### ISSUE TITLE
Possible race condition for leaving activity while playing

### ISSUE THREAD

**Issue by daniele-athome** [kontalk/androidclient#764]
It shouldn't happen, test it out. updatePosition is called in a Runnable launched in the UI thread.

```
java.lang.NullPointerException
       at org.kontalk.ui.ComposeMessageFragment.updatePosition(ComposeMessageFragment.java:2897)
       at org.kontalk.ui.ComposeMessageFragment.access$4600(ComposeMessageFragment.java:150)
       at org.kontalk.ui.ComposeMessageFragment$30.run(ComposeMessageFragment.java:2999)
       at android.os.Handler.handleCallback(Handler.java:615)
       at android.os.Handler.dispatchMessage(Handler.java:92)
       at android.os.Looper.loop(Looper.java:177)
       at android.app.ActivityThread.main(ActivityThread.java:4947)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:511)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1038)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:805)
       at dalvik.system.NativeStart.main(NativeStart.java)
```

**Comment by daniele-athome** [comment]
Unable to reproduce.
