### ISSUE TITLE
Handle stanza parsing from rogue server

### ISSUE THREAD

**Issue by daniele-athome** [kontalk/androidclient#765]
Related to #759, but in this case it's the packet reader thread, so possibly no control over it. Investigate workarounds or report to Smack (at least notify the exception, don't just crash the thread).

```
java.lang.AssertionError: impossible
       at java.lang.Enum$1.create(Enum.java:45)
       at java.lang.Enum$1.create(Enum.java:35)
       at libcore.util.BasicLruCache.get(BasicLruCache.java:54)
       at java.lang.Enum.getSharedConstants(Enum.java:211)
       at java.lang.Enum.valueOf(Enum.java:191)
       at org.jivesoftware.smack.packet.Message$Type.valueOf(Message.java:607)
       at org.jivesoftware.smack.packet.Message$Type.fromString(Message.java:644)
       at org.jivesoftware.smack.util.PacketParserUtils.parseMessage(PacketParserUtils.java:229)
       at org.jivesoftware.smack.util.PacketParserUtils.parseStanza(PacketParserUtils.java:151)
       at org.jivesoftware.smack.AbstractXMPPConnection.parseAndProcessStanza(AbstractXMPPConnection.java:955)
       at org.kontalk.client.XMPPTCPConnection.access$500(XMPPTCPConnection.java:140)
       at org.kontalk.client.XMPPTCPConnection$PacketReader.parsePackets(XMPPTCPConnection.java:997)
       at org.kontalk.client.XMPPTCPConnection$PacketReader.access$300(XMPPTCPConnection.java:952)
       at org.kontalk.client.XMPPTCPConnection$PacketReader$1.run(XMPPTCPConnection.java:967)
       at java.lang.Thread.run(Thread.java:818)
Caused by java.lang.NoSuchMethodException: values []
       at java.lang.Class.getDeclaredMethod(Class.java:635)
       at java.lang.Enum$1.create(Enum.java:41)
       at java.lang.Enum$1.create(Enum.java:35)
       at libcore.util.BasicLruCache.get(BasicLruCache.java:54)
       at java.lang.Enum.getSharedConstants(Enum.java:211)
       at java.lang.Enum.valueOf(Enum.java:191)
       at org.jivesoftware.smack.packet.Message$Type.valueOf(Message.java:607)
       at org.jivesoftware.smack.packet.Message$Type.fromString(Message.java:644)
       at org.jivesoftware.smack.util.PacketParserUtils.parseMessage(PacketParserUtils.java:229)
       at org.jivesoftware.smack.util.PacketParserUtils.parseStanza(PacketParserUtils.java:151)
       at org.jivesoftware.smack.AbstractXMPPConnection.parseAndProcessStanza(AbstractXMPPConnection.java:955)
       at org.kontalk.client.XMPPTCPConnection.access$500(XMPPTCPConnection.java:140)
       at org.kontalk.client.XMPPTCPConnection$PacketReader.parsePackets(XMPPTCPConnection.java:997)
       at org.kontalk.client.XMPPTCPConnection$PacketReader.access$300(XMPPTCPConnection.java:952)
       at org.kontalk.client.XMPPTCPConnection$PacketReader$1.run(XMPPTCPConnection.java:967)
       at java.lang.Thread.run(Thread.java:818)
```

**Comment by daniele-athome** [comment]
Related to Proguard. Already including Proguard rules for enums so it cannot really be reproduced.
