### ISSUE TITLE
Investigate multiuser support

### ISSUE THREAD

**Issue by daniele-athome** [kontalk/androidclient#766]
Kontalk shouldn't support multiuser, so why is this exception occuring?
Android 5.1.1 on a strange chinese device. It might just be bogus firmware.

```
java.lang.SecurityException: Permission Denial: get/set setting for user asks to run as user 10 but is calling from user 0; this requires android.permission.INTERACT_ACROSS_USERS_FULL
       at android.os.Parcel.readException(Parcel.java:1546)
       at android.os.Parcel.readException(Parcel.java:1499)
       at android.app.IAlarmManager$Stub$Proxy.set(IAlarmManager.java:197)
       at android.app.AlarmManager.setImpl(AlarmManager.java:416)
       at android.app.AlarmManager.setInexactRepeating(AlarmManager.java:517)
       at org.kontalk.service.msgcenter.MessageCenterService.setIdleAlarm(MessageCenterService.java:2633)
       at org.kontalk.service.msgcenter.MessageCenterService.inactive(MessageCenterService.java:1411)
       at org.kontalk.service.msgcenter.MessageCenterService.access$200(MessageCenterService.java:148)
       at org.kontalk.service.msgcenter.MessageCenterService$IdleConnectionHandler.handleMessage(MessageCenterService.java:440)
       at org.kontalk.service.msgcenter.MessageCenterService$IdleConnectionHandler.handleMessage(MessageCenterService.java:420)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:135)
       at android.os.HandlerThread.run(HandlerThread.java:61)
```

**Comment by daniele-athome** [comment]
Multiuser seems to work just fine, closing as bogus firmware/system bug for now.
