### ISSUE TITLE
NPE on keys importing

### ISSUE THREAD

**Issue by relan** [kontalk/androidclient#790]
NPE happens every time I try to import keys from the welcome screen. I'm on aa7cf877807700584623eb7adb44109834c99e12, Android 6.0.1.

#### How reproducible

5/5

#### Steps to reproduce

1. In Kontalk 3.1.10 (F-Droid build) export `kontalk-keys.zip`.
2. Start Kontalk built from `master`.
3. In the welcome screen enter your nick and phone number.
4. Choose Import keys from the toolbar menu.
5. Navigate to `kontalk-keys.zip` and tap it.
6. Enter the password.

#### Actual result

Keys importing fails with
```
E NumberValidation: error importing keys
E NumberValidation: java.lang.NullPointerException: Attempt to invoke virtual method 'byte[] java.lang.String.getBytes()' on a null object reference
E NumberValidation: 	at org.kontalk.util.MessageUtils.sha1(MessageUtils.java:206)
E NumberValidation: 	at org.kontalk.ui.NumberValidation.startImport(NumberValidation.java:763)
E NumberValidation: 	at org.kontalk.ui.NumberValidation.access$400(NumberValidation.java:113)
E NumberValidation: 	at org.kontalk.ui.NumberValidation$6.onInput(NumberValidation.java:673)
E NumberValidation: 	at com.afollestad.materialdialogs.MaterialDialog.onClick(MaterialDialog.java:370)
E NumberValidation: 	at android.view.View.performClick(View.java:5204)
E NumberValidation: 	at android.view.View$PerformClick.run(View.java:21153)
E NumberValidation: 	at android.os.Handler.handleCallback(Handler.java:739)
E NumberValidation: 	at android.os.Handler.dispatchMessage(Handler.java:95)
E NumberValidation: 	at android.os.Looper.loop(Looper.java:148)
E NumberValidation: 	at android.app.ActivityThread.main(ActivityThread.java:5417)
E NumberValidation: 	at java.lang.reflect.Method.invoke(Native Method)
E NumberValidation: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
E NumberValidation: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

#### Expected result

New Kontalk version should support old `kontalk-keys.zip` format. Otherwise users won't be able to restore their keys from a backup made with earlier versions.

**Comment by daniele-athome** [comment]
Thanks for reporting! I'll look into it.

**Comment by abika** [comment]
Fixed: you have to enter the phone number again if it is not included in the key archive
