### ISSUE TITLE
Race condition on tablets

### ISSUE THREAD

**Issue by daniele-athome** [kontalk/androidclient#793]
From version 3.1.10.

```
java.lang.RuntimeException: Unable to start activity ComponentInfo{org.kontalk/org.kontalk.ui.ConversationsActivity}: java.lang.NullPointerException
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2347)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2397)
       at android.app.ActivityThread.access$1100(ActivityThread.java:143)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1286)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:136)
       at android.app.ActivityThread.main(ActivityThread.java:5398)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:864)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:680)
       at dalvik.system.NativeStart.main(NativeStart.java)
Caused by java.lang.NullPointerException
       at org.kontalk.ui.ConversationsActivity.openConversation(ConversationsActivity.java:280)
       at org.kontalk.ui.ConversationsActivity.handleIntent(ConversationsActivity.java:127)
       at org.kontalk.ui.ConversationsActivity.onCreate(ConversationsActivity.java:89)
       at android.app.Activity.performCreate(Activity.java:5301)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1090)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2311)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2397)
       at android.app.ActivityThread.access$1100(ActivityThread.java:143)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1286)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:136)
       at android.app.ActivityThread.main(ActivityThread.java:5398)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:864)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:680)
       at dalvik.system.NativeStart.main(NativeStart.java)
```

**Comment by daniele-athome** [comment]
Unable to reproduce.
