### ISSUE TITLE
Contactlist stay empty

### ISSUE THREAD

**Issue by webratte** [kontalk/androidclient#802]
Title say what happens.

Kontalk V.4.0.0 alpha 4

**Comment by daniele-athome** [comment]
I know, sorry I just discovered a couple of major bugs. I'll publish a new apk in a few minutes.

**Comment by webratte** [comment]
Thank you 👍

**Comment by TheLastProject** [comment]
For what it's worth, although I assume it's known, I expect this to be caused by `mListAdapter.changeCursor(mCursor);` being commented out in c380a2e38397aaa3514947262afc72ee9f7b78c6, which probably happened to test the situation in the case of an empty contact list.

**Comment by daniele-athome** [comment]
Damn I hoped no one saw that!!

:-)

**Comment by TheLastProject** [comment]
I don't think anyone will mind after all the other awesome commits made for the project. After all, we all commit debug code sometimes :)

**Comment by abika** [comment]
that's why we have Git: to keep record of all the mistakes we made .)

other problems: crash when adding/removing group members:
```
java.lang.RuntimeException: Unable to start service org.kontalk.service.msgcenter.MessageCenterService@a51c3490 with Intent { act=org.kontalk.action.MESSAGE cmp=org.kontalk.debug/org.kontalk.service.msgcenter.MessageCenterService (has extras) }: java.lang.IllegalStateException: no encryption methods specified
at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:2719)
                                                                     at android.app.ActivityThread.access$2100(ActivityThread.java:135)
                                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1293)
                                                                     at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                     at android.os.Looper.loop(Looper.java:136)
                                                                     at android.app.ActivityThread.main(ActivityThread.java:5017)
                                                                     at java.lang.reflect.Method.invokeNative(Native Method)
                                                                     at java.lang.reflect.Method.invoke(Method.java:515)
                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
```

And removing and adding a group member again does not work: removing works fine but after the removed member get the 'set' message, it shows up in the chat ("Users added: Bob") but the member list does not change.

**Comment by daniele-athome** [comment]
@abika would you mind opening an issue for that? I'll release a new apk in a few minutes but I don't have enough time to fix also that tonight.

**Comment by daniele-athome** [comment]
@abika you know what never mind. I'll just store the stacktrace. I don't want to pollute issues with even the smallest bug. It's alpha stage anyway :-)

**Comment by abika** [comment]
I just didn't know if you were already aware of these. Sure, will test again tomorrow and open issues with more details if necessary
