### ISSUE TITLE
Impossible to export personal key

### ISSUE THREAD

**Issue by webratte** [kontalk/androidclient#848]
### Expected behavior
Key should be stored on SD card or internal storage

### Actual behavior
The export ends with errormessage like "key can't be exported" I don't know the exact english sentence.

### Steps to reproduce
1. Trie to export the personal key
2. After it finished with error take a look into the choosed folder
3. In this folder is a file kontalk-key.zip with 0kb

### Environment

Kontalk version: 4.0.0-alpha6 (205)
Android version: 6.0.1

Device model: Sony M4 Aqua - E2303

### Other

I hope a error log is sended autocratically via chrashlytics

I would test a fresh exported key to check out this issue in desktop client "Impossible to import personal key" https://github.com/kontalk/desktopclient-java/issues/97

**Comment by abika** [comment]
Can confirm with current git in emulator (API19). Exception from log:
```
10-23 12:16:14.341 1927-1927/org.kontalk.debug E/CursorWindow: Failed to read row 0, column 3 from a CursorWindow which has 4 rows, 3 columns.
10-23 12:16:14.361 1927-1927/org.kontalk.debug E/Kontalk: error exporting keys
                                                          java.lang.IllegalStateException: Couldn't read row 0, col 3 from CursorWindow.  Make sure the Cursor is initialized correctly before accessing data from it.
                                                              at android.database.CursorWindow.nativeGetLong(Native Method)
                                                              at android.database.CursorWindow.getLong(CursorWindow.java:507)
                                                              at android.database.CursorWindow.getInt(CursorWindow.java:574)
                                                              at android.database.AbstractWindowedCursor.getInt(AbstractWindowedCursor.java:69)
                                                              at android.database.CursorWrapper.getInt(CursorWrapper.java:102)
                                                              at org.kontalk.provider.Keyring.getTrustedKeys(Keyring.java:203)
                                                              at org.kontalk.authenticator.Authenticator.exportDefaultPersonalKey(Authenticator.java:196)
                                                              at org.kontalk.Kontalk.exportPersonalKey(Kontalk.java:244)
                                                              at org.kontalk.ui.prefs.MaintenanceFragment.exportPersonalKey(MaintenanceFragment.java:331)
                                                              at org.kontalk.ui.prefs.MaintenanceFragment.onActivityResult(MaintenanceFragment.java:359)
                                                              at android.support.v4.app.FragmentActivity.onActivityResult(FragmentActivity.java:165)
                                                              at android.app.Activity.dispatchActivityResult(Activity.java:5423)
                                                              at android.app.ActivityThread.deliverResults(ActivityThread.java:3361)
                                                              at android.app.ActivityThread.handleSendResult(ActivityThread.java:3408)
                                                              at android.app.ActivityThread.access$1300(ActivityThread.java:135)
                                                              at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1244)
                                                              at android.os.Handler.dispatchMessage(Handler.java:102)
                                                              at android.os.Looper.loop(Looper.java:136)
                                                              at android.app.ActivityThread.main(ActivityThread.java:5017)
                                                              at java.lang.reflect.Method.invokeNative(Native Method)
                                                              at java.lang.reflect.Method.invoke(Method.java:515)
                                                              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
                                                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
                                                              at dalvik.system.NativeStart.main(Native Method)
```

**Comment by daniele-athome** [comment]
Thanks guys, I'll get right on it.
