### ISSUE TITLE
Paperclip crashes kontalk

### ISSUE THREAD

**Issue by Megver83** [kontalk/androidclient#922]
### Expected behavior
Touch and close the paperclip in chats (both groups and contacts) without crashing Kontalk.

### Actual behavior
Touch the paperclip, and when closing it Kontalk crashes.

### Steps to reproduce
1. Open a chat
2. Touch the paperclip
3. Close the paperclip

### Environment

Kontalk version: 4.0.0-beta5 (F-Droid)

Android version: Replicant 6.0, Android Marshmallow

Device model: Samsung Galaxy S3 i9300

### Other

I've test the same Kontalk version in a Galaxy J5 (without custom ROM), and worked OK. Maybe it's a Replicant issue (like graphics acceleration?)

**Comment by daniele-athome** [comment]
It could be a Replicant issue, yes. Can you provide a system log please? You may send it to devteam (at) kontalk.org

https://github.com/kontalk/androidclient/wiki/How-to-create-a-system-log-%28logcat%29

**Comment by Megver83** [comment]
Sent! I was reading the log, it seems it's a permissions issue

**Comment by daniele-athome** [comment]
@Megver83 please check if there is some feature to allow/deny some permissions in some way (although it seems strange that an app is denied to write in its own data directory).

**Comment by daniele-athome** [comment]
Wait you said Kontalk crashed, but I can't see the error in the log. Are you sure the log is complete?

**Comment by Megver83** [comment]
Yes it is complete. The only feature I found for permissions was in the settings, and I gave Kontalk all the permissions (microphone, file access, etc).

> it seems strange that an app is denied to write in its own data directory

I agree, what can it be?

**Comment by daniele-athome** [comment]
No idea, seriously. It also seems that files are created, it's the chmod that isn't working.
However, without a crash report I can't possibly know what is happening. Can you send a complete system log to the devteam email after having reproduced the crash please? Complete as in not only from Kontalk process. There must be something that's being traced.

**Comment by Megver83** [comment]
ok, and how do I do that?

**Comment by daniele-athome** [comment]
If you followed the procedure in the wiki page, execute the adb command without the filters:

```
adb logcat -d >kontalk-log.txt
```

It may contain personal data so do not post it here, be sure to send it via email only.

**Comment by Megver83** [comment]
I'll try, my email is failing a little

**Comment by daniele-athome** [comment]
Here is the crash:

```
java.lang.NullPointerException: Attempt to invoke virtual method 'long com.android.internal.util.VirtualRefBasePtr.get()' on a null object reference
    at android.view.RenderNodeAnimator.applyInterpolator(RenderNodeAnimator.java:171)
    at android.view.RenderNodeAnimator.start(RenderNodeAnimator.java:185)
    at io.codetail.animation.SupportAnimatorLollipop.start(SupportAnimatorLollipop.java:35)
    at org.kontalk.ui.view.AttachmentRevealFrameLayout.hide(AttachmentRevealFrameLayout.java:131)
    at org.kontalk.ui.view.AttachmentRevealFrameLayout.hide(AttachmentRevealFrameLayout.java:120)
    at org.kontalk.ui.view.AttachmentRevealFrameLayout.toggle(AttachmentRevealFrameLayout.java:137)
    at org.kontalk.ui.AbstractComposeFragment.toggleAttachmentView(AbstractComposeFragment.java:931)
    at org.kontalk.ui.AbstractComposeFragment.onOptionsItemSelected(AbstractComposeFragment.java:775)
    at org.kontalk.ui.ComposeMessageFragment.onOptionsItemSelected(ComposeMessageFragment.java:122)
    at android.support.v4.app.Fragment.performOptionsItemSelected(Fragment.java:2309)
    at android.support.v4.app.FragmentManagerImpl.dispatchOptionsItemSelected(FragmentManager.java:2973)
    at android.support.v4.app.FragmentController.dispatchOptionsItemSelected(FragmentController.java:353)
    at android.support.v4.app.FragmentActivity.onMenuItemSelected(FragmentActivity.java:414)
    at android.support.v7.app.AppCompatActivity.onMenuItemSelected(AppCompatActivity.java:198)
    at android.support.v7.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:113)
    at android.support.v7.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:113)
    at android.support.v7.app.ToolbarActionBar$2.onMenuItemClick(ToolbarActionBar.java:69)
    at android.support.v7.widget.Toolbar$1.onMenuItemClick(Toolbar.java:206)
    at android.support.v7.widget.ActionMenuView$MenuBuilderCallback.onMenuItemSelected(ActionMenuView.java:776)
    at android.support.v7.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:822)
    at android.support.v7.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:156)
    at android.support.v7.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:969)
    at android.support.v7.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:959)
    at android.support.v7.widget.ActionMenuView.invokeItem(ActionMenuView.java:623)
    at android.support.v7.view.menu.ActionMenuItemView.onClick(ActionMenuItemView.java:154)
    at android.view.View.performClick(View.java:5204)
    at android.view.View$PerformClick.run(View.java:21158)
    at android.os.Handler.handleCallback(Handler.java:739)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at android.os.Looper.loop(Looper.java:148)
    at android.app.ActivityThread.main(ActivityThread.java:5461)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

However, I don't really know how to handle it. I've investigated into Android source code, seems that the pointer is destroyed when the animation ends:

https://android.googlesource.com/platform/frameworks/base/+/77bdfb5/core/java/android/view/RenderNodeAnimator.java

However, the animation is just starting.
I found only one other reported (unsolved) case here: ogaclejapan/ArcLayout#27

Does the crash also happens if you click on the paperclip and then exit the activity by pressing the device home button, while the attachments section is still open?

**Comment by Megver83** [comment]
no, it only happens is I press back. Pressing home closes the app, and that doesn't crash it
