### ISSUE TITLE
Crash opening conversation on tablet

### ISSUE THREAD

**Issue by daniele-athome** [kontalk/androidclient#953]
Reported on a Samsung Galaxy Tab running Android 6.0.1. More than once, so it doesn't seem like a race condition.

```
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String org.kontalk.data.Conversation.getRecipient()' on a null object reference
       at org.kontalk.ui.ConversationsActivity.openConversation(ConversationsActivity.java:457)
       at org.kontalk.ui.ConversationsActivity.openConversation(ConversationsActivity.java:443)
       at org.kontalk.ui.ConversationsActivity.handleIntent(ConversationsActivity.java:151)
       at org.kontalk.ui.ConversationsActivity.onCreate(ConversationsActivity.java:103)
```

**Comment by daniele-athome** [comment]
```
java.lang.RuntimeException: Unable to start activity ComponentInfo{org.kontalk/org.kontalk.ui.ConversationsActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String org.kontalk.data.Conversation.getRecipient()' on a null object reference
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3184)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3294)
       at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:5198)
       at android.app.ActivityThread.access$1100(ActivityThread.java:210)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1710)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:145)
       at android.app.ActivityThread.main(ActivityThread.java:6934)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)
Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String org.kontalk.data.Conversation.getRecipient()' on a null object reference
       at org.kontalk.ui.ConversationsActivity.openConversation(ConversationsActivity.java:418)
       at org.kontalk.ui.ConversationsActivity.openConversation(ConversationsActivity.java:405)
       at org.kontalk.ui.ConversationsActivity.handleIntent(ConversationsActivity.java:144)
       at org.kontalk.ui.ConversationsActivity.onCreate(ConversationsActivity.java:103)
       at android.app.Activity.performCreate(Activity.java:6575)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1134)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3137)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3294)
       at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:5198)
       at android.app.ActivityThread.access$1100(ActivityThread.java:210)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1710)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:145)
       at android.app.ActivityThread.main(ActivityThread.java:6934)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)
```
