### ISSUE TITLE
Smack concurrency issue for ping failed listener

### ISSUE THREAD

**Issue by daniele-athome** [kontalk/androidclient#955]
Most probably a race condition issue in Smack. Will track Smack issue here:

```
java.util.ConcurrentModificationException
       at java.util.HashMap$HashIterator.nextEntry(HashMap.java:788)
       at java.util.HashMap$KeyIterator.next(HashMap.java:815)
       at org.jivesoftware.smackx.ping.PingManager.pingMyServer(PingManager.java:252)
       at org.kontalk.service.msgcenter.MessageCenterService$3.run(MessageCenterService.java:1114)
       at java.lang.Thread.run(Thread.java:818)
```

A synchronized Set is used for PingFailedListeners, howver, access to it [should be synchronized manually](https://docs.oracle.com/javase/7/docs/api/java/util/Collections.html#synchronizedSet(java.util.Set)):

```
Set s = Collections.synchronizedSet(new HashSet());
      ...
synchronized (s) {
      Iterator i = s.iterator(); // Must be in the synchronized block
      while (i.hasNext())
          foo(i.next());
}
```

---

https://community.igniterealtime.org/message/263095

**Comment by daniele-athome** [comment]
Waiting for Smack release.

https://github.com/Flowdalic/Smack/commit/6cfdf2bc6ff9c3a7c0cf0ff6c7bb9507c77f95fc

**Comment by daniele-athome** [comment]
[Support for 4.1 was dropped](https://community.igniterealtime.org/message/263191#comment-263191), fork of the class will be needed.
