### ISSUE TITLE
Registration fails as kontalk.halifax.rwth-aachen.de seems to be down

### ISSUE THREAD

**Issue by svrnwnsch** [kontalk/androidclient#962]
The registration on a device fails with Kontalk 4.0. 

The following log seems to indicate that the server for Numbervalidation in Germany seems to be down (kontalk.halifax.rwth-aachen.de). I checkt this by trying to ping the server from different locations (http://maplatency.com/070587e9-9f00-4307-a53d-ace66cc135af). 

What makes me wonder is that there seems to be only one server in the list for number valididation.

```
W/NumberValidator: connection error - trying next server in list
W/NumberValidator: org.jivesoftware.smack.SmackException$ConnectionException: The following addresses failed: 'kontalk.halifax.rwth-aachen.de:5222' failed because java.net.ConnectException: failed to connect to kontalk.halifax.rwth-aachen.de/137.226.111.112 (port 5222) after 30000ms: isConnected failed: ECONNREFUSED (Connection refused)
	at org.kontalk.client.XMPPTCPConnection.connectUsingConfiguration(XMPPTCPConnection.java:612)
	at org.kontalk.client.XMPPTCPConnection.connectInternal(XMPPTCPConnection.java:850)
	at org.jivesoftware.smack.AbstractXMPPConnection.connect(AbstractXMPPConnection.java:364)
	at org.kontalk.service.XMPPConnectionHelper.connectOnce(XMPPConnectionHelper.java:196)
	at org.kontalk.service.XMPPConnectionHelper.connectOnce(XMPPConnectionHelper.java:145)
	at org.kontalk.client.NumberValidator.initConnection(NumberValidator.java:545)
	at org.kontalk.client.NumberValidator.run(NumberValidator.java:256)
	at java.lang.Thread.run(Thread.java:818)

E/NumberValidation: validation error.
E/NumberValidation: org.jivesoftware.smack.SmackException$NoResponseException: No response received within reply timeout. Timeout was 15000ms (~15s). Used filter: No filter used or filter was 'null'.
	at org.jivesoftware.smack.SynchronizationPoint.checkForResponse(SynchronizationPoint.java:253)
	at org.jivesoftware.smack.SynchronizationPoint.checkIfSuccessOrWait(SynchronizationPoint.java:146)
	at org.jivesoftware.smack.SynchronizationPoint.checkIfSuccessOrWaitOrThrow(SynchronizationPoint.java:125)
	at org.kontalk.client.XMPPTCPConnection.connectInternal(XMPPTCPConnection.java:857)
	at org.jivesoftware.smack.AbstractXMPPConnection.connect(AbstractXMPPConnection.java:364)
	at org.kontalk.service.XMPPConnectionHelper.connectOnce(XMPPConnectionHelper.java:196)
	at org.kontalk.service.XMPPConnectionHelper.connectOnce(XMPPConnectionHelper.java:145)
	at org.kontalk.client.NumberValidator.initConnection(NumberValidator.java:545)
	at org.kontalk.client.NumberValidator.run(NumberValidator.java:256)
	at org.kontalk.client.NumberValidator.run(NumberValidator.java:265)
	at java.lang.Thread.run(Thread.java:818)

W/NumberValidator: shutting down
W/NumberValidator: exiting
W/NumberValidator: connection error - trying next server in list
W/NumberValidator: org.jivesoftware.smack.SmackException$NoResponseException: No response received within reply timeout. Timeout was 15000ms (~15s). Used filter: No filter used or filter was 'null'.
	at org.jivesoftware.smack.SynchronizationPoint.checkForResponse(SynchronizationPoint.java:253)
	at org.jivesoftware.smack.SynchronizationPoint.checkIfSuccessOrWait(SynchronizationPoint.java:146)
	at org.jivesoftware.smack.SynchronizationPoint.checkIfSuccessOrWaitOrThrow(SynchronizationPoint.java:125)
	at org.kontalk.client.XMPPTCPConnection.connectInternal(XMPPTCPConnection.java:857)
	at org.jivesoftware.smack.AbstractXMPPConnection.connect(AbstractXMPPConnection.java:364)
	at org.kontalk.service.XMPPConnectionHelper.connectOnce(XMPPConnectionHelper.java:196)
	at org.kontalk.service.XMPPConnectionHelper.connectOnce(XMPPConnectionHelper.java:145)
	at org.kontalk.client.NumberValidator.initConnection(NumberValidator.java:545)
	at org.kontalk.client.NumberValidator.run(NumberValidator.java:256)
	at java.lang.Thread.run(Thread.java:818)

E/NumberValidation: validation error.
E/NumberValidation: org.jivesoftware.smack.SmackException$ConnectionException: The following addresses failed: 'kontalk.halifax.rwth-aachen.de:5222' failed because java.net.ConnectException: failed to connect to kontalk.halifax.rwth-aachen.de/137.226.111.112 (port 5222) after 30000ms: isConnected failed: ECONNREFUSED (Connection refused)
	at org.kontalk.client.XMPPTCPConnection.connectUsingConfiguration(XMPPTCPConnection.java:612)
	at org.kontalk.client.XMPPTCPConnection.connectInternal(XMPPTCPConnection.java:850)
	at org.jivesoftware.smack.AbstractXMPPConnection.connect(AbstractXMPPConnection.java:364)
	at org.kontalk.service.XMPPConnectionHelper.connectOnce(XMPPConnectionHelper.java:196)
	at org.kontalk.service.XMPPConnectionHelper.connectOnce(XMPPConnectionHelper.java:145)
	at org.kontalk.client.NumberValidator.initConnection(NumberValidator.java:545)
	at org.kontalk.client.NumberValidator.run(NumberValidator.java:256)
	at org.kontalk.client.NumberValidator.run(NumberValidator.java:265)
	at java.lang.Thread.run(Thread.java:818)

W/NumberValidator: shutting down
W/NumberValidator: exiting
```

**Comment by daniele-athome** [comment]
The halifax server has been down for several months. It's weird that you can't register because the other (our main) server is up and running. Anyway, you probably have an old list in the cache. As a workaround, please go to system settings > apps > Kontalk > Clear cache. In the meantime I've opened #963.

**Comment by svrnwnsch** [comment]
Thank you, this fixed my problem.
