### ISSUE TITLE
Crash when resuming activity from another app

### ISSUE THREAD

**Issue by daniele-athome** [kontalk/androidclient#982]
Probable race condition between fragment transactions.

```
java.lang.RuntimeException: Unable to start activity ComponentInfo{org.kontalk.debug/org.kontalk.ui.ComposeMessage}: java.lang.IllegalStateException: FragmentManager is already executing transactions
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2339)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2413)
	at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:4032)
	at android.app.ActivityThread.access$900(ActivityThread.java:155)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1323)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5343)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:905)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:700)
	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:102)
Caused by: java.lang.IllegalStateException: FragmentManager is already executing transactions
	at android.support.v4.app.FragmentManagerImpl.ensureExecReady(FragmentManager.java:1956)
	at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2007)
	at android.support.v4.app.FragmentManagerImpl.executePendingTransactions(FragmentManager.java:763)
	at org.kontalk.ui.AbstractComposeFragment.getAudioFragment(AbstractComposeFragment.java:1084)
	at org.kontalk.ui.AbstractComposeFragment.processArguments(AbstractComposeFragment.java:1389)
	at org.kontalk.ui.AbstractComposeFragment.onActivityCreated(AbstractComposeFragment.java:286)
	at android.support.v4.app.Fragment.performActivityCreated(Fragment.java:2201)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1326)
	at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1528)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1595)
	at android.support.v4.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:2900)
	at android.support.v4.app.FragmentController.dispatchActivityCreated(FragmentController.java:201)
	at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:603)
	at android.support.v7.app.AppCompatActivity.onStart(AppCompatActivity.java:178)
	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1259)
	at android.app.Activity.performStart(Activity.java:6026)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2302)
	... 12 more
```

**Comment by daniele-athome** [comment]
Should be fixed in 4.0.3.
