### ISSUE TITLE
Pending fragment transactions

### ISSUE THREAD

**Issue by daniele-athome** [kontalk/androidclient#994]
This needs a hotfix.

```
java.lang.RuntimeException: Unable to start activity ComponentInfo{org.kontalk/org.kontalk.ui.ComposeMessage}: java.lang.IllegalStateException: FragmentManager is already executing transactions
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2230)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2279)
       at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:3812)
       at android.app.ActivityThread.access$900(ActivityThread.java:143)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1248)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:136)
       at android.app.ActivityThread.main(ActivityThread.java:5124)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:797)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:613)
       at dalvik.system.NativeStart.main(NativeStart.java)
Caused by java.lang.IllegalStateException: FragmentManager is already executing transactions
       at android.support.v4.app.FragmentManagerImpl.ensureExecReady(FragmentManager.java:1956)
       at android.support.v4.app.FragmentManagerImpl.execSingleAction(FragmentManager.java:1980)
       at android.support.v4.app.BackStackRecord.commitNow(BackStackRecord.java:620)
       at org.kontalk.ui.AbstractComposeFragment.getAudioFragment(AbstractComposeFragment.java:1083)
       at org.kontalk.ui.AbstractComposeFragment.processArguments(AbstractComposeFragment.java:1388)
       at org.kontalk.ui.AbstractComposeFragment.onActivityCreated(AbstractComposeFragment.java:286)
       at android.support.v4.app.Fragment.performActivityCreated(Fragment.java:2201)
       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1326)
       at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1528)
       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1595)
       at android.support.v4.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:2900)
       at android.support.v4.app.FragmentController.dispatchActivityCreated(FragmentController.java:201)
       at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:603)
       at android.support.v7.app.AppCompatActivity.onStart(AppCompatActivity.java:178)
       at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1171)
       at android.app.Activity.performStart(Activity.java:5251)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2203)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2279)
       at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:3812)
       at android.app.ActivityThread.access$900(ActivityThread.java:143)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1248)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:136)
       at android.app.ActivityThread.main(ActivityThread.java:5124)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:797)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:613)
       at dalvik.system.NativeStart.main(NativeStart.java)
```

**Comment by daniele-athome** [comment]
This article is slightly related to this issue:
https://medium.com/@elye.project/new-in-support-library-25-1-0-android-disallow-commitnow-on-onbackstackchanged-227c651eefb2

Not strictly the same cause, but the effect is the same. We can't call `getAudioFragment()` from `processArguments()`.
